"""
Write frontend/launcher/renderer/dota-data.js: hero ids, names and picture keys
(from app.dota_constants) and item display names -> picture keys (from
OpenDota's dotaconstants), used by the launcher to show hero portraits and item
icons. Run from backend/ after a patch adds heroes or items:

    python scripts/build_dota_data.py
    python scripts/build_dota_data.py --items /path/to/dotaconstants/build/items.json
    python scripts/build_dota_data.py --check-heroes   # exit 1 when a hero is missing

New heroes also need a line in app/dota_constants.py HEROES; --check-heroes
compares it with OpenDota's heroes.json (names may differ: HEROES keeps the
in-game ones). .github/workflows/dota-data.yml runs both every week.
"""

from __future__ import annotations

import argparse
import json
import sys
import urllib.request
from pathlib import Path

BACKEND_DIR = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(BACKEND_DIR))

from app.dota_constants import HEROES  # noqa: E402

ITEMS_URL = "https://raw.githubusercontent.com/odota/dotaconstants/master/build/items.json"
HEROES_URL = "https://raw.githubusercontent.com/odota/dotaconstants/master/build/heroes.json"
OUT = BACKEND_DIR.parent / "frontend" / "launcher" / "renderer" / "dota-data.js"


def load_items(path: str | None) -> dict[str, dict]:
    if path:
        return json.loads(Path(path).read_text(encoding="utf-8"))
    with urllib.request.urlopen(ITEMS_URL, timeout=30) as response:  # noqa: S310 - fixed URL
        return json.loads(response.read().decode("utf-8"))


def missing_heroes(remote: dict[str, dict]) -> dict[int, str]:
    """Heroes in OpenDota's heroes.json that HEROES does not have (id -> name)."""
    return {
        int(key): str(info.get("localized_name") or info.get("name") or key)
        for key, info in remote.items()
        if str(key).isdigit() and int(key) not in HEROES
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[1])
    parser.add_argument("--items", help="a local copy of dotaconstants build/items.json")
    parser.add_argument(
        "--check-heroes", action="store_true", help="fail when OpenDota has a hero HEROES lacks"
    )
    args = parser.parse_args()

    if args.check_heroes:
        with urllib.request.urlopen(HEROES_URL, timeout=30) as response:  # noqa: S310
            missing = missing_heroes(json.loads(response.read().decode("utf-8")))
        for hero_id, name in sorted(missing.items()):
            print(f"missing hero {hero_id}: {name} (add it to app/dota_constants.py HEROES)")
        sys.exit(1 if missing else 0)

    heroes = {
        str(hero_id): [name, npc.removeprefix("npc_dota_hero_")]
        for hero_id, (name, npc) in sorted(HEROES.items())
    }
    items: dict[str, str] = {}
    for key, info in sorted(load_items(args.items).items()):
        name = str(info.get("dname") or "").strip()
        if not name or key.startswith("recipe_") or not info.get("img"):
            continue
        items.setdefault(name, key)
    body = json.dumps({"heroes": heroes, "items": items}, ensure_ascii=False, indent=0)
    OUT.write_text(
        "// Generated by backend/scripts/build_dota_data.py - do not edit by hand.\n"
        "// Hero id -> [name, picture key]; item name -> picture key.\n"
        f"window.DotaData = {body};\n",
        encoding="utf-8",
    )
    print(f"{OUT}: {len(heroes)} heroes, {len(items)} items")


if __name__ == "__main__":
    main()
