"use strict";

// Control-panel UK/EN copy is independent of DOM and IPC. A fresh catalog keeps
// update history and nested text tables local to the current panel instance.
(function () {
  function create(whatsNew) {
    const I18N = {
      en: {
        tabHome: "Home",
        tabMatches: "Matches",
        tabProgress: "Progress",
        tabProfile: "Profile",
        tabSettings: "Settings",
        adviceSettingsTitle: "Advice",
        languageTitle: "Language",
        languageHint: "Advice, reviews and the whole app",
        languageAuto: "Auto",
        uiScaleTitle: "Interface size",
        uiScaleHint: "Bigger text and buttons for a large or high-resolution screen. Ctrl + plus and Ctrl + minus work too.",
        uiScaleToast: (size) => `Interface size: ${size}`,
        dataTitle: "Match history",
        odTitle: "Faster match history",
        odPlaceholder: "OpenDota key",
        odSave: "Save",
        odGet: "Get a key on opendota.com",
        odClear: "Remove key",
        odHintOff: "Your match history comes from OpenDota, a free Dota statistics site. Everything works without a key, just slower. A free key from opendota.com makes it faster; it stays on this computer.",
        odHintOn: (hint) => `Key ${hint} saved: your matches load faster.`,
        odHintEnv: "A key is already set in the app's settings file.",
        odBad: "This does not look like an OpenDota key.",
        appTitle: "Main",
        service: "Coach",
        serviceStates: { running: "running", starting: "starting…", stopping: "stopping…", stopped: "stopped" },
        status: {
          loadingTitle: "Starting the coach…",
          loadingHint: "Usually takes a couple of seconds.",
          backendDownTitle: "The coach is stopped",
          backendDownHint: "No advice while it is stopped. Press “Start”: it takes a couple of seconds.",
          gsiErrorTitle: "Could not connect to Dota",
          gsiErrorHint: "No access to the Dota folder. Point to the game folder manually.",
          noDotaTitle: "Dota not found",
          noDotaHint: "Dota 2 was not found in Steam. Point to the game folder and the app does the rest.",
          noGsiTitle: "Connect Dota",
          noGsiHint: "Press “Connect”: the app puts a small file into the Dota folder, and through it the game tells the coach what happens in your match.",
          notRunningTitle: "Dota is not running",
          notRunningHint: "Start Dota 2; the coach connects by itself. You can close this window.",
          connectedTitle: "Dota is connected, waiting for a match",
          noDataTitle: "Dota is running, no data from it yet",
          waitingHintConnected: "Advice starts as soon as a match with your hero begins.",
          waitingHintNoData: "If a match is already on, restart Dota: it connects to the coach only when it starts.",
          launchOptionTitle: "Dota is not sending game data",
          launchOptionHint: "Dota needs one launch option for that. In Steam: right-click Dota 2 → Properties → Launch options, paste -gamestateintegration (the button copies it), then restart the game.",
          inGameTitle: (hero, clock) => `In game: ${[hero, clock].filter(Boolean).join(", ")}`,
          inGameHint: "Advice appears over the game while Dota is the active window.",
          inGameOverlayOff: "Advice over the game is off: it shows only here.",
          demoTitle: (preset) => `Replay demo${preset ? `: ${preset}` : ""}`,
          demoHint: "The overlay shows advice from a recorded match.",
          fullscreenTitle: "Advice is hidden by fullscreen",
          fullscreenHint:
            "Dota runs in exclusive fullscreen, where no window can be drawn on top. In Dota: Settings → Video → Display mode → Borderless window. Or turn on the voice in Settings → Advice: it is heard in any mode."
        },
        actions: {
          start: "Start the coach",
          install: "Connect",
          chooseDota: "Choose Dota folder",
          fullscreenSeen: "I can see the advice",
          copyLaunchOption: "Copy option",
          copied: "Copied"
        },
        matchTitle: "Current match",
        coverageSafety: "The full advice is for 64 heroes (carries, mids, offlaners and supports); on this hero the coach gives survival advice, map timers and role tips.",
        coverageSupport: "Support advice: your own saves, fights and objectives, stacks, pulls, wards and save items. No farm or item advice: the gold goes to your cores.",
        statHero: "Hero",
        statClock: "Match time",
        statStage: "Phase",
        statData: "Link to the game",
        dataFresh: (s) => `${s} s ago`,
        dataFreshNow: "just now",
        matchEmptyTitle: "No match right now",
        matchEmptyHint: "Hero and time show up here when a match starts.",
        offlineTitle: "The coach is not running",
        offlineHint: "Start it to see your match here.",
        adviceTitle: "Recent advice",
        adviceWhy: "Why this advice?",
        adviceEmptyTitle: "No advice yet",
        adviceEmptyHint: "Advice shows up here as it appears over the game.",
        priority: { high: "urgent", urgent: "urgent", medium: "important", low: "tip", safe: "calm" },
        stages: { laning: "Lanes", "post-laning": "After the lanes", macro: "Mid and late game" },
        overlayTitle: "Advice card",
        overlayShow: "Show advice over the game",
        overlayReason: {
          off: "Off",
          positioning: "Shown so you can move it",
          demo: "Showing the replay demo",
          no_tracking: "Always visible: on this system the app cannot tell whether Dota is open",
          dota_not_running: "Appears in a match, over Dota",
          dota_not_focused: "Hidden while Dota is in the background",
          no_match: "Appears when a match starts",
          in_game: "On screen now"
        },
        overlayPosition: "Where on the screen",
        positionHint: "Away from the minimap and the hero panel",
        positionCustom: "Custom position, pick a preset to reset",
        posLeft: "Left",
        posRight: "Right",
        posBottom: "Bottom",
        overlaySize: "Card size",
        overlaySizeHint: "Larger on big and high-resolution screens",
        overlayTimers: "Timer strip",
        skillArrowsTitle: "Arrows over your abilities",
        skillArrowsCalibrate: "Fine-tune",
        skillArrowsHint: {
          on: "With a skill point to spend, an arrow points at the ability right on Dota's bar and finds the icons by itself. “Fine-tune” if it misses.",
          manual: "On, with your own frame. “Fine-tune” → “Automatic” goes back to finding the icons by itself.",
          off: "Off. The card still names the ability to level."
        },
        overlayTimersHint: "Always under the card: how long until the next runes, stacks, Roshan and Aegis for your role",
        overlayCompact: "Short advice",
        overlayCompactHint: "Only what to do, without the reason: less to read during a fight",
        hotkeysTitle: "Hotkeys",
        hotkeysGame: "In the game",
        hotkeysApp: "In this window",
        hotkeyTabs: "Home, Matches, Progress, Profile, Settings",
        hotkeyBack: "From a match review back to where you opened it",
        hotkeyHistory: "Back / forward through the pages you opened (the mouse's side buttons too)",
        hotkeyFind: "On Settings: find a setting",
        hotkeyPalette: "Find a tab, a match, a setting or an action",
        findAnything: "Find…",
        hotkeyZoom: "Interface size bigger / smaller, Ctrl+0 back to 100%",
        hotkeyNeighbour: "In a match review: the match above / below in the list (newer / older unless the list is sorted)",
        hotkeyHelp: "This list of keys, from any tab",
        hotkeyToggle: "Turn the advice card on or off",
        hotkeyRepeat: "Show (and say) the last advice again",
        hotkeyMute: "No advice for 5 minutes",
        hotkeyMove: "Unlock the card to drag it, press again to lock",
        hotkeyPlace: "The card on the left / on the right / at the bottom",
        sizeSmall: "Small",
        sizeNormal: "Normal",
        sizeLarge: "Large",
        frequencyTitle: "How often",
        frequencyCalm: "Less",
        frequencyNormal: "Normal",
        frequencyActive: "More",
        roleTitle: "Your role",
        roleAuto: "Auto",
        roleCarry: "Carry",
        roleMid: "Mid",
        roleOfflane: "Offlane",
        roleSupport: "Support",
        roleHint: {
          auto: "The coach works it out from your lane in the first minutes. Pick a role if it gets it wrong",
          carry: "Timers and tips for a carry",
          mid: "Runes and timers for a mid player",
          offlane: "Shrines, lotuses and timers for an offlaner",
          support: "Stacks, wards and runes for a support; farm advice is off"
        },
        roleNames: { carry: "carry", mid: "mid", offlane: "offlane", support: "support" },
        roleSource: {
          setting: "chosen in Settings",
          lane: "from your lane",
          history: "from your past games on this hero",
          hero: "usual for this hero"
        },
        roleNote: (role, source) => `Role: ${role}, ${source}.`,
        roleMismatch: (setting, seen) => `“Your role” is set to ${setting}, but you play as ${seen}: some tips miss.`,
        roleSetAuto: "Set to Auto",
        mapHintsTitle: "Map timers",
        mapHintsHint: "A reminder on the card 20 s before runes, shrines, Tormentor, stacks and wards — only the ones your role needs. Off also hides the timer strip",
        frequencyHint: {
          calm: "Twice the pause between tips; urgent advice is never delayed",
          normal: "Balanced pauses between tips",
          active: "Shorter pauses between tips; urgent advice as always"
        },
        voiceTitle: "Voice",
        voiceOff: "Off",
        voiceUrgent: "Urgent",
        voiceAll: "All",
        voiceTest: "Listen",
        voiceHint: {
          off: "Advice is only shown, not spoken",
          urgent: "Speaks urgent advice; heard even in exclusive fullscreen. Ctrl+Alt+R repeats",
          all: "Speaks every piece of advice; heard even in exclusive fullscreen. Ctrl+Alt+R repeats"
        },
        voiceNoVoice: "No English voice in the system: Windows Settings → Time & language → Speech",
        voiceEnglishFallback: (name) =>
          `No voice for the app language: advice is read in English (${name}). Add one in Windows Settings → Time & language → Speech`,
        voiceSettings: "Add a voice",
        voiceSample: "Back off: the enemy is missing from the map.",
        overlayMove: "Move by hand",
        moveHint: "Shows the card so you can drag it anywhere",
        moveActiveHint: "Drag the card, then press Done",
        moveStart: "Move",
        moveDone: "Done",
        recordsTitle: "Keep match recordings for a week",
        recordsHint: "Everything the game sent during each match and every advice shown, kept on this computer for 7 days. Save any match as a file and send it to the developer, the next day too. No nicknames, Steam IDs or chat.",
        recordsOff: "Off: matches are not recorded.",
        recordsEmpty: "On: the next match will be recorded.",
        recordsCount: (n) => `On: ${n} ${n === 1 ? "match" : "matches"} recorded this week.`,
        recordsSave: "Save file",
        recordsSaved: "Saved to Downloads.",
        recordsFailed: "Could not save the file.",
        recordsMinutes: (n) => `${n} min`,
        recordsAdvice: (n) => `${n} advice`,
        statsTitle: "Help improve the advice",
        statsHint: "Once a day the app sends anonymous counts: which advice was shown and which warnings came before a death. No heroes, matches, nickname or keys. Off by default.",
        statsPreview: "What is sent (today so far)",
        statsTerms: "Kept for a year.",
        statsOff: "Off: nothing is sent.",
        statsOn: "On: the first upload is tomorrow, with today's counts.",
        statsSent: (date) => `On. Last sent ${date}.`,
        statsPreviewLoading: "Collecting…",
        statsPreviewFailed: "The coach is not running: nothing to show.",
        serverDelete: "Delete my data on the server",
        serverDeleteConfirm: "Delete for sure? Press again",
        serverDeleted: "Deleted: problem reports, shared links and statistics of this computer are gone from the server.",
        serverDeleteFailed: (code) => `Could not delete (${code}): check the internet and try again.`,
        discordTitle: "Status in Discord",
        discordHint: "Your Discord friends see “Playing Juggernaut · with the Wardly coach” while Dota runs",
        discordStates: {
          idle: "It appears once Dota is running.",
          connecting: "Connecting to Discord…",
          no_discord: "Discord not found: open the Discord app on this computer (the browser version cannot show it).",
          connected: "Discord connected. The status appears once Dota is running.",
          shown: "Shown in Discord. Friends do not see it? Discord → Settings → Activity Privacy → “Share your detected activities with others”.",
          rejected: (error) => `Discord did not accept the status: ${error}`
        },
        settingsMore: "More settings",
        settingsMoreHint: "Match recordings, statistics, the OpenDota key, your week in Discord",
        settingsPageTitle: "Settings",
        settingsPageSub: "Everything already works. Change only what you want to.",
        settingsSearch: "Find a setting",
        settingsSearchEmpty: "Nothing found. Try another word, for example “voice”, “size” or “key”.",
        settingsSearchClear: "Show all settings",
        zoneNow: "Now",
        zoneNowHint: "The current match and the advice it got",
        zoneHistory: "Last matches",
        zoneHistoryHint: "Open one for its review",
        zoneWeek: "Your week",
        zoneWeekHint: "The last seven days against the seven before",
        zoneAllMatches: "All matches",
        zoneGame: "In the game",
        zoneGameHint: "What you see and hear during a match",
        zoneData: "After the match",
        zoneDataHint: "A review of every match in plain words, written by the AI coach",
        zoneApp: "App",
        zoneAppHint: "Language, start with Windows, updates",
        weeklyTitle: "The week in Discord",
        weeklyHint:
          "Every Monday the week's matches, results and average score are posted to a channel of your Discord server. You need the channel's webhook link: in Discord open the channel settings → Integrations → Webhooks → New webhook → Copy webhook URL, and paste it here.",
        weeklyInputLabel: "Webhook link",
        weeklyConnect: "Connect",
        weeklySendNow: "Send now",
        weeklyDisconnect: "Disconnect",
        weeklySending: "Sending…",
        weeklyConnected: (hint) => `Connected (${hint}). The week goes to Discord every Monday.`,
        weeklySent: (date) => `Last post: ${date}.`,
        weeklyEmpty: (date) => `${date}: no matches in that week, nothing was posted.`,
        weeklyNoMatchesNow: "No matches in the last seven days: nothing to post yet.",
        weeklyErrors: {
          bad_url: "This is not a Discord webhook link: it starts with https://discord.com/api/webhooks/.",
          webhook_gone: "The webhook was deleted in Discord: create a new one and connect it again.",
          rate_limited: "Discord asks to wait: try again in a minute.",
          offline: "No connection to Discord: check the internet.",
          backend_down: "The coach is not running yet: try again in a moment.",
          busy: "Already sending…",
          fallback: "Could not post: try again later."
        },
        autostart: "Start with Windows",
        autostartOn: "Wardly opens by itself when the computer starts and waits quietly next to the clock, so you never forget it before a game.",
        autostartOff: "Off: open Wardly yourself before you play. Turn it on and Wardly will open with the computer and wait quietly next to the clock.",
        autostartUnavailable: "Available in the installed app",
        updates: "Updates",
        updateCheck: "Check",
        updateInstall: "Restart and update",
        updateHint: {
          disabled: (v) => `Version ${v} · updates work in the installed app`,
          idle: (v) => `Version ${v} · updates install by themselves`,
          checking: (v) => `Version ${v} · checking…`,
          "up-to-date": (v) => `Version ${v} · up to date`,
          downloading: (v, next, pct) => `Downloading ${next}… ${pct}%`,
          ready: (v, next) => `Version ${next} is ready. It installs by itself once Dota is closed.`,
          blocked: (v, next) => `Version ${next} is ready. It installs after you close Dota.`,
          error: (v) => `Version ${v} · could not check for updates`
        },
        whatsNewTitle: (version) => `What's new in ${version}`,
        whatsNewAlso: (version) => `Also in ${version}`,
        whatsNewOk: "Got it",
        inviteTitle: "Like Wardly?",
        inviteText: "Send the link to a friend: the app is free, and playing together it is easier to follow the advice.",
        inviteCopy: "Copy the link",
        inviteLater: "Not now",
        inviteCopied: "Link copied",
        tour: {
          next: "Next",
          back: "Back",
          skip: "Skip",
          done: "Start playing",
          count: (i, n) => `${i} of ${n}`,
          steps: {
            welcome: {
              title: "Hi! This is Wardly",
              text: "The coach watches your match with you: short advice over the game and out loud, and a review with what to fix after it. A two-minute look around: what the advice looks like, where everything is and what to set up."
            },
            card: {
              title: "What advice looks like",
              text: "A card over the game. The big line is what to do now, the line below is why. “Urgent” with a red dot means right now: low HP, a death coming. The rest are tips you can do at the next good moment. The card shows only during a match, while Dota is in front."
            },
            mapline: {
              title: "Map timers and calls",
              text: "Runes, stacks, Roshan, the Tormentor, an enemy missing from your lane, an unspent skill point: these come as a “Map” card with the time left. Under the card a strip counts down the next timers."
            },
            plan: {
              title: "Plan, death screen and score",
              text: "Before the horn the card shows a plan: last hits to reach by 10:00, the key item and your focus. While you are dead it says why you died and what to buy, and on the score screen it gives the match score and one thing to fix."
            },
            status: {
              title: "Status line",
              text: "What is going on right now: is Dota found, is it sending data, is a match on. When something needs you, the button on the right does it."
            },
            setup: {
              title: "Getting started",
              text: "What is set up and what is left. Most steps do themselves. If Dota asks for it, add -gamestateintegration to its launch options (the button copies it). The first match with the app finishes the list."
            },
            match: {
              title: "Current match",
              text: "Your hero, the match time and the advice the coach gave. Under each advice, “Why this advice?” says what the coach saw. During a match the advice appears over the game: you do not need to look here."
            },
            matches: {
              title: "Matches",
              text: "Every match with a review: a score by area, where you died, the item timings and what to fix first. The review of a match is ready a minute or two after it ends."
            },
            progress: {
              title: "Progress",
              text: "How you play over the last games: the trends, the mistakes that repeat, your lanes and heroes. Pick one problem as your focus: every next match shows whether you fixed it."
            },
            profile: {
              title: "Profile and friends",
              text: "Your rating graph, level and achievements for matches with the app. Sparks from games buy frames, banners and titles. Share your friend code to see each other on a leaderboard."
            },
            settings: {
              title: "Card over the game",
              text: "Where the advice card sits over the game and how big it is. You can drag it by hand."
            },
            voice: {
              title: "Advice and voice",
              text: "How often the coach speaks, your role and the voice. Leave the role on “Auto”: the coach works it out from your lane. The voice reads the advice out loud and also works in exclusive fullscreen, where no card can be drawn."
            },
            ai: {
              title: "AI coach (optional)",
              text: "With a free Google AI Studio key the review gets a written breakdown and you can ask the coach about any match. Everything else works without it."
            },
            help: {
              title: "Help",
              text: "This tour opens again from here. If something does not work, “Report a problem” sends the developer a report with what the game sent (no keys or passwords)."
            },
            done: {
              title: "All set",
              text: "Start Dota and play a match: the first advice appears by itself, and the review is ready a minute or two after the game. Good luck!"
            }
          }
        },
        summaryTitle: "Summary",
        sessionTitle: "Your evening",
        sessionHide: "Hide",
        tourTitle: "How to use Wardly",
        tourHint: "A short tour of the app, one minute",
        tourStart: "Show",
        whatsNew: whatsNew.texts("en"),
        setupTitle: "Getting started",
        setupPreviewTitle: "What you will see in game",
        setupPreviewText: "Advice appears over the game when it matters, and after the match the coach writes a review with a score and one thing to fix.",
        setupHide: "Hide",
        setupCount: (done, total) => `${done} of ${total}`,
        setup: {
          service: ["The coach is running", "Starts with the app. If it stopped, restart the app."],
          dota: ["Dota 2 found", "Not in your Steam libraries: point to the game folder."],
          gsi: ["Connected to Dota", "A small file in the Dota folder: through it the game tells the coach what happens in your match."],
          launch: ["Dota shares the match", "Dota needs a launch option for it. In Steam: right-click Dota 2 → Properties → Launch options, paste -gamestateintegration."],
          data: ["Dota has talked to the coach", "Start Dota 2 (or restart it if it was running) and open any match, bots are fine."],
          account: ["Steam account linked", "Linked by itself in the first match, or enter it on the Matches tab."],
          ai: ["AI coach (optional)", "With a free Google key the AI writes a review of every match in plain words."]
        },
        setupActions: { dota: "Choose folder", gsi: "Connect", launch: "Copy", account: "Link", ai: "Set up" },
        reportTitle: "Report a problem",
        reportHint: "Something does not work? Press “Report” and describe it in a few words: the developer gets the app's log. Keys and passwords are cut out.",
        reportSave: "Save as a file instead",
        autoBackupTitle: "Automatic copies",
        autoBackupHint: "Once a week and before each update Wardly keeps a copy of your history on this computer: the last 4, up to 200 MB. Restoring only adds what is missing and never removes anything.",
        autoBackupNow: "Make a copy now",
        autoBackupMaking: "Making a copy…",
        autoBackupMade: "Copy saved.",
        autoBackupNone: "No copies yet: the first one appears after your first reviewed match.",
        autoBackupOff: "Automatic copies are off. You can still make one by hand.",
        autoBackupFailed: "Could not make the copy. Try again later.",
        autoBackupKinds: { weekly: "weekly", update: "before an update", manual: "by hand" },
        autoBackupItem: (date, kind, matches, size) => `${date} · ${kind} · ${matches == null ? "?" : matches} matches · ${size}`,
        autoBackupCheck: "Check",
        autoBackupChecking: "Comparing with your history…",
        autoBackupPreview: (matches, notes) => (matches || notes ? `Restoring adds ${matches} matches${notes ? ` and fills ${notes} missing fields` : ""}. Nothing is removed.` : "Nothing to add: your history already has everything in this copy."),
        autoBackupRestore: "Restore",
        autoBackupRestored: (matches) => `Restored: ${matches} matches added.`,
        autoBackupBroken: "This copy is damaged and cannot be read.",
        backupTitle: "Spare copy in a file",
        backupHint: "Saves all your matches and reviews into one file, for example before reinstalling Windows. Open it later in Wardly on any computer. Keys are not saved.",
        backupExport: "Save to file",
        backupImport: "Open a file",
        backupSaved: (count, file) => `Saved ${count} matches: ${file}`,
        backupLoaded: (added, linked) => `Loaded: ${added} new matches${linked ? ", account linked" : ""}. Nothing was overwritten.`,
        backupNotBackup: "This file is not a Wardly history backup, or its data is damaged. Nothing from the file was saved.",
        backupNewer: "The backup was made by a newer version: update the app first.",
        backupRestoreFailed: "Could not restore the history. Nothing from the file was saved; check the disk and try again.",
        backupFailed: "Could not do it: the coach is not running or the disk is not available.",
        transferTitle: "Move to another computer",
        zoneMyData: "Your matches",
        zoneMyDataHint: "So your history is not lost when you change computers",
        zoneHelp: "Help",
        zoneHelpHint: "How to use the app, and what to do if something breaks",
        transferIntro: "Installed Wardly on a new computer? Move your matches and reviews there, it takes a minute.",
        transferStep1: "Here, press “Get a code”.",
        transferStep2: "On the new computer: Wardly → Settings → Move to another computer → “I have a code”, and type it in.",
        transferHave: "I have a code",
        transferHint: "The code works for 15 minutes. Your matches travel encrypted; keys are not moved.",
        transferSend: "Get a code",
        transferReceive: "Load",
        transferInputLabel: "Code from the other computer",
        transferSending: "Encrypting and sending…",
        transferReady: (matches, time) => `The code works until ${time}. Type it in on the new computer (matches: ${matches}).`,
        transferReceiving: "Downloading and decrypting…",
        transferErrors: {
          bad_code: "Check the code: three groups of four letters and digits, as shown on the other computer.",
          not_found: "No history under this code: it has expired (15 minutes) or was already loaded. Get a new code.",
          too_big: "The history is too big to send by code: save it to a file instead.",
          rate_limited: "Too many tries for now: wait an hour or move it with a file.",
          disabled: "Moving by code is switched off right now: use a file.",
          not_backup: "The code opened something that is not a Wardly history.",
          offline: "No connection to the server: check the internet.",
          fallback: "Could not do it: try again or use a file."
        },
        reportSaving: "Collecting…",
        reportSaved: (name) => `Saved: ${name}. Send this file to the developer.`,
        reportFailed: "Could not save the file",
        reportSend: "Report",
        reportNoteLabel: "What happened? (optional)",
        reportNotePlaceholder: "For example: no advice shows in a match",
        reportPreview: "What will be sent",
        reportPreviewLoading: "Collecting the report…",
        reportTerms: "Keys are cut out. The report is kept for 180 days.",
        reportPrivacy: "Privacy",
        reportSendNow: "Send",
        reportCancel: "Cancel",
        reportSending: "Sending…",
        reportSentId: (id) => `Sent. Report number: ${id}. Mention it if you write to the developer.`,
        reportQueued: "No internet right now. The report will be sent by itself later.",
        reportQueuedCount: (count) => `Waiting to be sent: ${count}`,
        reportLast: (id) => `Last report: ${id}`,
        reportRefused: (name) =>
          name ? `The server did not accept the report. Saved a file instead: ${name}.` : "The server did not accept the report.",
        devTitle: "For developers",
        devHint: "Technical tools: the coach process, the link to the game, logs. You do not need them to play",
        factBackend: "Service",
        factDota: "Dota",
        factOverlay: "Overlay",
        factDemo: "Demo",
        factRecording: "Recording",
        factGsiConfig: "GSI config",
        factMode: "Mode",
        groupBackend: "Service",
        startBackend: "Start",
        restartBackend: "Restart",
        stopBackend: "Stop",
        showOverlay: "Show overlay",
        hideOverlay: "Hide overlay",
        hotkeys: "Ctrl+Alt+O on/off · Ctrl+Alt+L move · Ctrl+Alt+M mute 5 min · Ctrl+Alt+R repeat advice · Ctrl+Alt+1/2/3 left/right/bottom · Ctrl+Alt+D debug line",
        groupGsi: "GSI config",
        gsiPathPlaceholder: "Custom gamestate_integration folder (optional)",
        chooseFolder: "Choose",
        checkGsi: "Check",
        installGsi: "Install",
        gsiPath: (p, e) => `Config: ${p}${e ? `\nEndpoint: ${e}` : ""}`,
        gsiPathMissing: "Config not found. Choose the gamestate_integration folder and install.",
        gsiEndpoint: (e) => (e ? `Endpoint: ${e}` : "Endpoint: waiting for the service port…"),
        groupLive: "Live GSI",
        kvConnection: "Connection",
        kvLast: "Last data",
        kvHero: "Hero",
        kvTime: "Game time",
        kvStage: "Stage",
        liveConnected: "connected",
        liveWaiting: "waiting / stale",
        liveUnavailable: "service unavailable",
        liveAdvice: (a) => `Current advice: ${a}`,
        liveAdviceNone: "Current advice: none yet",
        liveAdviceLast: (t) => `Current advice: last shown at ${t}`,
        liveMissing: (m) => `Missing important fields: ${m}`,
        none: "none",
        checkLive: "Check",
        startRecording: "Record",
        stopRecording: "Stop recording",
        openRecords: "Recordings",
        groupDemo: "Replay demo",
        demoHint: "Plays recorded match states into the service; the overlay shows without Dota.",
        demoBusy: "A demo is already running. Stop it first.",
        runDemo: "Run demo",
        presetPl: "Phantom Lancer 20–30",
        presetJugg: "Juggernaut 10–20",
        deepReview: "Deep Review",
        stopDemo: "Stop",
        openResults: "Results",
        groupLogs: "Logs",
        groupOps: "Operations health",
        opsHint: "Background queues, saving the finished match, the live GSI path and how fresh the data are. Counts and times only.",
        opsRefresh: "Refresh",
        opsAllGood: "Nothing looks wrong.",
        opsUnavailable: "The service did not answer.",
        opsJobs: "History jobs",
        opsAi: "AI coach jobs",
        opsMatch: "Match saving",
        opsGsi: "Live GSI path",
        opsData: "Data",
        opsQueueIdle: (done) => `idle · ${done} done`,
        opsQueueIdleFailed: (done, failed, at) => `idle · ${done} done, ${failed} failed${at ? ` (last ${at})` : ""}`,
        opsQueueRunning: (kind, seconds, queued) => `running ${kind} for ${seconds} s${queued ? ` · ${queued} waiting` : ""}`,
        opsQueueWaiting: (queued, seconds) => `${queued} waiting · the oldest for ${seconds} s`,
        opsQueueLater: (queued, seconds) => `${queued} scheduled · next in ${seconds} s`,
        opsMatchPending: (n) => `${n} finished ${n === 1 ? "match is" : "matches are"} waiting to be saved`,
        opsMatchSaved: (at) => `last match saved at ${at}`,
        opsMatchNone: "no match finished in this session",
        opsGsiNone: "no packets in this session",
        opsGsiTimes: (count, p50, p95, failed) => `${count} packets · p50 ${p50 ?? "—"} ms · p95 ${p95 ?? "—"} ms${failed ? ` · ${failed} saves failed` : ""}`,
        opsDataLine: (state, at, builds, age) => {
          const sync = { done: "matches synced", error: "match sync failed", running: "syncing matches", queued: "syncing matches" }[state] || "matches not synced";
          return `${sync}${at ? ` ${at}` : ""} · builds ${builds ? `from ${builds}${age != null ? ` (${age} d)` : ""}` : "missing"}`;
        },
        opsWarn_jobs_waiting: "History jobs wait in the queue for over 2 minutes.",
        opsWarn_jobs_running_long: "A history job has run for over 5 minutes.",
        opsWarn_jobs_no_worker: "History jobs are queued but no worker runs them.",
        opsWarn_ai_jobs_waiting: "AI coach jobs wait in the queue for over 2 minutes.",
        opsWarn_ai_jobs_running_long: "An AI coach job has run for over 5 minutes.",
        opsWarn_ai_jobs_no_worker: "AI coach jobs are queued but no worker runs them.",
        opsWarn_match_not_saved: "A finished match could not be saved yet; it is kept and retried.",
        opsWarn_recovery_write_failed: "The match recovery file could not be written.",
        opsWarn_gsi_persistence_failed: "Saving live GSI data failed at least once.",
        opsWarn_gsi_slow: "The live GSI path is slow (p95 over 250 ms).",
        opsWarn_sync_failed: "The last match sync failed.",
        opsWarn_builds_stale: "The bundled item builds are over three weeks old.",
        logClean: "Clean",
        logVerbose: "Verbose",
        copyLogs: "Copy",
        clearLogs: "Clear",
        openLogs: "Logs folder",
        dotaStates: { not_found: "not found", waiting: "waiting for a match", in_game: "in game" },
        gsiConfigStates: { installed: "installed", "not found": "not found", error: "error", unknown: "unknown" },
        modes: { "Live GSI": "Live GSI", "Replay Demo": "Replay demo" },
        on: "on",
        off: "off",
        shown: "on screen",
        hidden: "hidden",
        running: "running",
        stopped: "stopped"
      },
      uk: {
        tabHome: "Головна",
        tabMatches: "Матчі",
        tabProgress: "Прогрес",
        tabProfile: "Профіль",
        tabSettings: "Налаштування",
        adviceSettingsTitle: "Поради",
        languageTitle: "Мова",
        languageHint: "Поради, розбори й увесь застосунок",
        languageAuto: "Як у системі",
        uiScaleTitle: "Розмір інтерфейсу",
        uiScaleHint: "Більші текст і кнопки — для великого екрана чи високої роздільної здатності. Працюють і Ctrl + плюс, Ctrl + мінус.",
        uiScaleToast: (size) => `Розмір інтерфейсу: ${size}`,
        dataTitle: "Історія матчів",
        odTitle: "Швидке завантаження історії",
        odPlaceholder: "Ключ OpenDota",
        odSave: "Зберегти",
        odGet: "Отримати ключ на opendota.com",
        odClear: "Видалити ключ",
        odHintOff: "Історію ваших матчів застосунок бере з OpenDota — безкоштовного сайту статистики Доти. Без ключа все працює, просто повільніше. Безкоштовний ключ з opendota.com пришвидшить завантаження; він зберігається лише на цьому комп'ютері.",
        odHintOn: (hint) => `Ключ ${hint} збережено: матчі завантажуються швидше.`,
        odHintEnv: "Ключ уже задано у файлі налаштувань застосунку.",
        odBad: "Це не схоже на ключ OpenDota.",
        appTitle: "Основне",
        service: "Тренер",
        serviceStates: { running: "працює", starting: "запускається…", stopping: "зупиняється…", stopped: "зупинено" },
        status: {
          loadingTitle: "Запускаємо тренера…",
          loadingHint: "Зазвичай це кілька секунд.",
          backendDownTitle: "Тренера зупинено",
          backendDownHint: "Поки його зупинено, підказок не буде. Натисніть «Запустити» — це кілька секунд.",
          gsiErrorTitle: "Не вдалося підключитися до Доти",
          gsiErrorHint: "Немає доступу до теки Доти. Вкажіть теку гри вручну.",
          noDotaTitle: "Доту не знайдено",
          noDotaHint: "Не знайшли Dota 2 у Steam. Вкажіть теку гри — решту застосунок зробить сам.",
          noGsiTitle: "Підключіть Доту",
          noGsiHint: "Натисніть «Підключити»: застосунок покладе в теку Доти маленький файл, через який гра повідомляє тренерові, що відбувається в матчі.",
          notRunningTitle: "Дота не запущена",
          notRunningHint: "Запустіть Dota 2 — тренер підключиться сам. Це вікно можна закрити.",
          connectedTitle: "Зв'язок із Дотою є, чекаємо на матч",
          noDataTitle: "Дота запущена, даних від неї поки немає",
          waitingHintConnected: "Підказки почнуться, щойно стартує матч із вашим героєм.",
          waitingHintNoData: "Якщо матч уже йде, перезапустіть Доту: до тренера вона підключається лише під час запуску.",
          launchOptionTitle: "Дота не передає дані гри",
          launchOptionHint: "Для цього Доті потрібен параметр запуску. У Steam: правою кнопкою на Dota 2 → Властивості → Параметри запуску, вставте -gamestateintegration (кнопка його скопіює) і перезапустіть гру.",
          inGameTitle: (hero, clock) => `У грі: ${[hero, clock].filter(Boolean).join(", ")}`,
          inGameHint: "Підказки з'являються поверх гри, поки вікно Доти активне.",
          inGameOverlayOff: "Підказки поверх гри вимкнено — їх видно лише тут.",
          demoTitle: (preset) => `Демо-повтор${preset ? `: ${preset}` : ""}`,
          demoHint: "Оверлей показує підказки із записаного матчу.",
          fullscreenTitle: "Підказок не видно через повноекранний режим",
          fullscreenHint:
            "Дота запущена в ексклюзивному повноекранному режимі — поверх нього вікна не малюються. У Доті: Налаштування → Відео → режим екрана «Вікно без рамки» (Borderless window). Або ввімкніть голос у «Налаштування → Поради» — його чути в будь-якому режимі."
        },
        actions: {
          start: "Запустити тренера",
          install: "Підключити",
          chooseDota: "Вказати теку Доти",
          fullscreenSeen: "Підказки видно",
          copyLaunchOption: "Скопіювати параметр",
          copied: "Скопійовано"
        },
        matchTitle: "Поточний матч",
        coverageSafety: "Повні підказки — для 64 героїв (керрі, мід, хардлайн, саппорти); на цьому герої тренер підказує щодо виживання, таймерів мапи й ролі.",
        coverageSupport: "Поради саппорта: власні порятунки, бійки й цілі, стаки, пули, варди й рятівні предмети. Без порад щодо фарму й предметів — золото дістається корам.",
        statHero: "Герой",
        statClock: "Час матчу",
        statStage: "Етап",
        statData: "Зв'язок із грою",
        dataFresh: (s) => `${s} с тому`,
        dataFreshNow: "щойно",
        matchEmptyTitle: "Матч не йде",
        matchEmptyHint: "Герой і час з'являться тут, коли почнеться матч.",
        offlineTitle: "Тренера не запущено",
        offlineHint: "Запустіть його, щоб бачити тут свій матч.",
        adviceTitle: "Останні підказки",
        adviceWhy: "Чому ця порада?",
        adviceEmptyTitle: "Підказок поки немає",
        adviceEmptyHint: "Тут з'являться підказки, які показувалися поверх гри.",
        priority: { high: "терміново", urgent: "терміново", medium: "важливо", low: "порада", safe: "спокійно" },
        stages: { laning: "Лінії", "post-laning": "Після ліній", macro: "Середина й кінець гри" },
        overlayTitle: "Картка з підказками",
        overlayShow: "Показувати підказки поверх гри",
        overlayReason: {
          off: "Вимкнено",
          positioning: "Показано, щоб його можна було перемістити",
          demo: "Показує демо-повтор",
          no_tracking: "Завжди видно: у цій системі застосунок не бачить, чи відкрита Дота",
          dota_not_running: "З'явиться в матчі поверх Доти",
          dota_not_focused: "Приховано, поки Дота у фоні",
          no_match: "З'явиться, коли почнеться матч",
          in_game: "Зараз на екрані"
        },
        overlayPosition: "Де на екрані",
        positionHint: "Осторонь мінімапи й панелі героя",
        positionCustom: "Власне положення — оберіть варіант, щоб повернути",
        posLeft: "Ліворуч",
        posRight: "Праворуч",
        posBottom: "Знизу",
        overlaySize: "Розмір картки",
        overlaySizeHint: "Більша — для великих екранів і високої роздільної здатності",
        overlayTimers: "Смуга таймерів",
        skillArrowsTitle: "Стрілки над навичками",
        skillArrowsCalibrate: "Підправити",
        skillArrowsHint: {
          on: "Коли є очко навички, стрілка вказує на здібність просто на панелі Доти й сама знаходить іконки. «Підправити» — якщо промахується.",
          manual: "Увімкнено, зі своєю рамкою. «Підправити» → «Автоматично» поверне пошук іконок самою стрілкою.",
          off: "Вимкнено. Картка все одно називає здібність."
        },
        overlayTimersHint: "Завжди під карткою: скільки лишилося до найближчих рун, стаків, Рошана й Аегіса для вашої ролі",
        overlayCompact: "Короткі підказки",
        overlayCompactHint: "Лише що робити, без пояснення: менше читати під час бійки",
        hotkeysTitle: "Гарячі клавіші",
        hotkeysGame: "У грі",
        hotkeysApp: "У цьому вікні",
        hotkeyTabs: "Головна, Матчі, Прогрес, Профіль, Налаштування",
        hotkeyBack: "З розбору матчу назад туди, звідки його відкрили",
        hotkeyHistory: "Назад / вперед відкритими сторінками (і бічні кнопки миші)",
        hotkeyFind: "У «Налаштуваннях»: знайти налаштування",
        hotkeyPalette: "Знайти вкладку, матч, налаштування або дію",
        findAnything: "Знайти…",
        hotkeyZoom: "Інтерфейс більший / менший, Ctrl+0 — назад 100 %",
        hotkeyNeighbour: "У розборі матчу: матч вище / нижче в списку (новіший / старіший, якщо список не відсортовано)",
        hotkeyHelp: "Цей список клавіш, з будь-якої вкладки",
        hotkeyToggle: "Увімкнути чи вимкнути картку з підказками",
        hotkeyRepeat: "Показати (і озвучити) останню пораду ще раз",
        hotkeyMute: "Без підказок на 5 хвилин",
        hotkeyMove: "Відкріпити картку, щоб перетягнути; ще раз — закріпити",
        hotkeyPlace: "Картка ліворуч / праворуч / знизу",
        sizeSmall: "Малий",
        sizeNormal: "Звичайний",
        sizeLarge: "Великий",
        frequencyTitle: "Частота порад",
        frequencyCalm: "Рідше",
        frequencyNormal: "Як зазвичай",
        frequencyActive: "Частіше",
        roleTitle: "Ваша роль",
        roleAuto: "Авто",
        roleCarry: "Керрі",
        roleMid: "Мід",
        roleOfflane: "Хардлайн",
        roleSupport: "Саппорт",
        roleHint: {
          auto: "Тренер сам зрозуміє за вашою лінією в перші хвилини. Оберіть роль, якщо він помиляється",
          carry: "Таймери й підказки для керрі",
          mid: "Руни й таймери для мідера",
          offlane: "Святилища, лотоси й таймери для хардлайнера",
          support: "Стаки, варди й руни для саппорта; поради щодо фарму вимкнено"
        },
        roleNames: { carry: "керрі", mid: "мід", offlane: "хардлайн", support: "саппорт" },
        roleSource: {
          setting: "обрано в налаштуваннях",
          lane: "за лінією",
          history: "за вашими минулими іграми на герої",
          hero: "звичайна для героя"
        },
        roleNote: (role, source) => `Роль: ${role}, ${source}.`,
        roleMismatch: (setting, seen) => `У «Ваша роль» стоїть ${setting}, а граєте ви як ${seen} — частина підказок не до речі.`,
        roleSetAuto: "Поставити «Авто»",
        mapHintsTitle: "Таймери мапи",
        mapHintsHint: "Нагадування на картці за 20 секунд до рун, святилищ, Торментора, стаків і вардів — лише потрібних вашій ролі. Вимкніть — зникне й смуга таймерів",
        frequencyHint: {
          calm: "Удвічі більша пауза між порадами; термінові не затримуються",
          normal: "Звичайні паузи між порадами",
          active: "Коротші паузи між порадами; термінові як завжди"
        },
        voiceTitle: "Голос",
        voiceOff: "Вимк",
        voiceUrgent: "Термінові",
        voiceAll: "Усі",
        voiceTest: "Прослухати",
        voiceHint: {
          off: "Поради лише на екрані, без озвучення",
          urgent: "Озвучує термінові поради; чути навіть у повноекранному режимі. Ctrl+Alt+R — повторити",
          all: "Озвучує всі поради; чути навіть у повноекранному режимі. Ctrl+Alt+R — повторити"
        },
        voiceNoVoice: "У Windows немає українського голосу: Параметри → Час і мова → Мовлення → Додати голоси",
        voiceEnglishFallback: (name) =>
          `Українського голосу в Windows немає, тому поради читаються англійською (${name}). Щоб чути українською, додайте голос: Параметри → Час і мова → Мовлення → Додати голоси → Українська`,
        voiceSettings: "Додати голос",
        voiceSample: "Відходьте: суперника не видно на мапі.",
        overlayMove: "Перемістити вручну",
        moveHint: "Покаже картку, щоб її можна було перетягнути",
        moveActiveHint: "Перетягніть картку й натисніть «Готово»",
        moveStart: "Перемістити",
        moveDone: "Готово",
        recordsTitle: "Зберігати записи матчів тиждень",
        recordsHint: "Усе, що гра надсилала за матч, і всі показані поради зберігаються на цьому комп'ютері 7 днів. Будь-який матч можна зберегти файлом і надіслати розробникові — хоч наступного дня. Без ніків, Steam ID і чату.",
        recordsOff: "Вимкнено: матчі не записуються.",
        recordsEmpty: "Увімкнено: наступний матч буде записано.",
        recordsCount: (n) => `Увімкнено: записано матчів за тиждень — ${n}.`,
        recordsSave: "Зберегти файл",
        recordsSaved: "Збережено в «Завантаження».",
        recordsFailed: "Не вдалося зберегти файл.",
        recordsMinutes: (n) => `${n} хв`,
        recordsAdvice: (n) => `порад: ${n}`,
        statsTitle: "Допомогти покращити підказки",
        statsHint: "Раз на день застосунок надсилає анонімні лічильники: які підказки показувалися й після яких попереджень була смерть. Без героїв, матчів, ніка й ключів. Типово вимкнено.",
        statsPreview: "Що надсилається (за сьогодні)",
        statsTerms: "Зберігається рік.",
        statsOff: "Вимкнено: нічого не надсилається.",
        statsOn: "Увімкнено: перше надсилання — завтра, з лічильниками за сьогодні.",
        statsSent: (date) => `Увімкнено. Останнє надсилання — ${date}.`,
        statsPreviewLoading: "Збираємо…",
        statsPreviewFailed: "Тренера не запущено, тож показати нічого.",
        serverDelete: "Видалити мої дані на сервері",
        serverDeleteConfirm: "Точно видалити? Натисніть ще раз",
        serverDeleted: "Видалено: звіти про проблеми, посилання «Поділитися» й статистику цього комп'ютера стерто із сервера.",
        serverDeleteFailed: (code) => `Не вдалося видалити (${code}): перевірте інтернет і спробуйте ще раз.`,
        discordTitle: "Статус у Discord",
        discordHint: "Друзі в Discord бачать «Матч на Juggernaut · з тренером Wardly», поки запущена Дота",
        discordStates: {
          idle: "З'явиться, коли запущена Дота.",
          connecting: "Підключаюся до Discord…",
          no_discord: "Discord не знайдено: відкрийте застосунок Discord на цьому комп'ютері (у браузері статус не працює).",
          connected: "Discord підключено. Статус з'явиться, коли запущена Дота.",
          shown: "Статус показано в Discord. Друзі не бачать? Discord → Налаштування → Конфіденційність активності → «Ділитися своєю активністю».",
          rejected: (error) => `Discord не прийняв статус: ${error}`
        },
        settingsMore: "Ще налаштування",
        settingsMoreHint: "Записи матчів, статистика, ключ OpenDota, тиждень у Discord",
        settingsPageTitle: "Налаштування",
        settingsPageSub: "Усе вже працює. Змінюйте лише те, що хочеться.",
        settingsSearch: "Знайти налаштування",
        settingsSearchEmpty: "Нічого не знайшлося. Спробуйте інше слово, наприклад «голос», «розмір» або «ключ».",
        settingsSearchClear: "Показати всі налаштування",
        zoneNow: "Зараз",
        zoneNowHint: "Поточний матч і підказки в ньому",
        zoneHistory: "Останні матчі",
        zoneHistoryHint: "Відкрийте матч, щоб побачити розбір",
        zoneWeek: "Ваш тиждень",
        zoneWeekHint: "Останні сім днів проти семи до них",
        zoneAllMatches: "Усі матчі",
        zoneGame: "У грі",
        zoneGameHint: "Що ви бачите й чуєте під час матчу",
        zoneData: "Після матчу",
        zoneDataHint: "Розбір кожного матчу простими словами від ШІ-тренера",
        zoneApp: "Застосунок",
        zoneAppHint: "Мова, автозапуск, оновлення",
        weeklyTitle: "Тиждень у Discord",
        weeklyHint:
          "Щопонеділка матчі, результати й середня оцінка за тиждень приходять у канал вашого сервера Discord. Для цього потрібне посилання каналу (вебхук): у Discord відкрийте налаштування каналу → Інтеграції → Вебхуки → Новий вебхук → Копіювати URL вебхука й вставте його сюди.",
        weeklyInputLabel: "Посилання вебхука",
        weeklyConnect: "Підключити",
        weeklySendNow: "Надіслати зараз",
        weeklyDisconnect: "Від'єднати",
        weeklySending: "Надсилаю…",
        weeklyConnected: (hint) => `Підключено (${hint}). Тиждень приходить у Discord щопонеділка.`,
        weeklySent: (date) => `Останнє надсилання: ${date}.`,
        weeklyEmpty: (date) => `${date}: за той тиждень матчів не було, нічого не надіслано.`,
        weeklyNoMatchesNow: "За останні сім днів матчів немає: надсилати поки нічого.",
        weeklyErrors: {
          bad_url: "Це не посилання вебхука Discord: воно починається з https://discord.com/api/webhooks/.",
          webhook_gone: "Вебхук видалено в Discord: створіть новий і підключіть заново.",
          rate_limited: "Discord просить зачекати: спробуйте за хвилину.",
          offline: "Немає зв'язку з Discord: перевірте інтернет.",
          backend_down: "Тренера ще не запущено: спробуйте за хвилину.",
          busy: "Уже надсилаю…",
          fallback: "Не вдалося надіслати: спробуйте пізніше."
        },
        autostart: "Автозапуск із Windows",
        autostartOn: "Wardly сам відкриється під час увімкнення комп'ютера й тихо чекатиме біля годинника. Так ви не забудете запустити його перед грою.",
        autostartOff: "Зараз вимкнено: Wardly треба відкривати самому перед грою. Увімкніть — і він сам запускатиметься з комп'ютером і тихо чекатиме біля годинника.",
        autostartUnavailable: "Доступно у встановленому застосунку",
        updates: "Оновлення",
        updateCheck: "Перевірити",
        updateInstall: "Перезапустити й оновити",
        updateHint: {
          disabled: (v) => `Версія ${v} · оновлення працюють у встановленому застосунку`,
          idle: (v) => `Версія ${v} · оновлюється сама`,
          checking: (v) => `Версія ${v} · перевіряємо…`,
          "up-to-date": (v) => `Версія ${v} · остання`,
          downloading: (v, next, pct) => `Завантажується ${next}… ${pct}%`,
          ready: (v, next) => `Версію ${next} завантажено. Встановиться сама, коли Дота буде закрита.`,
          blocked: (v, next) => `Версію ${next} завантажено. Встановиться після виходу з Доти.`,
          error: (v) => `Версія ${v} · не вдалося перевірити оновлення`
        },
        whatsNewTitle: (version) => `Що нового в ${version}`,
        whatsNewAlso: (version) => `Також у ${version}`,
        whatsNewOk: "Зрозуміло",
        inviteTitle: "Подобається Wardly?",
        inviteText: "Надішліть посилання другові: застосунок безкоштовний, а коли граєте разом, підказок легше дотримуватися.",
        inviteCopy: "Скопіювати посилання",
        inviteLater: "Не зараз",
        inviteCopied: "Посилання скопійовано",
        tour: {
          next: "Далі",
          back: "Назад",
          skip: "Пропустити",
          done: "Грати",
          count: (i, n) => `${i} з ${n}`,
          steps: {
            welcome: {
              title: "Привіт! Це Wardly",
              text: "Тренер дивиться матч разом із вами: короткі поради поверх гри й голосом, а після матчу — розбір, що виправити. За кілька хвилин покажемо, як виглядають поради, що де лежить і що налаштувати."
            },
            card: {
              title: "Як виглядає порада",
              text: "Картка поверх гри. Великий рядок — що зробити зараз, нижче — чому. «Терміново» з червоною крапкою — робіть одразу: мало HP, поруч смерть. Решта — підказки, які можна виконати в найближчий зручний момент. Картку видно лише в матчі, коли Дота на передньому плані."
            },
            mapline: {
              title: "Таймери й підказки на мапі",
              text: "Руни, стаки, Рошан, Торментор, суперник, що зник з лінії, невкладене очко навички — приходять карткою «Мапа» з часом до події. Під карткою смуга таймерів відлічує найближчі події."
            },
            plan: {
              title: "План, екран смерті й підсумок",
              text: "До горна картка покаже план: скільки добити до 10:00, ключовий предмет і ваш фокус. Поки герой мертвий — чому ви загинули й що купити, а на екрані рахунку — оцінку матчу й одну річ, яку варто виправити."
            },
            status: {
              title: "Рядок стану",
              text: "Що відбувається зараз: чи знайдено Доту, чи йдуть від неї дані, чи почався матч. Якщо треба щось зробити, праворуч буде кнопка."
            },
            setup: {
              title: "Перший запуск",
              text: "Що вже налаштовано й що лишилося. Більшість кроків виконуються самі. Якщо Дота попросить, додайте в параметри запуску -gamestateintegration (кнопка скопіює). Перший матч із застосунком закриє список."
            },
            match: {
              title: "Поточний матч",
              text: "Ваш герой, час матчу й поради тренера. Під кожною порадою «Чому ця порада?» — що тренер побачив. Під час матчу поради з'являються поверх гри, сюди дивитися не потрібно."
            },
            matches: {
              title: "Матчі",
              text: "Кожен матч із розбором: оцінки за областями, де ви гинули, таймінги предметів і що виправити насамперед. Розбір готовий за хвилину-дві після матчу."
            },
            progress: {
              title: "Прогрес",
              text: "Як ви граєте в останніх матчах: тренди, повторювані помилки, лінії й герої. Оберіть одну проблему фокусом — кожен наступний матч покаже, чи вдалося її виправити."
            },
            profile: {
              title: "Профіль і друзі",
              text: "Графік рейтингу, рівень і нагороди за матчі із застосунком. За ігри нараховуються іскри — за них купуються рамки, банери й титули. Обміняйтеся кодами з другом, щоб бачити одне одного в таблиці."
            },
            settings: {
              title: "Картка в грі",
              text: "Де картка з порадою стоїть поверх гри й якого вона розміру. Її можна перетягнути вручну."
            },
            voice: {
              title: "Поради й голос",
              text: "Як часто тренер підказує, ваша роль і голос. Роль краще залишити на «Авто»: тренер сам зрозуміє її за лінією. Голос читає поради вголос і працює навіть у повноекранному режимі, де картки не видно."
            },
            ai: {
              title: "ШІ-тренер (за бажанням)",
              text: "З безкоштовним ключем Google AI Studio в розборі з'явиться текстовий розбір від тренера, і про будь-який матч можна буде поставити запитання. Усе інше працює й без ключа."
            },
            help: {
              title: "Допомога",
              text: "Звідси навчання відкривається знову. Якщо щось не працює, «Повідомити про проблему» надішле розробникові звіт із тим, що надсилала гра (без ключів і паролів)."
            },
            done: {
              title: "Усе готово",
              text: "Запустіть Доту й почніть матч — перша підказка з'явиться сама, а розбір буде готовий за хвилину-дві після гри. Успіхів!"
            }
          }
        },
        summaryTitle: "Зведення",
        sessionTitle: "Підсумок вечора",
        sessionHide: "Сховати",
        tourTitle: "Як користуватися Wardly",
        tourHint: "Коротка екскурсія застосунком, на хвилину",
        tourStart: "Показати",
        whatsNew: whatsNew.texts("uk"),
        setupTitle: "Перший запуск",
        setupPreviewTitle: "Так це виглядає в грі",
        setupPreviewText: "Підказка з'являється поверх гри, коли вона потрібна, а після матчу тренер пише розбір з оцінкою й одним головним, що виправити.",
        setupHide: "Сховати",
        setupCount: (done, total) => `${done} з ${total}`,
        setup: {
          service: ["Тренера запущено", "Запускається разом із застосунком. Якщо зупинився — перезапустіть застосунок."],
          dota: ["Dota 2 знайдено", "Гри немає в бібліотеках Steam — вкажіть теку гри."],
          gsi: ["Застосунок підключено до Доти", "Маленький файл у теці Доти: через нього гра повідомляє тренерові, що відбувається в матчі."],
          launch: ["Дота передає дані матчу", "Для цього потрібен параметр запуску. У Steam: правою кнопкою на Dota 2 → Властивості → Параметри запуску, вставте -gamestateintegration."],
          data: ["Дота зв'язалася з тренером", "Запустіть Dota 2 (або перезапустіть, якщо вона була відкрита) і зайдіть у будь-який матч, можна з ботами."],
          account: ["Акаунт Steam прив'язано", "Прив'яжеться сам у першому матчі, або вкажіть його на вкладці «Матчі»."],
          ai: ["ШІ-тренер (за бажанням)", "З безкоштовним ключем Google ШІ-тренер напише розбір кожного матчу простими словами."]
        },
        setupActions: { dota: "Вказати теку", gsi: "Підключити", launch: "Скопіювати", account: "Прив'язати", ai: "Налаштувати" },
        reportTitle: "Повідомити про проблему",
        reportHint: "Щось не працює? Натисніть «Повідомити» й опишіть двома словами: розробник отримає журнал застосунку. Ключі й паролі з нього вирізаються.",
        reportSave: "Зберегти у файл замість надсилання",
        autoBackupTitle: "Автоматичні копії",
        autoBackupHint: "Раз на тиждень і перед кожним оновленням Wardly зберігає копію вашої історії на цьому комп'ютері: останні 4, до 200 МБ. Відновлення лише додає відсутнє й нічого не видаляє.",
        autoBackupNow: "Зробити копію зараз",
        autoBackupMaking: "Роблю копію…",
        autoBackupMade: "Копію збережено.",
        autoBackupNone: "Копій поки немає: перша з'явиться після першого розібраного матчу.",
        autoBackupOff: "Автоматичні копії вимкнено. Зробити копію вручну можна й зараз.",
        autoBackupFailed: "Не вдалося зробити копію. Спробуйте пізніше.",
        autoBackupKinds: { weekly: "щотижнева", update: "перед оновленням", manual: "вручну" },
        autoBackupItem: (date, kind, matches, size) => `${date} · ${kind} · матчів: ${matches == null ? "?" : matches} · ${size}`,
        autoBackupCheck: "Перевірити",
        autoBackupChecking: "Порівнюю з вашою історією…",
        autoBackupPreview: (matches, notes) => (matches || notes ? `Відновлення додасть матчів: ${matches}${notes ? ` і заповнить порожніх полів: ${notes}` : ""}. Нічого не видалиться.` : "Додавати нічого: усе з цієї копії вже є в історії."),
        autoBackupRestore: "Відновити",
        autoBackupRestored: (matches) => `Відновлено: додано матчів — ${matches}.`,
        autoBackupBroken: "Копію пошкоджено, вона не читається.",
        backupTitle: "Запасна копія у файлі",
        backupHint: "Зберігає всі матчі й розбори в один файл — наприклад, перед перевстановленням Windows. Потім його можна відкрити у Wardly на будь-якому комп'ютері. Ключі у файл не потрапляють.",
        backupExport: "Зберегти у файл",
        backupImport: "Відкрити файл",
        backupSaved: (count, file) => `Збережено матчів: ${count}. Файл ${file}`,
        backupLoaded: (added, linked) => `Завантажено нових матчів: ${added}${linked ? ", акаунт прив'язано" : ""}. Нічого не перезаписано.`,
        backupNotBackup: "Це не файл історії Wardly, або в ньому пошкоджено дані. Дані з файлу не збережено.",
        backupNewer: "Файл створено новішою версією: спершу оновіть застосунок.",
        backupRestoreFailed: "Не вдалося відновити історію. Дані з файлу не збережено; перевірте диск і повторіть спробу.",
        backupFailed: "Не вдалося: тренера не запущено або диск недоступний.",
        transferTitle: "Перенесення на інший комп'ютер",
        zoneMyData: "Ваші матчі",
        zoneMyDataHint: "Щоб історія не загубилася під час зміни комп'ютера",
        zoneHelp: "Допомога",
        zoneHelpHint: "Як користуватися застосунком і що робити, якщо щось зламалося",
        transferIntro: "Поставили Wardly на новий комп'ютер? Перенесіть туди свої матчі й розбори — це займе хвилину.",
        transferStep1: "Тут натисніть «Отримати код».",
        transferStep2: "На новому комп'ютері: Wardly → Налаштування → «Перенесення на інший комп'ютер» → «У мене є код» — і введіть його.",
        transferHave: "У мене є код",
        transferHint: "Код діє 15 хвилин. Матчі передаються в зашифрованому вигляді, ключі не переносяться.",
        transferSend: "Отримати код",
        transferReceive: "Завантажити",
        transferInputLabel: "Код з іншого комп'ютера",
        transferSending: "Шифрую й надсилаю…",
        transferReady: (matches, time) => `Код діє до ${time}. Введіть його на новому комп'ютері (матчів: ${matches}).`,
        transferReceiving: "Завантажую й розшифровую…",
        transferErrors: {
          bad_code: "Перевірте код: три групи по чотири літери й цифри, як на іншому комп'ютері.",
          not_found: "За цим кодом нічого немає: він застарів (15 хвилин) або історію вже завантажено. Отримайте новий код.",
          too_big: "Історія завелика для перенесення за кодом: збережіть її у файл.",
          rate_limited: "Забагато спроб: зачекайте годину або перенесіть файлом.",
          disabled: "Перенесення за кодом зараз вимкнено: скористайтеся файлом.",
          not_backup: "Код відкрив щось, що не схоже на історію Wardly.",
          offline: "Немає зв'язку із сервером: перевірте інтернет.",
          fallback: "Не вдалося: спробуйте ще раз або перенесіть файлом."
        },
        reportSaving: "Збираємо…",
        reportSaved: (name) => `Збережено: ${name}. Надішліть цей файл розробникові.`,
        reportFailed: "Не вдалося зберегти файл",
        reportSend: "Повідомити",
        reportNoteLabel: "Що сталося? (необов'язково)",
        reportNotePlaceholder: "Наприклад: у матчі не видно підказок",
        reportPreview: "Що буде надіслано",
        reportPreviewLoading: "Збираємо звіт…",
        reportTerms: "Ключі вирізано. Звіт зберігається 180 днів.",
        reportPrivacy: "Конфіденційність",
        reportSendNow: "Надіслати",
        reportCancel: "Скасувати",
        reportSending: "Надсилаємо…",
        reportSentId: (id) => `Надіслано. Номер звіту: ${id}. Назвіть його, якщо писатимете розробникові.`,
        reportQueued: "Зараз немає інтернету. Звіт надішлеться сам пізніше.",
        reportQueuedCount: (count) => `Чекають надсилання: ${count}`,
        reportLast: (id) => `Останній звіт: ${id}`,
        reportRefused: (name) =>
          name ? `Сервер не прийняв звіт. Натомість збережено файл: ${name}.` : "Сервер не прийняв звіт.",
        devTitle: "Для розробника",
        devHint: "Технічні інструменти: процес тренера, зв'язок із грою, журнали. Для гри не потрібні",
        factBackend: "Сервіс",
        factDota: "Дота",
        factOverlay: "Оверлей",
        factDemo: "Демо",
        factRecording: "Запис",
        factGsiConfig: "Конфіг GSI",
        factMode: "Режим",
        groupBackend: "Сервіс",
        startBackend: "Запустити",
        restartBackend: "Перезапустити",
        stopBackend: "Зупинити",
        showOverlay: "Показати оверлей",
        hideOverlay: "Сховати оверлей",
        hotkeys: "Ctrl+Alt+O увімк/вимк · Ctrl+Alt+L перемістити · Ctrl+Alt+M тиша 5 хв · Ctrl+Alt+R повторити пораду · Ctrl+Alt+1/2/3 ліворуч/праворуч/знизу · Ctrl+Alt+D налагодження",
        groupGsi: "Конфіг GSI",
        gsiPathPlaceholder: "Власна тека gamestate_integration (необов'язково)",
        chooseFolder: "Обрати",
        checkGsi: "Перевірити",
        installGsi: "Встановити",
        gsiPath: (p, e) => `Конфіг: ${p}${e ? `\nАдреса: ${e}` : ""}`,
        gsiPathMissing: "Конфіг не знайдено. Оберіть теку gamestate_integration і встановіть.",
        gsiEndpoint: (e) => (e ? `Адреса: ${e}` : "Адреса: чекаємо порт сервісу…"),
        groupLive: "Живий GSI",
        kvConnection: "Зв'язок",
        kvLast: "Дані",
        kvHero: "Герой",
        kvTime: "Час",
        kvStage: "Стадія",
        liveConnected: "підключено",
        liveWaiting: "очікування / застаріло",
        liveUnavailable: "сервіс недоступний",
        liveAdvice: (a) => `Поточна порада: ${a}`,
        liveAdviceNone: "Поточна порада: поки немає",
        liveAdviceLast: (t) => `Поточна порада: остання о ${t}`,
        liveMissing: (m) => `Бракує полів: ${m}`,
        none: "немає",
        checkLive: "Перевірити",
        startRecording: "Записати",
        stopRecording: "Зупинити запис",
        openRecords: "Записи",
        groupDemo: "Демо-повтор",
        demoHint: "Програє записані стани матчу в сервіс; оверлей видно без Доти.",
        demoBusy: "Демо вже йде. Спершу зупиніть його.",
        runDemo: "Запустити демо",
        presetPl: "Phantom Lancer 20–30",
        presetJugg: "Juggernaut 10–20",
        deepReview: "Deep Review",
        stopDemo: "Зупинити",
        openResults: "Результати",
        groupLogs: "Логи",
        groupOps: "Стан операцій",
        opsHint: "Фонові черги, збереження зіграного матчу, шлях живого GSI і свіжість даних. Лише числа й час.",
        opsRefresh: "Оновити",
        opsAllGood: "Усе гаразд.",
        opsUnavailable: "Сервіс не відповів.",
        opsJobs: "Завдання історії",
        opsAi: "Завдання ШІ-тренера",
        opsMatch: "Збереження матчу",
        opsGsi: "Шлях живого GSI",
        opsData: "Дані",
        opsQueueIdle: (done) => `простоює · виконано ${done}`,
        opsQueueIdleFailed: (done, failed, at) => `простоює · виконано ${done}, з помилкою ${failed}${at ? ` (остання о ${at})` : ""}`,
        opsQueueRunning: (kind, seconds, queued) => `виконується ${kind} ${seconds} с${queued ? ` · чекають ${queued}` : ""}`,
        opsQueueWaiting: (queued, seconds) => `чекають ${queued} · найстаріша ${seconds} с`,
        opsQueueLater: (queued, seconds) => `заплановано ${queued} · наступна через ${seconds} с`,
        opsMatchPending: (n) => `зіграних матчів чекають збереження: ${n}`,
        opsMatchSaved: (at) => `останній матч збережено о ${at}`,
        opsMatchNone: "у цьому запуску матчі не закінчувалися",
        opsGsiNone: "у цьому запуску пакетів не було",
        opsGsiTimes: (count, p50, p95, failed) => `пакетів ${count} · p50 ${p50 ?? "—"} мс · p95 ${p95 ?? "—"} мс${failed ? ` · помилок збереження ${failed}` : ""}`,
        opsDataLine: (state, at, builds, age) => {
          const sync = { done: "матчі оновлено", error: "оновлення матчів не вдалося", running: "матчі оновлюються", queued: "матчі оновлюються" }[state] || "матчі не оновлювалися";
          return `${sync}${at ? ` о ${at}` : ""} · збірки ${builds ? `від ${builds}${age != null ? ` (${age} дн.)` : ""}` : "відсутні"}`;
        },
        opsWarn_jobs_waiting: "Завдання історії чекають у черзі довше 2 хвилин.",
        opsWarn_jobs_running_long: "Завдання історії виконується довше 5 хвилин.",
        opsWarn_jobs_no_worker: "Завдання історії в черзі, але їх нікому виконувати.",
        opsWarn_ai_jobs_waiting: "Завдання ШІ-тренера чекають у черзі довше 2 хвилин.",
        opsWarn_ai_jobs_running_long: "Завдання ШІ-тренера виконується довше 5 хвилин.",
        opsWarn_ai_jobs_no_worker: "Завдання ШІ-тренера в черзі, але їх нікому виконувати.",
        opsWarn_match_not_saved: "Зіграний матч поки не вдалося зберегти; збереження повториться автоматично.",
        opsWarn_recovery_write_failed: "Не вдалося записати файл відновлення матчу.",
        opsWarn_gsi_persistence_failed: "Збереження даних живого GSI хоча б раз не вдалося.",
        opsWarn_gsi_slow: "Шлях живого GSI повільний (p95 більше 250 мс).",
        opsWarn_sync_failed: "Останнє оновлення матчів не вдалося.",
        opsWarn_builds_stale: "Вбудованим збіркам предметів понад три тижні.",
        logClean: "Коротко",
        logVerbose: "Детально",
        copyLogs: "Копіювати",
        clearLogs: "Очистити",
        openLogs: "Тека логів",
        dotaStates: { not_found: "не знайдено", waiting: "чекаємо на матч", in_game: "у грі" },
        gsiConfigStates: { installed: "встановлено", "not found": "не знайдено", error: "помилка", unknown: "невідомо" },
        modes: { "Live GSI": "Живий GSI", "Replay Demo": "Демо-повтор" },
        on: "увімк",
        off: "вимк",
        shown: "на екрані",
        hidden: "приховано",
        running: "йде",
        stopped: "зупинено"
      }
    };
    return I18N;
  }
  const api = {create};
  if (typeof module !== "undefined" && module.exports) module.exports = api;
  else window.WardlyAppTexts = api;
})();
