"use strict";

// Control-panel RU/EN copy is independent of DOM and IPC. A fresh catalog keeps
// update history and nested text tables local to the current panel instance.
(function () {
  function create(whatsNew) {
    const I18N = {
      en: {
        tabHome: "Home",
        tabMatches: "Matches",
        tabProgress: "Progress",
        tabProfile: "Profile",
        tabSettings: "Settings",
        adviceSettingsTitle: "Advice",
        languageTitle: "Language",
        languageHint: "Advice, reviews and the whole app",
        languageAuto: "Auto",
        uiScaleTitle: "Interface size",
        uiScaleHint: "Bigger text and buttons for a large or high-resolution screen. Ctrl + plus and Ctrl + minus work too.",
        uiScaleToast: (size) => `Interface size: ${size}`,
        dataTitle: "Match history",
        odTitle: "Faster match history",
        odPlaceholder: "OpenDota key",
        odSave: "Save",
        odGet: "Get a key on opendota.com",
        odClear: "Remove key",
        odHintOff: "Your match history comes from OpenDota, a free Dota statistics site. Everything works without a key, just slower. A free key from opendota.com makes it faster; it stays on this computer.",
        odHintOn: (hint) => `Key ${hint} saved: your matches load faster.`,
        odHintEnv: "A key is already set in the app's settings file.",
        odBad: "This does not look like an OpenDota key.",
        appTitle: "Main",
        service: "Coach",
        serviceStates: { running: "running", starting: "starting…", stopping: "stopping…", stopped: "stopped" },
        status: {
          loadingTitle: "Starting the coach…",
          loadingHint: "Usually takes a couple of seconds.",
          backendDownTitle: "The coach is stopped",
          backendDownHint: "No advice while it is stopped. Press “Start”: it takes a couple of seconds.",
          gsiErrorTitle: "Could not connect to Dota",
          gsiErrorHint: "No access to the Dota folder. Point to the game folder manually.",
          noDotaTitle: "Dota not found",
          noDotaHint: "Dota 2 was not found in Steam. Point to the game folder and the app does the rest.",
          noGsiTitle: "Connect Dota",
          noGsiHint: "Press “Connect”: the app puts a small file into the Dota folder, and through it the game tells the coach what happens in your match.",
          notRunningTitle: "Dota is not running",
          notRunningHint: "Start Dota 2; the coach connects by itself. You can close this window.",
          connectedTitle: "Dota is connected, waiting for a match",
          noDataTitle: "Dota is running, no data from it yet",
          waitingHintConnected: "Advice starts as soon as a match with your hero begins.",
          waitingHintNoData: "If a match is already on, restart Dota: it connects to the coach only when it starts.",
          launchOptionTitle: "Dota is not sending game data",
          launchOptionHint: "Dota needs one launch option for that. In Steam: right-click Dota 2 → Properties → Launch options, paste -gamestateintegration (the button copies it), then restart the game.",
          inGameTitle: (hero, clock) => `In game: ${[hero, clock].filter(Boolean).join(", ")}`,
          inGameHint: "Advice appears over the game while Dota is the active window.",
          inGameOverlayOff: "Advice over the game is off: it shows only here.",
          demoTitle: (preset) => `Replay demo${preset ? `: ${preset}` : ""}`,
          demoHint: "The overlay shows advice from a recorded match.",
          fullscreenTitle: "Advice is hidden by fullscreen",
          fullscreenHint:
            "Dota runs in exclusive fullscreen, where no window can be drawn on top. In Dota: Settings → Video → Display mode → Borderless window. Or turn on the voice in Settings → Advice: it is heard in any mode."
        },
        actions: {
          start: "Start the coach",
          install: "Connect",
          chooseDota: "Choose Dota folder",
          fullscreenSeen: "I can see the advice",
          copyLaunchOption: "Copy option",
          copied: "Copied"
        },
        matchTitle: "Current match",
        coverageSafety: "The full advice is for 64 heroes (carries, mids, offlaners and supports); on this hero the coach gives survival advice, map timers and role tips.",
        coverageSupport: "Support advice: your own saves, fights and objectives, stacks, pulls, wards and save items. No farm or item advice: the gold goes to your cores.",
        statHero: "Hero",
        statClock: "Match time",
        statStage: "Phase",
        statData: "Link to the game",
        dataFresh: (s) => `${s} s ago`,
        dataFreshNow: "just now",
        matchEmptyTitle: "No match right now",
        matchEmptyHint: "Hero and time show up here when a match starts.",
        offlineTitle: "The coach is not running",
        offlineHint: "Start it to see your match here.",
        adviceTitle: "Recent advice",
        adviceWhy: "Why this advice?",
        adviceEmptyTitle: "No advice yet",
        adviceEmptyHint: "Advice shows up here as it appears over the game.",
        priority: { high: "urgent", urgent: "urgent", medium: "important", low: "tip", safe: "calm" },
        stages: { laning: "Lanes", "post-laning": "After the lanes", macro: "Mid and late game" },
        overlayTitle: "Advice card",
        overlayShow: "Show advice over the game",
        overlayReason: {
          off: "Off",
          positioning: "Shown so you can move it",
          demo: "Showing the replay demo",
          no_tracking: "Always visible: on this system the app cannot tell whether Dota is open",
          dota_not_running: "Appears in a match, over Dota",
          dota_not_focused: "Hidden while Dota is in the background",
          no_match: "Appears when a match starts",
          in_game: "On screen now"
        },
        overlayPosition: "Where on the screen",
        positionHint: "Away from the minimap and the hero panel",
        positionCustom: "Custom position, pick a preset to reset",
        posLeft: "Left",
        posRight: "Right",
        posBottom: "Bottom",
        overlaySize: "Card size",
        overlaySizeHint: "Larger on big and high-resolution screens",
        overlayTimers: "Timer strip",
        skillArrowsTitle: "Arrows over your abilities",
        skillArrowsCalibrate: "Fine-tune",
        skillArrowsHint: {
          on: "With a skill point to spend, an arrow points at the ability right on Dota's bar and finds the icons by itself. “Fine-tune” if it misses.",
          manual: "On, with your own frame. “Fine-tune” → “Automatic” goes back to finding the icons by itself.",
          off: "Off. The card still names the ability to level."
        },
        overlayTimersHint: "Always under the card: how long until the next runes, stacks, Roshan and Aegis for your role",
        overlayCompact: "Short advice",
        overlayCompactHint: "Only what to do, without the reason: less to read during a fight",
        hotkeysTitle: "Hotkeys",
        hotkeysGame: "In the game",
        hotkeysApp: "In this window",
        hotkeyTabs: "Home, Matches, Progress, Profile, Settings",
        hotkeyBack: "From a match review back to where you opened it",
        hotkeyHistory: "Back / forward through the pages you opened (the mouse's side buttons too)",
        hotkeyFind: "On Settings: find a setting",
        hotkeyPalette: "Find a tab, a match, a setting or an action",
        findAnything: "Find…",
        hotkeyZoom: "Interface size bigger / smaller, Ctrl+0 back to 100%",
        hotkeyNeighbour: "In a match review: the match above / below in the list (newer / older unless the list is sorted)",
        hotkeyHelp: "This list of keys, from any tab",
        hotkeyToggle: "Turn the advice card on or off",
        hotkeyRepeat: "Show (and say) the last advice again",
        hotkeyMute: "No advice for 5 minutes",
        hotkeyMove: "Unlock the card to drag it, press again to lock",
        hotkeyPlace: "The card on the left / on the right / at the bottom",
        sizeSmall: "Small",
        sizeNormal: "Normal",
        sizeLarge: "Large",
        frequencyTitle: "How often",
        frequencyCalm: "Less",
        frequencyNormal: "Normal",
        frequencyActive: "More",
        roleTitle: "Your role",
        roleAuto: "Auto",
        roleCarry: "Carry",
        roleMid: "Mid",
        roleOfflane: "Offlane",
        roleSupport: "Support",
        roleHint: {
          auto: "The coach works it out from your lane in the first minutes. Pick a role if it gets it wrong",
          carry: "Timers and tips for a carry",
          mid: "Runes and timers for a mid player",
          offlane: "Shrines, lotuses and timers for an offlaner",
          support: "Stacks, wards and runes for a support; farm advice is off"
        },
        roleNames: { carry: "carry", mid: "mid", offlane: "offlane", support: "support" },
        roleSource: {
          setting: "chosen in Settings",
          lane: "from your lane",
          history: "from your past games on this hero",
          hero: "usual for this hero"
        },
        roleNote: (role, source) => `Role: ${role}, ${source}.`,
        roleMismatch: (setting, seen) => `“Your role” is set to ${setting}, but you play as ${seen}: some tips miss.`,
        roleSetAuto: "Set to Auto",
        mapHintsTitle: "Map timers",
        mapHintsHint: "A reminder on the card 20 s before runes, shrines, Tormentor, stacks and wards — only the ones your role needs. Off also hides the timer strip",
        frequencyHint: {
          calm: "Twice the pause between tips; urgent advice is never delayed",
          normal: "Balanced pauses between tips",
          active: "Shorter pauses between tips; urgent advice as always"
        },
        voiceTitle: "Voice",
        voiceOff: "Off",
        voiceUrgent: "Urgent",
        voiceAll: "All",
        voiceTest: "Listen",
        voiceHint: {
          off: "Advice is only shown, not spoken",
          urgent: "Speaks urgent advice; heard even in exclusive fullscreen. Ctrl+Alt+R repeats",
          all: "Speaks every piece of advice; heard even in exclusive fullscreen. Ctrl+Alt+R repeats"
        },
        voiceNoVoice: "No English voice in the system: Windows Settings → Time & language → Speech",
        voiceSample: "Back off: the enemy is missing from the map.",
        overlayMove: "Move by hand",
        moveHint: "Shows the card so you can drag it anywhere",
        moveActiveHint: "Drag the card, then press Done",
        moveStart: "Move",
        moveDone: "Done",
        recordsTitle: "Keep match recordings for a week",
        recordsHint: "Everything the game sent during each match and every advice shown, kept on this computer for 7 days. Save any match as a file and send it to the developer, the next day too. No nicknames, Steam IDs or chat.",
        recordsOff: "Off: matches are not recorded.",
        recordsEmpty: "On: the next match will be recorded.",
        recordsCount: (n) => `On: ${n} ${n === 1 ? "match" : "matches"} recorded this week.`,
        recordsSave: "Save file",
        recordsSaved: "Saved to Downloads.",
        recordsFailed: "Could not save the file.",
        recordsMinutes: (n) => `${n} min`,
        recordsAdvice: (n) => `${n} advice`,
        statsTitle: "Help improve the advice",
        statsHint: "Once a day the app sends anonymous counts: which advice was shown and which warnings came before a death. No heroes, matches, nickname or keys. Off by default.",
        statsPreview: "What is sent (today so far)",
        statsTerms: "Kept for a year.",
        statsOff: "Off: nothing is sent.",
        statsOn: "On: the first upload is tomorrow, with today's counts.",
        statsSent: (date) => `On. Last sent ${date}.`,
        statsPreviewLoading: "Collecting…",
        statsPreviewFailed: "The coach is not running: nothing to show.",
        serverDelete: "Delete my data on the server",
        serverDeleteConfirm: "Delete for sure? Press again",
        serverDeleted: "Deleted: problem reports, shared links and statistics of this computer are gone from the server.",
        serverDeleteFailed: (code) => `Could not delete (${code}): check the internet and try again.`,
        discordTitle: "Status in Discord",
        discordHint: "Your Discord friends see “Playing Juggernaut · with the Wardly coach” while Dota runs",
        discordStates: {
          idle: "It appears once Dota is running.",
          connecting: "Connecting to Discord…",
          no_discord: "Discord not found: open the Discord app on this computer (the browser version cannot show it).",
          connected: "Discord connected. The status appears once Dota is running.",
          shown: "Shown in Discord. Friends do not see it? Discord → Settings → Activity Privacy → “Share your detected activities with others”.",
          rejected: (error) => `Discord did not accept the status: ${error}`
        },
        settingsMore: "More settings",
        settingsMoreHint: "Match recordings, statistics, the OpenDota key, your week in Discord",
        settingsPageTitle: "Settings",
        settingsPageSub: "Everything already works. Change only what you want to.",
        settingsSearch: "Find a setting",
        settingsSearchEmpty: "Nothing found. Try another word, for example “voice”, “size” or “key”.",
        settingsSearchClear: "Show all settings",
        zoneNow: "Now",
        zoneNowHint: "The current match and the advice it got",
        zoneHistory: "Last matches",
        zoneHistoryHint: "Open one for its review",
        zoneWeek: "Your week",
        zoneWeekHint: "The last seven days against the seven before",
        zoneAllMatches: "All matches",
        zoneGame: "In the game",
        zoneGameHint: "What you see and hear during a match",
        zoneData: "After the match",
        zoneDataHint: "A review of every match in plain words, written by the AI coach",
        zoneApp: "App",
        zoneAppHint: "Language, start with Windows, updates",
        weeklyTitle: "The week in Discord",
        weeklyHint:
          "Every Monday the week's matches, results and average score are posted to a channel of your Discord server. You need the channel's webhook link: in Discord open the channel settings → Integrations → Webhooks → New webhook → Copy webhook URL, and paste it here.",
        weeklyInputLabel: "Webhook link",
        weeklyConnect: "Connect",
        weeklySendNow: "Send now",
        weeklyDisconnect: "Disconnect",
        weeklySending: "Sending…",
        weeklyConnected: (hint) => `Connected (${hint}). The week goes to Discord every Monday.`,
        weeklySent: (date) => `Last post: ${date}.`,
        weeklyEmpty: (date) => `${date}: no matches in that week, nothing was posted.`,
        weeklyNoMatchesNow: "No matches in the last seven days: nothing to post yet.",
        weeklyErrors: {
          bad_url: "This is not a Discord webhook link: it starts with https://discord.com/api/webhooks/.",
          webhook_gone: "The webhook was deleted in Discord: create a new one and connect it again.",
          rate_limited: "Discord asks to wait: try again in a minute.",
          offline: "No connection to Discord: check the internet.",
          backend_down: "The coach is not running yet: try again in a moment.",
          busy: "Already sending…",
          fallback: "Could not post: try again later."
        },
        autostart: "Start with Windows",
        autostartOn: "Wardly opens by itself when the computer starts and waits quietly next to the clock, so you never forget it before a game.",
        autostartOff: "Off: open Wardly yourself before you play. Turn it on and Wardly will open with the computer and wait quietly next to the clock.",
        autostartUnavailable: "Available in the installed app",
        updates: "Updates",
        updateCheck: "Check",
        updateInstall: "Restart and update",
        updateHint: {
          disabled: (v) => `Version ${v} · updates work in the installed app`,
          idle: (v) => `Version ${v} · updates install by themselves`,
          checking: (v) => `Version ${v} · checking…`,
          "up-to-date": (v) => `Version ${v} · up to date`,
          downloading: (v, next, pct) => `Downloading ${next}… ${pct}%`,
          ready: (v, next) => `Version ${next} is ready. It installs by itself once Dota is closed.`,
          blocked: (v, next) => `Version ${next} is ready. It installs after you close Dota.`,
          error: (v) => `Version ${v} · could not check for updates`
        },
        whatsNewTitle: (version) => `What's new in ${version}`,
        whatsNewAlso: (version) => `Also in ${version}`,
        whatsNewOk: "Got it",
        inviteTitle: "Like Wardly?",
        inviteText: "Send the link to a friend: the app is free, and playing together it is easier to follow the advice.",
        inviteCopy: "Copy the link",
        inviteLater: "Not now",
        inviteCopied: "Link copied",
        tour: {
          next: "Next",
          back: "Back",
          skip: "Skip",
          done: "Start playing",
          count: (i, n) => `${i} of ${n}`,
          steps: {
            welcome: {
              title: "Hi! This is Wardly",
              text: "The coach watches your match with you: short advice over the game and out loud, and a review with what to fix after it. A two-minute look around: what the advice looks like, where everything is and what to set up."
            },
            card: {
              title: "What advice looks like",
              text: "A card over the game. The big line is what to do now, the line below is why. “Urgent” with a red dot means right now: low HP, a death coming. The rest are tips you can do at the next good moment. The card shows only during a match, while Dota is in front."
            },
            mapline: {
              title: "Map timers and calls",
              text: "Runes, stacks, Roshan, the Tormentor, an enemy missing from your lane, an unspent skill point: these come as a “Map” card with the time left. Under the card a strip counts down the next timers."
            },
            plan: {
              title: "Plan, death screen and score",
              text: "Before the horn the card shows a plan: last hits to reach by 10:00, the key item and your focus. While you are dead it says why you died and what to buy, and on the score screen it gives the match score and one thing to fix."
            },
            status: {
              title: "Status line",
              text: "What is going on right now: is Dota found, is it sending data, is a match on. When something needs you, the button on the right does it."
            },
            setup: {
              title: "Getting started",
              text: "What is set up and what is left. Most steps do themselves. If Dota asks for it, add -gamestateintegration to its launch options (the button copies it). The first match with the app finishes the list."
            },
            match: {
              title: "Current match",
              text: "Your hero, the match time and the advice the coach gave. Under each advice, “Why this advice?” says what the coach saw. During a match the advice appears over the game: you do not need to look here."
            },
            matches: {
              title: "Matches",
              text: "Every match with a review: a score by area, where you died, the item timings and what to fix first. The review of a match is ready a minute or two after it ends."
            },
            progress: {
              title: "Progress",
              text: "How you play over the last games: the trends, the mistakes that repeat, your lanes and heroes. Pick one problem as your focus: every next match shows whether you fixed it."
            },
            profile: {
              title: "Profile and friends",
              text: "Your rating graph, level and achievements for matches with the app. Sparks from games buy frames, banners and titles. Share your friend code to see each other on a leaderboard."
            },
            settings: {
              title: "Card over the game",
              text: "Where the advice card sits over the game and how big it is. You can drag it by hand."
            },
            voice: {
              title: "Advice and voice",
              text: "How often the coach speaks, your role and the voice. Leave the role on “Auto”: the coach works it out from your lane. The voice reads the advice out loud and also works in exclusive fullscreen, where no card can be drawn."
            },
            ai: {
              title: "AI coach (optional)",
              text: "With a free Google AI Studio key the review gets a written breakdown and you can ask the coach about any match. Everything else works without it."
            },
            help: {
              title: "Help",
              text: "This tour opens again from here. If something does not work, “Report a problem” sends the developer a report with what the game sent (no keys or passwords)."
            },
            done: {
              title: "All set",
              text: "Start Dota and play a match: the first advice appears by itself, and the review is ready a minute or two after the game. Good luck!"
            }
          }
        },
        summaryTitle: "Summary",
        sessionTitle: "Your evening",
        sessionHide: "Hide",
        tourTitle: "How to use Wardly",
        tourHint: "A short tour of the app, one minute",
        tourStart: "Show",
        whatsNew: whatsNew.texts("en"),
        setupTitle: "Getting started",
        setupPreviewTitle: "What you will see in game",
        setupPreviewText: "Advice appears over the game when it matters, and after the match the coach writes a review with a score and one thing to fix.",
        setupHide: "Hide",
        setupCount: (done, total) => `${done} of ${total}`,
        setup: {
          service: ["The coach is running", "Starts with the app. If it stopped, restart the app."],
          dota: ["Dota 2 found", "Not in your Steam libraries: point to the game folder."],
          gsi: ["Connected to Dota", "A small file in the Dota folder: through it the game tells the coach what happens in your match."],
          launch: ["Dota shares the match", "Dota needs a launch option for it. In Steam: right-click Dota 2 → Properties → Launch options, paste -gamestateintegration."],
          data: ["Dota has talked to the coach", "Start Dota 2 (or restart it if it was running) and open any match, bots are fine."],
          account: ["Steam account linked", "Linked by itself in the first match, or enter it on the Matches tab."],
          ai: ["AI coach (optional)", "With a free Google key the AI writes a review of every match in plain words."]
        },
        setupActions: { dota: "Choose folder", gsi: "Connect", launch: "Copy", account: "Link", ai: "Set up" },
        reportTitle: "Report a problem",
        reportHint: "Something does not work? Press “Report” and describe it in a few words: the developer gets the app's log. Keys and passwords are cut out.",
        reportSave: "Save as a file instead",
        backupTitle: "Spare copy in a file",
        backupHint: "Saves all your matches and reviews into one file, for example before reinstalling Windows. Open it later in Wardly on any computer. Keys are not saved.",
        backupExport: "Save to file",
        backupImport: "Open a file",
        backupSaved: (count, file) => `Saved ${count} matches: ${file}`,
        backupLoaded: (added, linked) => `Loaded: ${added} new matches${linked ? ", account linked" : ""}. Nothing was overwritten.`,
        backupNotBackup: "This file is not a Wardly history backup, or its data is damaged. Nothing from the file was saved.",
        backupNewer: "The backup was made by a newer version: update the app first.",
        backupRestoreFailed: "Could not restore the history. Nothing from the file was saved; check the disk and try again.",
        backupFailed: "Could not do it: the coach is not running or the disk is not available.",
        transferTitle: "Move to another computer",
        zoneMyData: "Your matches",
        zoneMyDataHint: "So your history is not lost when you change computers",
        zoneHelp: "Help",
        zoneHelpHint: "How to use the app, and what to do if something breaks",
        transferIntro: "Installed Wardly on a new computer? Move your matches and reviews there, it takes a minute.",
        transferStep1: "Here, press “Get a code”.",
        transferStep2: "On the new computer: Wardly → Settings → Move to another computer → “I have a code”, and type it in.",
        transferHave: "I have a code",
        transferHint: "The code works for 15 minutes. Your matches travel encrypted; keys are not moved.",
        transferSend: "Get a code",
        transferReceive: "Load",
        transferInputLabel: "Code from the other computer",
        transferSending: "Encrypting and sending…",
        transferReady: (matches, time) => `The code works until ${time}. Type it in on the new computer (matches: ${matches}).`,
        transferReceiving: "Downloading and decrypting…",
        transferErrors: {
          bad_code: "Check the code: three groups of four letters and digits, as shown on the other computer.",
          not_found: "No history under this code: it has expired (15 minutes) or was already loaded. Get a new code.",
          too_big: "The history is too big to send by code: save it to a file instead.",
          rate_limited: "Too many tries for now: wait an hour or move it with a file.",
          disabled: "Moving by code is switched off right now: use a file.",
          not_backup: "The code opened something that is not a Wardly history.",
          offline: "No connection to the server: check the internet.",
          fallback: "Could not do it: try again or use a file."
        },
        reportSaving: "Collecting…",
        reportSaved: (name) => `Saved: ${name}. Send this file to the developer.`,
        reportFailed: "Could not save the file",
        reportSend: "Report",
        reportNoteLabel: "What happened? (optional)",
        reportNotePlaceholder: "For example: no advice shows in a match",
        reportPreview: "What will be sent",
        reportPreviewLoading: "Collecting the report…",
        reportTerms: "Keys are cut out. The report is kept for 180 days.",
        reportPrivacy: "Privacy",
        reportSendNow: "Send",
        reportCancel: "Cancel",
        reportSending: "Sending…",
        reportSentId: (id) => `Sent. Report number: ${id}. Mention it if you write to the developer.`,
        reportQueued: "No internet right now. The report will be sent by itself later.",
        reportQueuedCount: (count) => `Waiting to be sent: ${count}`,
        reportLast: (id) => `Last report: ${id}`,
        reportRefused: (name) =>
          name ? `The server did not accept the report. Saved a file instead: ${name}.` : "The server did not accept the report.",
        devTitle: "For developers",
        devHint: "Technical tools: the coach process, the link to the game, logs. You do not need them to play",
        factBackend: "Service",
        factDota: "Dota",
        factOverlay: "Overlay",
        factDemo: "Demo",
        factRecording: "Recording",
        factGsiConfig: "GSI config",
        factMode: "Mode",
        groupBackend: "Service",
        startBackend: "Start",
        restartBackend: "Restart",
        stopBackend: "Stop",
        showOverlay: "Show overlay",
        hideOverlay: "Hide overlay",
        hotkeys: "Ctrl+Alt+O on/off · Ctrl+Alt+L move · Ctrl+Alt+M mute 5 min · Ctrl+Alt+R repeat advice · Ctrl+Alt+1/2/3 left/right/bottom · Ctrl+Alt+D debug line",
        groupGsi: "GSI config",
        gsiPathPlaceholder: "Custom gamestate_integration folder (optional)",
        chooseFolder: "Choose",
        checkGsi: "Check",
        installGsi: "Install",
        gsiPath: (p, e) => `Config: ${p}${e ? `\nEndpoint: ${e}` : ""}`,
        gsiPathMissing: "Config not found. Choose the gamestate_integration folder and install.",
        gsiEndpoint: (e) => (e ? `Endpoint: ${e}` : "Endpoint: waiting for the service port…"),
        groupLive: "Live GSI",
        kvConnection: "Connection",
        kvLast: "Last data",
        kvHero: "Hero",
        kvTime: "Game time",
        kvStage: "Stage",
        liveConnected: "connected",
        liveWaiting: "waiting / stale",
        liveUnavailable: "service unavailable",
        liveAdvice: (a) => `Current advice: ${a}`,
        liveAdviceNone: "Current advice: none yet",
        liveAdviceLast: (t) => `Current advice: last shown at ${t}`,
        liveMissing: (m) => `Missing important fields: ${m}`,
        none: "none",
        checkLive: "Check",
        startRecording: "Record",
        stopRecording: "Stop recording",
        openRecords: "Recordings",
        groupDemo: "Replay demo",
        demoHint: "Plays recorded match states into the service; the overlay shows without Dota.",
        demoBusy: "A demo is already running. Stop it first.",
        runDemo: "Run demo",
        presetPl: "Phantom Lancer 20–30",
        presetJugg: "Juggernaut 10–20",
        deepReview: "Deep Review",
        stopDemo: "Stop",
        openResults: "Results",
        groupLogs: "Logs",
        groupOps: "Operations health",
        opsHint: "Background queues, saving the finished match, the live GSI path and how fresh the data are. Counts and times only.",
        opsRefresh: "Refresh",
        opsAllGood: "Nothing looks wrong.",
        opsUnavailable: "The service did not answer.",
        opsJobs: "History jobs",
        opsAi: "AI coach jobs",
        opsMatch: "Match saving",
        opsGsi: "Live GSI path",
        opsData: "Data",
        opsQueueIdle: (done) => `idle · ${done} done`,
        opsQueueIdleFailed: (done, failed, at) => `idle · ${done} done, ${failed} failed${at ? ` (last ${at})` : ""}`,
        opsQueueRunning: (kind, seconds, queued) => `running ${kind} for ${seconds} s${queued ? ` · ${queued} waiting` : ""}`,
        opsQueueWaiting: (queued, seconds) => `${queued} waiting · the oldest for ${seconds} s`,
        opsQueueLater: (queued, seconds) => `${queued} scheduled · next in ${seconds} s`,
        opsMatchPending: (n) => `${n} finished ${n === 1 ? "match is" : "matches are"} waiting to be saved`,
        opsMatchSaved: (at) => `last match saved at ${at}`,
        opsMatchNone: "no match finished in this session",
        opsGsiNone: "no packets in this session",
        opsGsiTimes: (count, p50, p95, failed) => `${count} packets · p50 ${p50 ?? "—"} ms · p95 ${p95 ?? "—"} ms${failed ? ` · ${failed} saves failed` : ""}`,
        opsDataLine: (state, at, builds, age) => {
          const sync = { done: "matches synced", error: "match sync failed", running: "syncing matches", queued: "syncing matches" }[state] || "matches not synced";
          return `${sync}${at ? ` ${at}` : ""} · builds ${builds ? `from ${builds}${age != null ? ` (${age} d)` : ""}` : "missing"}`;
        },
        opsWarn_jobs_waiting: "History jobs wait in the queue for over 2 minutes.",
        opsWarn_jobs_running_long: "A history job has run for over 5 minutes.",
        opsWarn_jobs_no_worker: "History jobs are queued but no worker runs them.",
        opsWarn_ai_jobs_waiting: "AI coach jobs wait in the queue for over 2 minutes.",
        opsWarn_ai_jobs_running_long: "An AI coach job has run for over 5 minutes.",
        opsWarn_ai_jobs_no_worker: "AI coach jobs are queued but no worker runs them.",
        opsWarn_match_not_saved: "A finished match could not be saved yet; it is kept and retried.",
        opsWarn_recovery_write_failed: "The match recovery file could not be written.",
        opsWarn_gsi_persistence_failed: "Saving live GSI data failed at least once.",
        opsWarn_gsi_slow: "The live GSI path is slow (p95 over 250 ms).",
        opsWarn_sync_failed: "The last match sync failed.",
        opsWarn_builds_stale: "The bundled item builds are over three weeks old.",
        logClean: "Clean",
        logVerbose: "Verbose",
        copyLogs: "Copy",
        clearLogs: "Clear",
        openLogs: "Logs folder",
        dotaStates: { not_found: "not found", waiting: "waiting for a match", in_game: "in game" },
        gsiConfigStates: { installed: "installed", "not found": "not found", error: "error", unknown: "unknown" },
        modes: { "Live GSI": "Live GSI", "Replay Demo": "Replay demo" },
        on: "on",
        off: "off",
        shown: "on screen",
        hidden: "hidden",
        running: "running",
        stopped: "stopped"
      },
      ru: {
        tabHome: "Главная",
        tabMatches: "Матчи",
        tabProgress: "Прогресс",
        tabProfile: "Профиль",
        tabSettings: "Настройки",
        adviceSettingsTitle: "Советы",
        languageTitle: "Язык",
        languageHint: "Советы, разборы и всё приложение",
        languageAuto: "Как в системе",
        uiScaleTitle: "Размер интерфейса",
        uiScaleHint: "Крупнее текст и кнопки — для большого экрана или высокого разрешения. Работают и Ctrl + плюс, Ctrl + минус.",
        uiScaleToast: (size) => `Размер интерфейса: ${size}`,
        dataTitle: "История матчей",
        odTitle: "Быстрая загрузка истории",
        odPlaceholder: "Ключ OpenDota",
        odSave: "Сохранить",
        odGet: "Получить ключ на opendota.com",
        odClear: "Удалить ключ",
        odHintOff: "Историю ваших матчей приложение берёт с OpenDota — бесплатного сайта статистики Доты. Без ключа всё работает, просто медленнее. Бесплатный ключ с opendota.com ускорит загрузку; он хранится только на этом компьютере.",
        odHintOn: (hint) => `Ключ ${hint} сохранён: матчи загружаются быстрее.`,
        odHintEnv: "Ключ уже задан в файле настроек приложения.",
        odBad: "Это не похоже на ключ OpenDota.",
        appTitle: "Основное",
        service: "Тренер",
        serviceStates: { running: "работает", starting: "запускается…", stopping: "останавливается…", stopped: "остановлен" },
        status: {
          loadingTitle: "Запускаем тренера…",
          loadingHint: "Обычно это пара секунд.",
          backendDownTitle: "Тренер остановлен",
          backendDownHint: "Пока он остановлен, подсказок не будет. Нажмите «Запустить» — это пара секунд.",
          gsiErrorTitle: "Не получилось подключиться к Доте",
          gsiErrorHint: "Нет доступа к папке Доты. Укажите папку игры вручную.",
          noDotaTitle: "Дота не найдена",
          noDotaHint: "Не нашли Dota 2 в Steam. Укажите папку игры — остальное приложение сделает само.",
          noGsiTitle: "Подключите Доту",
          noGsiHint: "Нажмите «Подключить»: приложение положит в папку Доты маленький файл, через который игра сообщает тренеру, что происходит в матче.",
          notRunningTitle: "Дота не запущена",
          notRunningHint: "Запустите Dota 2 — тренер подключится сам. Это окно можно закрыть.",
          connectedTitle: "Связь с Дотой есть, ждём матч",
          noDataTitle: "Дота запущена, данных от неё пока нет",
          waitingHintConnected: "Подсказки начнутся, как только стартует матч с вашим героем.",
          waitingHintNoData: "Если матч уже идёт, перезапустите Доту: к тренеру она подключается только при запуске.",
          launchOptionTitle: "Дота не передаёт данные игры",
          launchOptionHint: "Для этого Доте нужен параметр запуска. В Steam: правой кнопкой по Dota 2 → Свойства → Параметры запуска, вставьте -gamestateintegration (кнопка его скопирует) и перезапустите игру.",
          inGameTitle: (hero, clock) => `В игре: ${[hero, clock].filter(Boolean).join(", ")}`,
          inGameHint: "Подсказки появляются поверх игры, пока окно Доты активно.",
          inGameOverlayOff: "Подсказки поверх игры выключены — они видны только здесь.",
          demoTitle: (preset) => `Демо-повтор${preset ? `: ${preset}` : ""}`,
          demoHint: "Оверлей показывает подсказки из записанного матча.",
          fullscreenTitle: "Подсказки не видны из-за полноэкранного режима",
          fullscreenHint:
            "Дота запущена в эксклюзивном полноэкранном режиме — поверх него окна не рисуются. В Доте: Настройки → Видео → режим экрана «Окно без рамки» (Borderless window). Или включите голос в «Настройки → Советы» — его слышно в любом режиме."
        },
        actions: {
          start: "Запустить тренера",
          install: "Подключить",
          chooseDota: "Указать папку Доты",
          fullscreenSeen: "Подсказки видны",
          copyLaunchOption: "Скопировать параметр",
          copied: "Скопировано"
        },
        matchTitle: "Текущий матч",
        coverageSafety: "Полные подсказки — для 64 героев (керри, мид, хардлайн, саппорты); на этом герое тренер подсказывает по выживанию, таймерам карты и роли.",
        coverageSupport: "Советы саппорта: свои спасения, драки и цели, стаки, пулы, варды и спасающие предметы. Без советов по фарму и предметам — золото достаётся корам.",
        statHero: "Герой",
        statClock: "Время матча",
        statStage: "Этап",
        statData: "Связь с игрой",
        dataFresh: (s) => `${s} с назад`,
        dataFreshNow: "только что",
        matchEmptyTitle: "Матч не идёт",
        matchEmptyHint: "Герой и время появятся здесь, когда начнётся матч.",
        offlineTitle: "Тренер не запущен",
        offlineHint: "Запустите его, чтобы видеть здесь свой матч.",
        adviceTitle: "Последние подсказки",
        adviceWhy: "Почему этот совет?",
        adviceEmptyTitle: "Подсказок пока нет",
        adviceEmptyHint: "Здесь появятся подсказки, которые показывались поверх игры.",
        priority: { high: "срочно", urgent: "срочно", medium: "важно", low: "совет", safe: "спокойно" },
        stages: { laning: "Линии", "post-laning": "После линий", macro: "Середина и конец игры" },
        overlayTitle: "Карточка с подсказками",
        overlayShow: "Показывать подсказки поверх игры",
        overlayReason: {
          off: "Выключено",
          positioning: "Показан, чтобы его можно было переместить",
          demo: "Показывает демо-повтор",
          no_tracking: "Всегда виден: на этой системе приложение не видит, открыта ли Дота",
          dota_not_running: "Появится в матче поверх Доты",
          dota_not_focused: "Скрыт, пока Дота в фоне",
          no_match: "Появится, когда начнётся матч",
          in_game: "Сейчас на экране"
        },
        overlayPosition: "Где на экране",
        positionHint: "В стороне от миникарты и панели героя",
        positionCustom: "Своё положение — выберите вариант, чтобы вернуть",
        posLeft: "Слева",
        posRight: "Справа",
        posBottom: "Снизу",
        overlaySize: "Размер карточки",
        overlaySizeHint: "Крупнее — для больших экранов и высокого разрешения",
        overlayTimers: "Полоса таймеров",
        skillArrowsTitle: "Стрелки над навыками",
        skillArrowsCalibrate: "Подправить",
        skillArrowsHint: {
          on: "Когда есть очко навыка, стрелка показывает на способность прямо на панели Доты и сама находит иконки. «Подправить» — если промахивается.",
          manual: "Включено, со своей рамкой. «Подправить» → «Автоматически» вернёт поиск иконок самой стрелкой.",
          off: "Выключено. Карточка всё равно называет способность."
        },
        overlayTimersHint: "Всегда под карточкой: сколько осталось до ближайших рун, стаков, Рошана и Аегиса для вашей роли",
        overlayCompact: "Короткие подсказки",
        overlayCompactHint: "Только что делать, без объяснения: меньше читать во время драки",
        hotkeysTitle: "Горячие клавиши",
        hotkeysGame: "В игре",
        hotkeysApp: "В этом окне",
        hotkeyTabs: "Главная, Матчи, Прогресс, Профиль, Настройки",
        hotkeyBack: "Из разбора матча обратно туда, откуда его открыли",
        hotkeyHistory: "Назад / вперёд по открытым страницам (и боковые кнопки мыши)",
        hotkeyFind: "В «Настройках»: найти настройку",
        hotkeyPalette: "Найти вкладку, матч, настройку или действие",
        findAnything: "Найти…",
        hotkeyZoom: "Интерфейс крупнее / мельче, Ctrl+0 — обратно 100 %",
        hotkeyNeighbour: "В разборе матча: матч выше / ниже в списке (новее / старее, если список не отсортирован)",
        hotkeyHelp: "Этот список клавиш, с любой вкладки",
        hotkeyToggle: "Включить или выключить карточку с подсказками",
        hotkeyRepeat: "Показать (и озвучить) последний совет ещё раз",
        hotkeyMute: "Без подсказок на 5 минут",
        hotkeyMove: "Открепить карточку, чтобы перетащить; ещё раз — закрепить",
        hotkeyPlace: "Карточка слева / справа / снизу",
        sizeSmall: "Мелкий",
        sizeNormal: "Обычный",
        sizeLarge: "Крупный",
        frequencyTitle: "Частота советов",
        frequencyCalm: "Реже",
        frequencyNormal: "Обычно",
        frequencyActive: "Чаще",
        roleTitle: "Ваша роль",
        roleAuto: "Авто",
        roleCarry: "Керри",
        roleMid: "Мид",
        roleOfflane: "Хардлайн",
        roleSupport: "Саппорт",
        roleHint: {
          auto: "Тренер сам поймёт по вашей линии в первые минуты. Выберите роль, если он ошибается",
          carry: "Таймеры и подсказки для керри",
          mid: "Руны и таймеры для мидера",
          offlane: "Святилища, лотосы и таймеры для хардлайнера",
          support: "Стаки, варды и руны для саппорта; советы про фарм выключены"
        },
        roleNames: { carry: "керри", mid: "мид", offlane: "хардлайн", support: "саппорт" },
        roleSource: {
          setting: "выбрана в настройках",
          lane: "по линии",
          history: "по вашим прошлым играм на герое",
          hero: "обычная для героя"
        },
        roleNote: (role, source) => `Роль: ${role}, ${source}.`,
        roleMismatch: (setting, seen) => `В «Ваша роль» стоит ${setting}, а играете вы как ${seen} — часть подсказок не в тему.`,
        roleSetAuto: "Поставить «Авто»",
        mapHintsTitle: "Таймеры карты",
        mapHintsHint: "Напоминание на карточке за 20 секунд до рун, святилищ, Торментора, стаков и вардов — только нужных вашей роли. Выключите — пропадёт и полоса таймеров",
        frequencyHint: {
          calm: "Вдвое больше пауза между советами; срочные не задерживаются",
          normal: "Обычные паузы между советами",
          active: "Короче паузы между советами; срочные как всегда"
        },
        voiceTitle: "Голос",
        voiceOff: "Выкл",
        voiceUrgent: "Срочные",
        voiceAll: "Все",
        voiceTest: "Прослушать",
        voiceHint: {
          off: "Советы только на экране, без озвучки",
          urgent: "Озвучивает срочные советы; слышно даже в полноэкранном режиме. Ctrl+Alt+R — повторить",
          all: "Озвучивает все советы; слышно даже в полноэкранном режиме. Ctrl+Alt+R — повторить"
        },
        voiceNoVoice: "В Windows нет русского голоса: Параметры → Время и язык → Речь → Добавить голоса",
        voiceSample: "Отходите: противника не видно на карте.",
        overlayMove: "Переместить вручную",
        moveHint: "Покажет карточку, чтобы её можно было перетащить",
        moveActiveHint: "Перетащите карточку и нажмите «Готово»",
        moveStart: "Переместить",
        moveDone: "Готово",
        recordsTitle: "Хранить записи матчей неделю",
        recordsHint: "Всё, что игра присылала за матч, и все показанные советы хранятся на этом компьютере 7 дней. Любой матч можно сохранить файлом и отправить разработчику — хоть на следующий день. Без ников, Steam ID и чата.",
        recordsOff: "Выключено: матчи не записываются.",
        recordsEmpty: "Включено: следующий матч будет записан.",
        recordsCount: (n) => `Включено: записано матчей за неделю — ${n}.`,
        recordsSave: "Сохранить файл",
        recordsSaved: "Сохранено в «Загрузки».",
        recordsFailed: "Не удалось сохранить файл.",
        recordsMinutes: (n) => `${n} мин`,
        recordsAdvice: (n) => `советов: ${n}`,
        statsTitle: "Помочь улучшить подсказки",
        statsHint: "Раз в день приложение отправляет анонимные счётчики: какие подсказки показывались и после каких предупреждений была смерть. Без героев, матчей, ника и ключей. По умолчанию выключено.",
        statsPreview: "Что отправляется (за сегодня)",
        statsTerms: "Хранится год.",
        statsOff: "Выключено: ничего не отправляется.",
        statsOn: "Включено: первая отправка — завтра, со счётчиками за сегодня.",
        statsSent: (date) => `Включено. Последняя отправка — ${date}.`,
        statsPreviewLoading: "Собираем…",
        statsPreviewFailed: "Тренер не запущен: показать нечего.",
        serverDelete: "Удалить мои данные на сервере",
        serverDeleteConfirm: "Точно удалить? Нажмите ещё раз",
        serverDeleted: "Удалено: отчёты о проблемах, ссылки «Поделиться» и статистика этого компьютера стёрты с сервера.",
        serverDeleteFailed: (code) => `Не получилось удалить (${code}): проверьте интернет и попробуйте ещё раз.`,
        discordTitle: "Статус в Discord",
        discordHint: "Друзья в Discord видят «Матч на Juggernaut · с тренером Wardly», пока запущена Дота",
        discordStates: {
          idle: "Появится, когда запущена Дота.",
          connecting: "Подключаюсь к Discord…",
          no_discord: "Discord не найден: откройте приложение Discord на этом компьютере (в браузере статус не работает).",
          connected: "Discord подключён. Статус появится, когда запущена Дота.",
          shown: "Статус показан в Discord. Друзья не видят? Discord → Настройки → Конфиденциальность активности → «Делиться своей активностью».",
          rejected: (error) => `Discord не принял статус: ${error}`
        },
        settingsMore: "Ещё настройки",
        settingsMoreHint: "Записи матчей, статистика, ключ OpenDota, неделя в Discord",
        settingsPageTitle: "Настройки",
        settingsPageSub: "Всё уже работает. Меняйте только то, что хочется.",
        settingsSearch: "Найти настройку",
        settingsSearchEmpty: "Ничего не нашлось. Попробуйте другое слово, например «голос», «размер» или «ключ».",
        settingsSearchClear: "Показать все настройки",
        zoneNow: "Сейчас",
        zoneNowHint: "Текущий матч и подсказки в нём",
        zoneHistory: "Последние матчи",
        zoneHistoryHint: "Откройте матч, чтобы увидеть разбор",
        zoneWeek: "Ваша неделя",
        zoneWeekHint: "Последние семь дней против семи до них",
        zoneAllMatches: "Все матчи",
        zoneGame: "В игре",
        zoneGameHint: "Что вы видите и слышите во время матча",
        zoneData: "После матча",
        zoneDataHint: "Разбор каждого матча простыми словами от ИИ-тренера",
        zoneApp: "Приложение",
        zoneAppHint: "Язык, автозапуск, обновления",
        weeklyTitle: "Неделя в Discord",
        weeklyHint:
          "Каждый понедельник матчи, результаты и средняя оценка за неделю приходят в канал вашего сервера Discord. Для этого нужна ссылка канала (вебхук): в Discord откройте настройки канала → Интеграция → Вебхуки → Новый вебхук → Копировать URL вебхука и вставьте её сюда.",
        weeklyInputLabel: "Ссылка вебхука",
        weeklyConnect: "Подключить",
        weeklySendNow: "Отправить сейчас",
        weeklyDisconnect: "Отключить",
        weeklySending: "Отправляю…",
        weeklyConnected: (hint) => `Подключено (${hint}). Неделя приходит в Discord каждый понедельник.`,
        weeklySent: (date) => `Последняя отправка: ${date}.`,
        weeklyEmpty: (date) => `${date}: за ту неделю матчей не было, ничего не отправлено.`,
        weeklyNoMatchesNow: "За последние семь дней матчей нет: отправлять пока нечего.",
        weeklyErrors: {
          bad_url: "Это не ссылка вебхука Discord: она начинается с https://discord.com/api/webhooks/.",
          webhook_gone: "Вебхук удалён в Discord: создайте новый и подключите заново.",
          rate_limited: "Discord просит подождать: попробуйте через минуту.",
          offline: "Нет связи с Discord: проверьте интернет.",
          backend_down: "Тренер ещё не запущен: попробуйте через минуту.",
          busy: "Уже отправляю…",
          fallback: "Не удалось отправить: попробуйте позже."
        },
        autostart: "Автозапуск с Windows",
        autostartOn: "Wardly сам откроется при включении компьютера и будет тихо ждать возле часов. Так вы не забудете запустить его перед игрой.",
        autostartOff: "Сейчас выключено: Wardly нужно открывать самому перед игрой. Включите — и он будет сам запускаться с компьютером и тихо ждать возле часов.",
        autostartUnavailable: "Доступно в установленном приложении",
        updates: "Обновления",
        updateCheck: "Проверить",
        updateInstall: "Перезапустить и обновить",
        updateHint: {
          disabled: (v) => `Версия ${v} · обновления работают в установленном приложении`,
          idle: (v) => `Версия ${v} · обновляется само`,
          checking: (v) => `Версия ${v} · проверяем…`,
          "up-to-date": (v) => `Версия ${v} · последняя`,
          downloading: (v, next, pct) => `Загружается ${next}… ${pct}%`,
          ready: (v, next) => `Версия ${next} загружена. Установится сама, когда Дота будет закрыта.`,
          blocked: (v, next) => `Версия ${next} загружена. Установится после выхода из Доты.`,
          error: (v) => `Версия ${v} · не удалось проверить обновления`
        },
        whatsNewTitle: (version) => `Что нового в ${version}`,
        whatsNewAlso: (version) => `Также в ${version}`,
        whatsNewOk: "Понятно",
        inviteTitle: "Нравится Wardly?",
        inviteText: "Скинь ссылку другу: приложение бесплатное, а играя вместе, проще следовать подсказкам.",
        inviteCopy: "Скопировать ссылку",
        inviteLater: "Не сейчас",
        inviteCopied: "Ссылка скопирована",
        tour: {
          next: "Дальше",
          back: "Назад",
          skip: "Пропустить",
          done: "Играть",
          count: (i, n) => `${i} из ${n}`,
          steps: {
            welcome: {
              title: "Привет! Это Wardly",
              text: "Тренер смотрит матч вместе с вами: короткие советы поверх игры и голосом, а после матча — разбор, что исправить. За пару минут покажем, как выглядят советы, что где лежит и что настроить."
            },
            card: {
              title: "Как выглядит совет",
              text: "Карточка поверх игры. Крупная строка — что сделать сейчас, ниже — почему. «Срочно» с красной точкой — делайте сразу: мало HP, рядом смерть. Остальное — подсказки, которые можно сделать в ближайший удобный момент. Карточка видна только в матче, когда Дота на переднем плане."
            },
            mapline: {
              title: "Таймеры и подсказки по карте",
              text: "Руны, стаки, Рошан, Торментор, пропавший с линии соперник, невложенное очко навыка — приходят карточкой «Карта» с временем до события. Под карточкой полоса таймеров отсчитывает ближайшие события."
            },
            plan: {
              title: "План, экран смерти и итог",
              text: "До горна карточка покажет план: сколько добить к 10:00, ключевой предмет и ваш фокус. Пока герой мёртв — почему вы погибли и что купить, а на экране счёта — оценку матча и одну вещь, которую стоит исправить."
            },
            status: {
              title: "Строка состояния",
              text: "Что происходит сейчас: найдена ли Дота, идут ли от неё данные, начался ли матч. Если нужно что-то сделать, справа будет кнопка."
            },
            setup: {
              title: "Первый запуск",
              text: "Что уже настроено и что осталось. Большинство шагов выполняются сами. Если Дота попросит, добавьте в параметры запуска -gamestateintegration (кнопка скопирует). Первый матч с приложением закроет список."
            },
            match: {
              title: "Текущий матч",
              text: "Ваш герой, время матча и советы тренера. Под каждым советом «Почему этот совет?» — что тренер увидел. Во время матча советы появляются поверх игры, сюда смотреть не нужно."
            },
            matches: {
              title: "Матчи",
              text: "Каждый матч с разбором: оценки по областям, где вы погибали, тайминги предметов и что исправить в первую очередь. Разбор готов через минуту-две после матча."
            },
            progress: {
              title: "Прогресс",
              text: "Как вы играете в последних матчах: тренды, повторяющиеся ошибки, линии и герои. Выберите одну проблему фокусом — каждый следующий матч покажет, получилось ли её исправить."
            },
            profile: {
              title: "Профиль и друзья",
              text: "График рейтинга, уровень и награды за матчи с приложением. За игры начисляются искры — на них покупаются рамки, баннеры и титулы. Обменяйтесь кодами с другом, чтобы видеть друг друга в таблице."
            },
            settings: {
              title: "Карточка в игре",
              text: "Где карточка с советом стоит поверх игры и какого она размера. Её можно перетащить руками."
            },
            voice: {
              title: "Советы и голос",
              text: "Как часто тренер подсказывает, ваша роль и голос. Роль лучше оставить на «Авто»: тренер сам поймёт её по линии. Голос читает советы вслух и работает даже в полноэкранном режиме, где карточку не видно."
            },
            ai: {
              title: "ИИ-тренер (по желанию)",
              text: "С бесплатным ключом Google AI Studio в разборе появится текстовый разбор от тренера, и про любой матч можно будет задать вопрос. Всё остальное работает и без ключа."
            },
            help: {
              title: "Помощь",
              text: "Отсюда обучение открывается снова. Если что-то не работает, «Сообщить о проблеме» отправит разработчику отчёт с тем, что присылала игра (без ключей и паролей)."
            },
            done: {
              title: "Всё готово",
              text: "Запустите Доту и начните матч — первая подсказка появится сама, а разбор будет готов через минуту-две после игры. Удачи!"
            }
          }
        },
        summaryTitle: "Сводка",
        sessionTitle: "Итог вечера",
        sessionHide: "Скрыть",
        tourTitle: "Как пользоваться Wardly",
        tourHint: "Короткая экскурсия по приложению, на минуту",
        tourStart: "Показать",
        whatsNew: whatsNew.texts("ru"),
        setupTitle: "Первый запуск",
        setupPreviewTitle: "Так это выглядит в игре",
        setupPreviewText: "Подсказка появляется поверх игры, когда она нужна, а после матча тренер пишет разбор с оценкой и одним главным, что исправить.",
        setupHide: "Скрыть",
        setupCount: (done, total) => `${done} из ${total}`,
        setup: {
          service: ["Тренер запущен", "Запускается вместе с приложением. Если остановился — перезапустите приложение."],
          dota: ["Dota 2 найдена", "Игры нет в библиотеках Steam — укажите папку игры."],
          gsi: ["Приложение подключено к Доте", "Маленький файл в папке Доты: через него игра сообщает тренеру, что происходит в матче."],
          launch: ["Дота передаёт данные матча", "Для этого нужен параметр запуска. В Steam: правой кнопкой по Dota 2 → Свойства → Параметры запуска, вставьте -gamestateintegration."],
          data: ["Дота связалась с тренером", "Запустите Dota 2 (или перезапустите, если она была открыта) и зайдите в любой матч, можно с ботами."],
          account: ["Аккаунт Steam привязан", "Привяжется сам в первом матче, или укажите его на вкладке «Матчи»."],
          ai: ["ИИ-тренер (по желанию)", "С бесплатным ключом Google ИИ напишет разбор каждого матча простыми словами."]
        },
        setupActions: { dota: "Указать папку", gsi: "Подключить", launch: "Скопировать", account: "Привязать", ai: "Настроить" },
        reportTitle: "Сообщить о проблеме",
        reportHint: "Что-то не работает? Нажмите «Сообщить» и опишите в двух словах: разработчик получит журнал приложения. Ключи и пароли из него вырезаются.",
        reportSave: "Сохранить в файл вместо отправки",
        backupTitle: "Запасная копия в файле",
        backupHint: "Сохраняет все матчи и разборы в один файл — например, перед переустановкой Windows. Потом его можно открыть в Wardly на любом компьютере. Ключи в файл не попадают.",
        backupExport: "Сохранить в файл",
        backupImport: "Открыть файл",
        backupSaved: (count, file) => `Сохранено матчей: ${count}. Файл ${file}`,
        backupLoaded: (added, linked) => `Загружено новых матчей: ${added}${linked ? ", аккаунт привязан" : ""}. Ничего не перезаписано.`,
        backupNotBackup: "Это не файл истории Wardly или в нём повреждены данные. Данные из файла не сохранены.",
        backupNewer: "Файл сделан более новой версией: сначала обновите приложение.",
        backupRestoreFailed: "Не удалось восстановить историю. Данные из файла не сохранены; проверьте диск и повторите попытку.",
        backupFailed: "Не получилось: тренер не запущен или диск недоступен.",
        transferTitle: "Перенос на другой компьютер",
        zoneMyData: "Ваши матчи",
        zoneMyDataHint: "Чтобы история не потерялась при смене компьютера",
        zoneHelp: "Помощь",
        zoneHelpHint: "Как пользоваться приложением и что делать, если что-то сломалось",
        transferIntro: "Поставили Wardly на новый компьютер? Перенесите туда свои матчи и разборы — это займёт минуту.",
        transferStep1: "Здесь нажмите «Получить код».",
        transferStep2: "На новом компьютере: Wardly → Настройки → «Перенос на другой компьютер» → «У меня есть код» — и введите его.",
        transferHave: "У меня есть код",
        transferHint: "Код действует 15 минут. Матчи передаются в зашифрованном виде, ключи не переносятся.",
        transferSend: "Получить код",
        transferReceive: "Загрузить",
        transferInputLabel: "Код с другого компьютера",
        transferSending: "Шифрую и отправляю…",
        transferReady: (matches, time) => `Код действует до ${time}. Введите его на новом компьютере (матчей: ${matches}).`,
        transferReceiving: "Скачиваю и расшифровываю…",
        transferErrors: {
          bad_code: "Проверьте код: три группы по четыре буквы и цифры, как на другом компьютере.",
          not_found: "По этому коду ничего нет: он устарел (15 минут) или история уже загружена. Получите новый код.",
          too_big: "История слишком большая для переноса по коду: сохраните её в файл.",
          rate_limited: "Слишком много попыток: подождите час или перенесите файлом.",
          disabled: "Перенос по коду сейчас выключен: воспользуйтесь файлом.",
          not_backup: "Код открыл что-то, что не похоже на историю Wardly.",
          offline: "Нет связи с сервером: проверьте интернет.",
          fallback: "Не получилось: попробуйте ещё раз или перенесите файлом."
        },
        reportSaving: "Собираем…",
        reportSaved: (name) => `Сохранено: ${name}. Отправьте этот файл разработчику.`,
        reportFailed: "Не удалось сохранить файл",
        reportSend: "Сообщить",
        reportNoteLabel: "Что случилось? (необязательно)",
        reportNotePlaceholder: "Например: в матче не видно подсказок",
        reportPreview: "Что будет отправлено",
        reportPreviewLoading: "Собираем отчёт…",
        reportTerms: "Ключи вырезаны. Отчёт хранится 180 дней.",
        reportPrivacy: "Конфиденциальность",
        reportSendNow: "Отправить",
        reportCancel: "Отмена",
        reportSending: "Отправляем…",
        reportSentId: (id) => `Отправлено. Номер отчёта: ${id}. Назовите его, если будете писать разработчику.`,
        reportQueued: "Сейчас нет интернета. Отчёт отправится сам позже.",
        reportQueuedCount: (count) => `Ждут отправки: ${count}`,
        reportLast: (id) => `Последний отчёт: ${id}`,
        reportRefused: (name) =>
          name ? `Сервер не принял отчёт. Вместо этого сохранён файл: ${name}.` : "Сервер не принял отчёт.",
        devTitle: "Для разработчика",
        devHint: "Технические инструменты: процесс тренера, связь с игрой, журналы. Для игры не нужны",
        factBackend: "Сервис",
        factDota: "Дота",
        factOverlay: "Оверлей",
        factDemo: "Демо",
        factRecording: "Запись",
        factGsiConfig: "Конфиг GSI",
        factMode: "Режим",
        groupBackend: "Сервис",
        startBackend: "Запустить",
        restartBackend: "Перезапустить",
        stopBackend: "Остановить",
        showOverlay: "Показать оверлей",
        hideOverlay: "Скрыть оверлей",
        hotkeys: "Ctrl+Alt+O вкл/выкл · Ctrl+Alt+L переместить · Ctrl+Alt+M тишина 5 мин · Ctrl+Alt+R повторить совет · Ctrl+Alt+1/2/3 слева/справа/снизу · Ctrl+Alt+D отладка",
        groupGsi: "Конфиг GSI",
        gsiPathPlaceholder: "Своя папка gamestate_integration (необязательно)",
        chooseFolder: "Выбрать",
        checkGsi: "Проверить",
        installGsi: "Установить",
        gsiPath: (p, e) => `Конфиг: ${p}${e ? `\nАдрес: ${e}` : ""}`,
        gsiPathMissing: "Конфиг не найден. Выберите папку gamestate_integration и установите.",
        gsiEndpoint: (e) => (e ? `Адрес: ${e}` : "Адрес: ждём порт сервиса…"),
        groupLive: "Живой GSI",
        kvConnection: "Связь",
        kvLast: "Данные",
        kvHero: "Герой",
        kvTime: "Время",
        kvStage: "Стадия",
        liveConnected: "подключено",
        liveWaiting: "ожидание / устарело",
        liveUnavailable: "сервис недоступен",
        liveAdvice: (a) => `Текущий совет: ${a}`,
        liveAdviceNone: "Текущий совет: пока нет",
        liveAdviceLast: (t) => `Текущий совет: последний в ${t}`,
        liveMissing: (m) => `Не хватает полей: ${m}`,
        none: "нет",
        checkLive: "Проверить",
        startRecording: "Записать",
        stopRecording: "Остановить запись",
        openRecords: "Записи",
        groupDemo: "Демо-повтор",
        demoHint: "Проигрывает записанные состояния матча в сервис; оверлей виден без Доты.",
        demoBusy: "Демо уже идёт. Сначала остановите его.",
        runDemo: "Запустить демо",
        presetPl: "Phantom Lancer 20–30",
        presetJugg: "Juggernaut 10–20",
        deepReview: "Deep Review",
        stopDemo: "Остановить",
        openResults: "Результаты",
        groupLogs: "Логи",
        groupOps: "Состояние операций",
        opsHint: "Фоновые очереди, сохранение сыгранного матча, путь живого GSI и свежесть данных. Только числа и время.",
        opsRefresh: "Обновить",
        opsAllGood: "Всё в порядке.",
        opsUnavailable: "Сервис не ответил.",
        opsJobs: "Задачи истории",
        opsAi: "Задачи ИИ-тренера",
        opsMatch: "Сохранение матча",
        opsGsi: "Путь живого GSI",
        opsData: "Данные",
        opsQueueIdle: (done) => `простаивает · выполнено ${done}`,
        opsQueueIdleFailed: (done, failed, at) => `простаивает · выполнено ${done}, с ошибкой ${failed}${at ? ` (последняя в ${at})` : ""}`,
        opsQueueRunning: (kind, seconds, queued) => `выполняется ${kind} ${seconds} с${queued ? ` · ждут ${queued}` : ""}`,
        opsQueueWaiting: (queued, seconds) => `ждут ${queued} · самая старая ${seconds} с`,
        opsQueueLater: (queued, seconds) => `запланировано ${queued} · следующая через ${seconds} с`,
        opsMatchPending: (n) => `сыгранных матчей ждут сохранения: ${n}`,
        opsMatchSaved: (at) => `последний матч сохранён в ${at}`,
        opsMatchNone: "в этом запуске матчи не заканчивались",
        opsGsiNone: "в этом запуске пакетов не было",
        opsGsiTimes: (count, p50, p95, failed) => `пакетов ${count} · p50 ${p50 ?? "—"} мс · p95 ${p95 ?? "—"} мс${failed ? ` · ошибок сохранения ${failed}` : ""}`,
        opsDataLine: (state, at, builds, age) => {
          const sync = { done: "матчи обновлены", error: "обновление матчей не удалось", running: "матчи обновляются", queued: "матчи обновляются" }[state] || "матчи не обновлялись";
          return `${sync}${at ? ` в ${at}` : ""} · сборки ${builds ? `от ${builds}${age != null ? ` (${age} дн.)` : ""}` : "отсутствуют"}`;
        },
        opsWarn_jobs_waiting: "Задачи истории ждут в очереди дольше 2 минут.",
        opsWarn_jobs_running_long: "Задача истории выполняется дольше 5 минут.",
        opsWarn_jobs_no_worker: "Задачи истории в очереди, но их некому выполнять.",
        opsWarn_ai_jobs_waiting: "Задачи ИИ-тренера ждут в очереди дольше 2 минут.",
        opsWarn_ai_jobs_running_long: "Задача ИИ-тренера выполняется дольше 5 минут.",
        opsWarn_ai_jobs_no_worker: "Задачи ИИ-тренера в очереди, но их некому выполнять.",
        opsWarn_match_not_saved: "Сыгранный матч пока не удалось сохранить; он хранится и будет сохранён повторно.",
        opsWarn_recovery_write_failed: "Не удалось записать файл восстановления матча.",
        opsWarn_gsi_persistence_failed: "Сохранение данных живого GSI хотя бы раз не удалось.",
        opsWarn_gsi_slow: "Путь живого GSI медленный (p95 больше 250 мс).",
        opsWarn_sync_failed: "Последнее обновление матчей не удалось.",
        opsWarn_builds_stale: "Встроенным сборкам предметов больше трёх недель.",
        logClean: "Кратко",
        logVerbose: "Подробно",
        copyLogs: "Копировать",
        clearLogs: "Очистить",
        openLogs: "Папка логов",
        dotaStates: { not_found: "не найдена", waiting: "ждём матч", in_game: "в игре" },
        gsiConfigStates: { installed: "установлен", "not found": "не найден", error: "ошибка", unknown: "неизвестно" },
        modes: { "Live GSI": "Живой GSI", "Replay Demo": "Демо-повтор" },
        on: "вкл",
        off: "выкл",
        shown: "на экране",
        hidden: "скрыт",
        running: "идёт",
        stopped: "остановлено"
      }
    };
    return I18N;
  }
  const api = {create};
  if (typeof module !== "undefined" && module.exports) module.exports = api;
  else window.WardlyAppTexts = api;
})();
