// Generated by backend/scripts/build_dota_data.py - do not edit by hand.
// Hero id -> [name, picture key]; item name -> picture key.
window.DotaData = {
"heroes": {
"1": [
"Anti-Mage",
"antimage"
],
"2": [
"Axe",
"axe"
],
"3": [
"Bane",
"bane"
],
"4": [
"Bloodseeker",
"bloodseeker"
],
"5": [
"Crystal Maiden",
"crystal_maiden"
],
"6": [
"Drow Ranger",
"drow_ranger"
],
"7": [
"Earthshaker",
"earthshaker"
],
"8": [
"Juggernaut",
"juggernaut"
],
"9": [
"Mirana",
"mirana"
],
"10": [
"Morphling",
"morphling"
],
"11": [
"Shadow Fiend",
"nevermore"
],
"12": [
"Phantom Lancer",
"phantom_lancer"
],
"13": [
"Puck",
"puck"
],
"14": [
"Pudge",
"pudge"
],
"15": [
"Razor",
"razor"
],
"16": [
"Sand King",
"sand_king"
],
"17": [
"Storm Spirit",
"storm_spirit"
],
"18": [
"Sven",
"sven"
],
"19": [
"Tiny",
"tiny"
],
"20": [
"Vengeful Spirit",
"vengefulspirit"
],
"21": [
"Windranger",
"windrunner"
],
"22": [
"Zeus",
"zuus"
],
"23": [
"Kunkka",
"kunkka"
],
"25": [
"Lina",
"lina"
],
"26": [
"Lion",
"lion"
],
"27": [
"Shadow Shaman",
"shadow_shaman"
],
"28": [
"Slardar",
"slardar"
],
"29": [
"Tidehunter",
"tidehunter"
],
"30": [
"Witch Doctor",
"witch_doctor"
],
"31": [
"Lich",
"lich"
],
"32": [
"Riki",
"riki"
],
"33": [
"Enigma",
"enigma"
],
"34": [
"Tinker",
"tinker"
],
"35": [
"Sniper",
"sniper"
],
"36": [
"Necrophos",
"necrolyte"
],
"37": [
"Warlock",
"warlock"
],
"38": [
"Beastmaster",
"beastmaster"
],
"39": [
"Queen of Pain",
"queenofpain"
],
"40": [
"Venomancer",
"venomancer"
],
"41": [
"Faceless Void",
"faceless_void"
],
"42": [
"Wraith King",
"skeleton_king"
],
"43": [
"Death Prophet",
"death_prophet"
],
"44": [
"Phantom Assassin",
"phantom_assassin"
],
"45": [
"Pugna",
"pugna"
],
"46": [
"Templar Assassin",
"templar_assassin"
],
"47": [
"Viper",
"viper"
],
"48": [
"Luna",
"luna"
],
"49": [
"Dragon Knight",
"dragon_knight"
],
"50": [
"Dazzle",
"dazzle"
],
"51": [
"Clockwerk",
"rattletrap"
],
"52": [
"Leshrac",
"leshrac"
],
"53": [
"Nature's Prophet",
"furion"
],
"54": [
"Lifestealer",
"life_stealer"
],
"55": [
"Dark Seer",
"dark_seer"
],
"56": [
"Clinkz",
"clinkz"
],
"57": [
"Omniknight",
"omniknight"
],
"58": [
"Enchantress",
"enchantress"
],
"59": [
"Huskar",
"huskar"
],
"60": [
"Night Stalker",
"night_stalker"
],
"61": [
"Broodmother",
"broodmother"
],
"62": [
"Bounty Hunter",
"bounty_hunter"
],
"63": [
"Weaver",
"weaver"
],
"64": [
"Jakiro",
"jakiro"
],
"65": [
"Batrider",
"batrider"
],
"66": [
"Chen",
"chen"
],
"67": [
"Spectre",
"spectre"
],
"68": [
"Ancient Apparition",
"ancient_apparition"
],
"69": [
"Doom",
"doom_bringer"
],
"70": [
"Ursa",
"ursa"
],
"71": [
"Spirit Breaker",
"spirit_breaker"
],
"72": [
"Gyrocopter",
"gyrocopter"
],
"73": [
"Alchemist",
"alchemist"
],
"74": [
"Invoker",
"invoker"
],
"75": [
"Silencer",
"silencer"
],
"76": [
"Outworld Destroyer",
"obsidian_destroyer"
],
"77": [
"Lycan",
"lycan"
],
"78": [
"Brewmaster",
"brewmaster"
],
"79": [
"Shadow Demon",
"shadow_demon"
],
"80": [
"Lone Druid",
"lone_druid"
],
"81": [
"Chaos Knight",
"chaos_knight"
],
"82": [
"Meepo",
"meepo"
],
"83": [
"Treant Protector",
"treant"
],
"84": [
"Ogre Magi",
"ogre_magi"
],
"85": [
"Undying",
"undying"
],
"86": [
"Rubick",
"rubick"
],
"87": [
"Disruptor",
"disruptor"
],
"88": [
"Nyx Assassin",
"nyx_assassin"
],
"89": [
"Naga Siren",
"naga_siren"
],
"90": [
"Keeper of the Light",
"keeper_of_the_light"
],
"91": [
"Io",
"wisp"
],
"92": [
"Visage",
"visage"
],
"93": [
"Slark",
"slark"
],
"94": [
"Medusa",
"medusa"
],
"95": [
"Troll Warlord",
"troll_warlord"
],
"96": [
"Centaur Warrunner",
"centaur"
],
"97": [
"Magnus",
"magnataur"
],
"98": [
"Timbersaw",
"shredder"
],
"99": [
"Bristleback",
"bristleback"
],
"100": [
"Tusk",
"tusk"
],
"101": [
"Skywrath Mage",
"skywrath_mage"
],
"102": [
"Abaddon",
"abaddon"
],
"103": [
"Elder Titan",
"elder_titan"
],
"104": [
"Legion Commander",
"legion_commander"
],
"105": [
"Techies",
"techies"
],
"106": [
"Ember Spirit",
"ember_spirit"
],
"107": [
"Earth Spirit",
"earth_spirit"
],
"108": [
"Underlord",
"abyssal_underlord"
],
"109": [
"Terrorblade",
"terrorblade"
],
"110": [
"Phoenix",
"phoenix"
],
"111": [
"Oracle",
"oracle"
],
"112": [
"Winter Wyvern",
"winter_wyvern"
],
"113": [
"Arc Warden",
"arc_warden"
],
"114": [
"Monkey King",
"monkey_king"
],
"119": [
"Dark Willow",
"dark_willow"
],
"120": [
"Pangolier",
"pangolier"
],
"121": [
"Grimstroke",
"grimstroke"
],
"123": [
"Hoodwink",
"hoodwink"
],
"126": [
"Void Spirit",
"void_spirit"
],
"128": [
"Snapfire",
"snapfire"
],
"129": [
"Mars",
"mars"
],
"131": [
"Ringmaster",
"ringmaster"
],
"135": [
"Dawnbreaker",
"dawnbreaker"
],
"136": [
"Marci",
"marci"
],
"137": [
"Primal Beast",
"primal_beast"
],
"138": [
"Muerta",
"muerta"
],
"145": [
"Kez",
"kez"
],
"155": [
"Largo",
"largo"
]
},
"items": {
"Abyssal Blade": "abyssal_blade",
"Aegis of the Immortal": "aegis",
"Aeon Disk": "aeon_disk",
"Aether Lens": "aether_lens",
"Aghanim's Shard": "aghanims_shard",
"Aghanim's Shard - Consumable": "aghanims_shard_roshan",
"Ancient Guardian": "ancient_guardian",
"Drum of Endurance": "ancient_janggo",
"Khanda": "angels_demise",
"Apex": "apex",
"Arcane Blink": "arcane_blink",
"Arcane Boots": "arcane_boots",
"Arcane Ring": "arcane_ring",
"Armlet of Mordiggian": "armlet",
"Ascetic's Cap": "ascetic_cap",
"Ash Legion Shield": "ash_legion_shield",
"Assault Cuirass": "assault",
"Aviana's Feather": "avianas_feather",
"Ballista": "ballista",
"Skull Basher": "basher",
"Belt of Strength": "belt_of_strength",
"Battle Fury": "bfury",
"Black Grimoire\\n(Warlock)": "black_grimoire",
"Black King Bar": "black_king_bar",
"Blast Rig": "black_powder_bag",
"Blade Mail": "blade_mail",
"Blade of Alacrity": "blade_of_alacrity",
"Blades of Attack": "blades_of_attack",
"Orb of Blight": "blight_stone",
"Blink Dagger": "blink",
"Blitz Knuckles": "blitz_knuckles",
"Blood Grenade": "blood_grenade",
"Bloodstone": "bloodstone",
"Bloodthorn": "bloodthorn",
"Book of Shadows": "book_of_shadows",
"Boots of Speed": "boots",
"Boots of Bearing": "boots_of_bearing",
"Band of Elvenskin": "boots_of_elves",
"Bottle": "bottle",
"Bracer": "bracer",
"Iron Branch": "branches",
"Broadsword": "broadsword",
"Broom Handle": "broom_handle",
"Buckler": "buckler",
"Bullwhip": "bullwhip",
"Butterfly": "butterfly",
"Ceremonial Robe": "ceremonial_robe",
"Chainmail": "chainmail",
"Chasm Stone": "chasm_stone",
"Cheese": "cheese",
"Chipped Vest": "chipped_vest",
"Circlet": "circlet",
"Clarity": "clarity",
"Claymore": "claymore",
"Cloak": "cloak",
"Cloak of Flames": "cloak_of_flames",
"Clumsy Net": "clumsy_net",
"Conjurer's Catalyst": "conjurers_catalyst",
"Consecrated Wraps": "consecrated_wraps",
"Cornucopia": "cornucopia",
"Animal Courier": "courier",
"Craggy Coat": "craggy_coat",
"Crella's Crozier": "crellas_crozier",
"Crimson Guard": "crimson_guard",
"Crippling Crossbow": "crippling_crossbow",
"Crown": "crown",
"Eul's Scepter of Divinity": "cyclone",
"Dagger of Ristul": "dagger_of_ristul",
"Dagon": "dagon",
"Dandelion Amulet": "dandelion_amulet",
"Defiant Shell": "defiant_shell",
"Demon Edge": "demon_edge",
"Book of the Dead": "demonicon",
"Desolator": "desolator",
"Stygian Desolator": "desolator_2",
"Parasma": "devastator",
"Dezun Bloodrite": "dezun_bloodrite",
"Diadem": "diadem",
"Diffusal Blade": "diffusal_blade",
"Disperser": "disperser",
"Divine Regalia": "divine_regalia",
"Disgraced Regalia": "divine_regalia_broken",
"Dormant Curio": "dormant_curio",
"Doubloon": "doubloon",
"Dragon Lance": "dragon_lance",
"Dragon Scale": "dragon_scale",
"Duelist Gloves": "duelist_gloves",
"Dust of Appearance": "dust",
"Eaglesong": "eagle",
"Echo Sabre": "echo_sabre",
"Eldwurm's Edda": "eldwurms_edda",
"Elixir": "elixer",
"Elven Tunic": "elven_tunic",
"Enchanted Mango": "enchanted_mango",
"Enchanted Quiver": "enchanted_quiver",
"Enchanter's Bauble": "enchanters_bauble",
"Energy Booster": "energy_booster",
"Alert": "enhancement_alert",
"Audacious": "enhancement_audacious",
"Boundless": "enhancement_boundless",
"Brawny": "enhancement_brawny",
"Crude": "enhancement_crude",
"Unleashed": "enhancement_curious",
"Dominant": "enhancement_dominant",
"Evolved": "enhancement_evolved",
"Feverish": "enhancement_feverish",
"Fierce": "enhancement_fierce",
"Fleetfooted": "enhancement_fleetfooted",
"Greedy": "enhancement_greedy",
"Hulking": "enhancement_hulking",
"Keen-eyed": "enhancement_keen_eyed",
"Manic": "enhancement_manic",
"Mystical": "enhancement_mystical",
"Nimble": "enhancement_nimble",
"Quickened": "enhancement_quickened",
"Restorative": "enhancement_restorative",
"Thick": "enhancement_thick",
"Timeless": "enhancement_timeless",
"Titanic": "enhancement_titanic",
"Tough": "enhancement_tough",
"Vampiric": "enhancement_vampiric",
"Vast": "enhancement_vast",
"Vital": "enhancement_vital",
"Wise": "enhancement_wise",
"Essence Distiller": "essence_distiller",
"Essence Ring": "essence_ring",
"Eternal Shroud": "eternal_shroud",
"Ethereal Blade": "ethereal_blade",
"Ex Machina": "ex_machina",
"Eye of the Vizier": "eye_of_the_vizier",
"Faded Broach": "faded_broach",
"Faerie Fire": "faerie_fire",
"Falcon Blade": "falcon_blade",
"Fallen Sky": "fallen_sky",
"Healing Lotus": "famango",
"Healing Salve": "flask",
"Flayer's Bota": "flayers_bota",
"Flicker": "flicker",
"Fluffy Hat": "fluffy_hat",
"Flying Courier": "flying_courier",
"Vital Toadstool": "foragers_health",
"Forager's Kit": "foragers_kit",
"Tomo'kan Ringcap": "foragers_mana",
"Ironwood Nut": "foragers_stats",
"Force Boots": "force_boots",
"Arcanist's Armor": "force_field",
"Force Staff": "force_staff",
"Bag of Gold": "furion_gold_bag",
"Fusion Rune": "fusion_rune",
"Gale Guard": "gale_guard",
"Gauntlets of Strength": "gauntlets",
"Gem of True Sight": "gem",
"Ghost Scepter": "ghost",
"Giant's Maul": "giant_maul",
"Giant's Ring": "giants_ring",
"Glimmer Cape": "glimmer_cape",
"Gloves of Haste": "gloves",
"Gossamer Cape": "gossamer_cape",
"Great Healing Lotus": "great_famango",
"Daedalus": "greater_crit",
"Greater Faerie Fire": "greater_faerie_fire",
"Greater Healing Lotus": "greater_famango",
"Gris-Gris": "grisgris",
"Grove Bow": "grove_bow",
"Guardian Greaves": "guardian_greaves",
"Gleipnir": "gungir",
"Gunpowder Gauntlet": "gunpowder_gauntlets",
"Hand of Midas": "hand_of_midas",
"Harmonizer": "harmonizer",
"Harpoon": "harpoon",
"Havoc Hammer": "havoc_hammer",
"Headdress": "headdress",
"Heart of Tarrasque": "heart",
"Heaven's Halberd": "heavens_halberd",
"Witchbane": "heavy_blade",
"Helm of Iron Will": "helm_of_iron_will",
"Helm of the Dominator": "helm_of_the_dominator",
"Helm of the Overlord": "helm_of_the_overlord",
"Helm of the Undying": "helm_of_the_undying",
"Holy Locket": "holy_locket",
"Hood of Defiance": "hood_of_defiance",
"Hurricane Pike": "hurricane_pike",
"Hydra's Breath": "hydras_breath",
"Hyperstone": "hyperstone",
"Idol of Scree'auk": "idol_of_screeauk",
"Illusionist's Cape": "illusionsts_cape",
"Imp Claw": "imp_claw",
"Infused Raindrops": "infused_raindrop",
"Shadow Blade": "invis_sword",
"Iron Talon": "iron_talon",
"Ironwood Tree": "ironwood_tree",
"Javelin": "javelin",
"Jidi Pollen Bag": "jidi_pollen_bag",
"Kaya": "kaya",
"Kaya and Sange": "kaya_and_sange",
"Keen Optic": "keen_optic",
"Kobold Cup": "kobold_cup",
"Lance of Pursuit": "lance_of_pursuit",
"Crystalys": "lesser_crit",
"Morbid Mask": "lifesteal",
"Light Collector": "light_collector",
"Lotus Orb": "lotus_orb",
"Madstone Bundle": "madstone_bundle",
"Maelstrom": "maelstrom",
"Mage Slayer": "mage_slayer",
"Magic Stick": "magic_stick",
"Magic Wand": "magic_wand",
"Magnifying Monocle": "magnifying_monocle",
"Mana Draught": "mana_draught",
"Mango Tree": "mango_tree",
"Manta Style": "manta",
"Mantle of Intelligence": "mantle",
"Martyr's Plate": "martyrs_plate",
"Mask of Madness": "mask_of_madness",
"Medallion of Courage": "medallion_of_courage",
"Mekansm": "mekansm",
"Metamorphic Mandible": "metamorphic_mandible",
"Meteor Hammer": "meteor_hammer",
"Mind Breaker": "mind_breaker",
"Minotaur Horn": "minotaur_horn",
"Mirror Shield": "mirror_shield",
"Brigand's Blade": "misericorde",
"Mithril Hammer": "mithril_hammer",
"Mjollnir": "mjollnir",
"Monkey King Bar": "monkey_king_bar",
"Moon Shard": "moon_shard",
"Mercy & Grace": "muertas_gun",
"Tombstone": "mutation_tombstone",
"Fairy's Trinket": "mysterious_hat",
"Mystic Staff": "mystic_staff",
"Necronomicon": "necronomicon",
"Nemesis Curse": "nemesis_curse",
"Nether Shawl": "nether_shawl",
"Ninja Gear": "ninja_gear",
"Null Talisman": "null_talisman",
"Nullifier": "nullifier",
"Oblivion Staff": "oblivion_staff",
"Occult Bracelet": "occult_bracelet",
"Ocean Heart": "ocean_heart",
"Octarine Core": "octarine_core",
"Beloved Memory": "ofrenda",
"Forebearer's Fortune": "ofrenda_pledge",
"Scrying Shovel": "ofrenda_shovel",
"Ogre Axe": "ogre_axe",
"Ogre Seal Totem": "ogre_seal_totem",
"Orb of Corrosion": "orb_of_corrosion",
"Orb of Destruction": "orb_of_destruction",
"Orb of Frost": "orb_of_frost",
"Orb of Venom": "orb_of_venom",
"Orchid Malevolence": "orchid",
"Outworld Staff": "outworld_staff",
"Overwhelming Blink": "overwhelming_blink",
"Fae Grenade": "paintball",
"Paladin Sword": "paladin_sword",
"Magic Lamp": "panic_button",
"Partisan's Brand": "partisans_brand",
"Pavise": "pavise",
"Penta-Edged Sword": "penta_edged_sword",
"Perseverance": "pers",
"Phase Boots": "phase_boots",
"Philosopher's Stone": "philosophers_stone",
"Phoenix Ash": "phoenix_ash",
"Phylactery": "phylactery",
"Pipe of Insight": "pipe",
"Pirate Hat": "pirate_hat",
"Platemail": "platemail",
"Pocket Roshan": "pocket_roshan",
"Pocket Tower": "pocket_tower",
"Tumbler's Toy": "pogo_stick",
"Point Booster": "point_booster",
"Pollywog Charm": "polliwog_charm",
"Poor Man's Shield": "poor_mans_shield",
"Possessed Mask": "possessed_mask",
"Power Treads": "power_treads",
"Prince's Knife": "princes_knife",
"Prophet's Pendulum": "prophets_pendulum",
"Psychic Headband": "psychic_headband",
"Pupil's Gift": "pupils_gift",
"Pyrrhic Cloak": "pyrrhic_cloak",
"Quarterstaff": "quarterstaff",
"Quelling Blade": "quelling_blade",
"Quickening Charm": "quickening_charm",
"Quicksilver Amulet": "quicksilver_amulet",
"Radiance": "radiance",
"Divine Rapier": "rapier",
"Rattlecage": "rattlecage",
"Reaver": "reaver",
"Refresher Orb": "refresher",
"Refresher Shard": "refresher_shard",
"Sacred Relic": "relic",
"Repair Kit": "repair_kit",
"Revenant's Brooch": "revenants_brooch",
"Riftshadow Prism": "riftshadow_prism",
"Ring of Aquila": "ring_of_aquila",
"Ring of Basilius": "ring_of_basilius",
"Ring of Health": "ring_of_health",
"Ring of Protection": "ring_of_protection",
"Ring of Regen": "ring_of_regen",
"Ring of Tarrasque": "ring_of_tarrasque",
"Ripper's Lash": "rippers_lash",
"River Vial: Chrome": "river_painter",
"River Vial: Dry": "river_painter2",
"River Vial: Slime": "river_painter3",
"River Vial: Oil": "river_painter4",
"River Vial: Electrified": "river_painter5",
"River Vial: Potion": "river_painter6",
"River Vial: Blood": "river_painter7",
"Robe of the Magi": "robe",
"Rod of Atos": "rod_of_atos",
"Roshan's Banner": "roshans_banner",
"Royal Jelly": "royal_jelly",
"Block of Cheese": "royale_with_cheese",
"Safety Bubble": "safety_bubble",
"Sange": "sange",
"Sange and Yasha": "sange_and_yasha",
"Satanic": "satanic",
"Searing Signet": "searing_signet",
"Seeds of Serenity": "seeds_of_serenity",
"Seer Stone": "seer_stone",
"Serrated Shiv": "serrated_shiv",
"Shadow Amulet": "shadow_amulet",
"Shawl": "shawl",
"Scythe of Vyse": "sheepstick",
"Shiva's Guard": "shivas_guard",
"Silver Edge": "silver_edge",
"Sister's Shroud": "sisters_shroud",
"Eye of Skadi": "skadi",
"Slippers of Agility": "slippers",
"Smoke of Deceit": "smoke_of_deceit",
"Sage's Mask": "sobi_mask",
"Solar Crest": "solar_crest",
"Soul Booster": "soul_booster",
"Soul Ring": "soul_ring",
"Spark of Courage": "spark_of_courage",
"Specialist's Array": "specialists_array",
"Spell Prism": "spell_prism",
"Spellslinger": "spellslinger",
"Linken's Sphere": "sphere",
"Spider Legs": "spider_legs",
"Spirit Vessel": "spirit_vessel",
"Splintmail": "splintmail",
"Telescope": "spy_gadget",
"Staff of Wizardry": "staff_of_wizardry",
"Stonefeather Satchel": "stonefeather_satchel",
"Stormcrafter": "stormcrafter",
"Stout Shield": "stout_shield",
"Swift Blink": "swift_blink",
"Talisman of Evasion": "talisman_of_evasion",
"Tango": "tango",
"Tango (Shared)": "tango_single",
"The Leveller": "the_leveller",
"Third Eye": "third_eye",
"Tiara of Selemene": "tiara_of_selemene",
"Leviathan's Fish": "tidehunter_fish",
"Tier 1 Token": "tier1_token",
"Tier 2 Token": "tier2_token",
"Tier 3 Token": "tier3_token",
"Tier 4 Token": "tier4_token",
"Tier 5 Token": "tier5_token",
"Timeless Relic": "timeless_relic",
"Titan Sliver": "titan_sliver",
"Tome of Aghanim": "tome_of_aghanim",
"Tome of Knowledge": "tome_of_knowledge",
"Town Portal Scroll": "tpscroll",
"Tranquil Boots": "tranquil_boots",
"Boots of Travel": "travel_boots",
"Boots of Travel 2": "travel_boots_2",
"Trickster Cloak": "trickster_cloak",
"Trident": "trident",
"Trusty Shovel": "trusty_shovel",
"Ultimate Orb": "ultimate_orb",
"Aghanim's Scepter": "ultimate_scepter",
"Aghanim's Blessing": "ultimate_scepter_2",
"Aghanim's Blessing - Roshan": "ultimate_scepter_roshan",
"Unrelenting Eye": "unrelenting_eye",
"Pig Pole": "unstable_wand",
"Unwavering Condition": "unwavering_condition",
"Urn of Shadows": "urn_of_shadows",
"Vambrace": "vambrace",
"Vampire Fangs": "vampire_fangs",
"Vanguard": "vanguard",
"Veil of Discord": "veil_of_discord",
"Vindicator's Axe": "vindicators_axe",
"Vitality Booster": "vitality_booster",
"Vladmir's Offering": "vladmir",
"Void Stone": "void_stone",
"Voodoo Mask": "voodoo_mask",
"Observer and Sentry Wards": "ward_dispenser",
"Observer Ward": "ward_observer",
"Sentry Ward": "ward_sentry",
"Weighted Dice": "weighted_dice",
"Whisper of the Dread": "whisper_of_the_dread",
"Wind Lace": "wind_lace",
"Wind Waker": "wind_waker",
"Witch Blade": "witch_blade",
"Witless Shako": "witless_shako",
"Wizard Hat": "wizard_hat",
"Woodland Striders": "woodland_striders",
"Wraith Band": "wraith_band",
"Wraith Pact": "wraith_pact",
"Yasha": "yasha",
"Yasha and Kaya": "yasha_and_kaya"
}
};
