"use strict";

// RU/EN copy is independent of view state and DOM. Formatters are supplied by
// the view so numbers continue to follow its current locale after switching.
(function () {
  function create({ number, decimal, clock, plural }) {
    const TEXT = {
      en: {
        pfTitle: "Profile",
        pfSub: "Your rating, level and achievements with Wardly.",
        pfLevel: (n) => `Level ${n}`,
        pfXp: (into, need) => `${into} / ${need} XP to the next level`,
        pfSparks: "Sparks",
        pfSparksHint: "Earned by playing with the coach: 10 a match, 5 more for a win, more for every achievement tier. Spend them on profile looks.",
        pfGames: "Matches with Wardly",
        pfWithApp: "With the coach",
        pfNextBadge: "Closest award",
        pfWinrate: "Win rate",
        pfHours: "Hours with the coach",
        pfNoName: "Player",
        pfRating: "Rating",
        pfRatingNone: "Enter your MMR from Dota to start the graph: every ranked game then moves it.",
        pfRatingMedal: "Estimated from your medal. Enter your MMR from Dota for your own line.",
        pfRatingManual: (step) => `An estimate: a ranked game moves it by about ${step}. Correct it when it drifts from Dota.`,
        pfNow: "Now",
        pfPeak: "Peak",
        pfLast20: "Last 20 games",
        pfRecord: (w, l) => `${w}–${l}`,
        pfMmrLabel: "Your MMR now",
        pfMmrPlaceholder: "e.g. 3200",
        pfMmrSave: "Save",
        pfMmrClear: "Back to the medal estimate",
        pfMmrBad: "Enter a number from 0 to 15000.",
        pfWin: "Win",
        pfLoss: "Loss",
        pfAnchor: "Your number",
        pfAchievements: "Achievements",
        pfAchievementsHint: "For matches played with Wardly. Every tier gives sparks.",
        pfTierNone: "Not started",
        pfTier: (name, tier, tiers) => `${name} · ${tier}/${tiers}`,
        pfDone: "All tiers done",
        pfReward: (n) => `+${n} sparks`,
        pfProgress: (value, target) => `${value} / ${target}`,
        pfEmpty: "Play a match with Wardly running: it starts your level, achievements and sparks.",
        pfFriends: "Friends",
        pfFriendsHint: "Show your profile to friends by a code and see theirs: level, rating, looks and achievements.",
        pfFriendsOff: "Your profile is visible only to you. Show it, and friends who have your code see your card: name, level, medal, achievements, looks and matches with Wardly — no Steam ID and no match list.",
        pfFriendsShow: "Show my profile to friends",
        pfFriendsHide: "Hide my profile",
        pfFriendsCode: "Your friend code",
        pfFriendsCopy: "Copy code",
        pfFriendsCopyLink: "Copy link",
        pfFriendsOpen: "Open the page",
        pfFriendsCopied: "Copied.",
        pfFriendsShowMmr: "Show my rating",
        pfFriendsAdd: "Add",
        pfFriendsAddPlaceholder: "Friend code, e.g. WD-4K7P9QX2",
        pfFriendsEmpty: "No friends yet: send them your code, and add theirs.",
        pfFriendsYou: "You",
        pfFriendsRemove: "Remove",
        pfFriendsWeek: (n) => `${n} this week`,
        pfFriendsMissing: (codes) => `Hidden or not found: ${codes}`,
        pfFriendsErrors: { bad_code: "That is not a friend code.", own_code: "That is your own code.", already: "Already in the list.", too_many: "50 friends at most.", offline: "No connection to the server.", disabled: "Friends are switched off on the server for now.", rate_limited: "Too many requests: try again in an hour.", backend_down: "The coach service is not running." },
        pfShop: "Profile looks",
        pfShopHint: "Spend sparks on how your profile looks. Rare ones need a level or an achievement.",
        pfKinds: { frame: "Avatar frames", banner: "Banners", name: "Name colour", title: "Titles" },
        pfBuy: (price) => `Buy · ${price}`,
        pfWear: "Wear",
        pfWorn: "Worn",
        pfFree: "Free",
        pfNeedSparks: (n) => `${n} more ${n === 1 ? "spark" : "sparks"}`,
        pfLockedHint: "Not open yet: see the line above",
        pfNeedLevel: (n) => `From level ${n}`,
        pfNeedAchievement: (name, tier) => `For “${name}”, tier ${tier}`,
        pfShopErrors: { not_enough: "Not enough sparks yet.", locked_level: "Your level is too low for it.", locked_achievement: "It comes with an achievement.", owned: "You already have it." },
        linkTitle: "Link your Steam account",
        linkHint:
          "The coach reads your account from Dota automatically when you play. You can also paste your Friend ID (Dota profile), a steamcommunity.com/profiles/… link or an OpenDota/Dotabuff link.",
        linkPlaceholder: "Friend ID, Steam ID or profile link",
        linkButton: "Link",
        linkSoon: "Once your account is linked, here you get:",
        offlineStarting: "The coach is starting",
        offlineStartingHint: "A few seconds: this page opens by itself.",
        offlineTitle: "The coach is not answering",
        offlineHint: "Your matches and reviews are safe: they show again once the coach runs.",
        offlineStart: "Start the coach",
        newerMatch: "Newer",
        olderMatch: "Older",
        newerMatchHint: (hero) => `The newer match${hero ? ` (${hero})` : ""} · ←`,
        olderMatchHint: (hero) => `The older match${hero ? ` (${hero})` : ""} · →`,
        prevRowMatch: "Previous",
        nextRowMatch: "Next",
        prevRowMatchHint: (hero) => `The row above in the list${hero ? ` (${hero})` : ""} · ←`,
        nextRowMatchHint: (hero) => `The row below in the list${hero ? ` (${hero})` : ""} · →`,
        sortBy: (label) => `Sort by “${label}”: click again to flip the order`,
        openOnSite: (name) => `Open this match on ${name}`,
        progressSoon: "Once a few matches are reviewed, here you get:",
        linkPerks: {
          matches: [
            ["target", "every game with its score and what to fix first"],
            ["skull", "each death: the minute, the place and what was ready to press"],
            ["swords", "your build next to the pros and players of your rank"]
          ],
          progress: [
            ["trending-up", "your last 10 games against the 10 before"],
            ["repeat", "the mistakes that repeat, and one focus for the next game"],
            ["map", "your heroes, your lanes and where you die most"]
          ],
          profile: [
            ["chart-line", "your rating graph and your level"],
            ["trophy", "achievements and looks for your card"],
            ["users", "friends by code and a leaderboard"]
          ]
        },
        progressSub: "How your game changes from match to match",
        linkErrors: {
          empty: "Enter a Friend ID, Steam ID or profile link.",
          vanity_url: "Custom links (steamcommunity.com/id/…) can't be resolved. Use your Friend ID from the Dota profile.",
          unrecognized: "This doesn't look like a Steam account.",
          out_of_range: "This number is not a valid Steam account.",
          backend_down: "The coach is not running.",
          request_failed: "Could not link the account."
        },
        detected: (name) => `Playing now: ${name}.`,
        detectedLink: "Link this account",
        detectedOther: (name) => `Dota is running on another account: ${name}.`,
        switchAccount: "Switch",
        friendId: (id) => `Friend ID ${id}`,
        sourceLabel: { gsi: "detected in Dota", manual: "linked by hand", opendota: "OpenDota" },
        change: "Change",
        refresh: "Refresh",
        syncing: "Updating history…",
        syncedAt: (when) => `History updated ${when}`,
        syncNever: "History not loaded yet",
        syncOffline: "OpenDota is off — only matches recorded by the app are shown.",
        syncError: {
          offline: "No internet — showing matches recorded by the app.",
          private: "Match data is private. In Dota: Settings → Social → Expose Public Match Data.",
          rate_limited: "OpenDota is busy, try again in a minute.",
          not_found: "OpenDota doesn't know this account yet.",
          bad_response: "OpenDota answered with an error."
        },
        matchesTitle: "Matches",
        matchesSub: "Every game with its review: open one to see what to fix",
        matchesTableTitle: "Match history",
        progressTitle: "Progress",
        zoneFix: "What to fix",
        zoneFixHint: "The coach's review and the goal for the next game",
        zoneStory: "How the match went",
        zoneStoryHint: "Farm and gold over time, deaths, the advice you got",
        zoneScores: "Scores and comparison",
        zoneScoresHint: "Areas of the game, what went well, your rank",
        zoneMapItems: "Map and items",
        zoneMapItemsHint: "Where you were, what you bought and when",
        zoneTeams: "Teams",
        zoneSummary: "Summary",
        zoneSummaryHint: "Your last 10 matches against the 10 before",
        zoneCoach: "Coach",
        zoneCoachHint: "What keeps coming back and what to train",
        zoneGames: "Games and heroes",
        zoneGamesHint: "The score of every match and your heroes",
        zoneCompare: "Comparison",
        zoneCompareHint: "Players of your rank, enemy heroes, a friend",
        zoneHero: "Your main hero",
        zoneHeroHint: "Your best games against your worst, your build",
        sectionNav: "Page sections",
        openPlaceholder: "Match number or link",
        openButton: "Open",
        openBad: "No match number there: paste the number or an OpenDota, Dotabuff or STRATZ link.",
        openLoading: "Fetching the match from OpenDota…",
        openErrors: {
          not_player: "You did not play in this match (or your OpenDota profile hides it).",
          mode: "Turbo, bot games and the like are not reviewed.",
          not_found: "OpenDota does not know this match yet: check the number, or try again in a few minutes.",
          offline: "No connection to OpenDota: try again a little later.",
          rate_limited: "OpenDota is busy: try again in a minute.",
          unlinked: "Link your Steam account first.",
          pending: "OpenDota is still answering: try again in a minute.",
          error: "The match could not be fetched: try again a little later."
        },
        dialogClose: "Close",
        navFix: "Fix",
        navStory: "The match",
        navScores: "Scores",
        navMap: "Map and items",
        navTeams: "Teams",
        navSummary: "Summary",
        navGoals: "Goals",
        navCoach: "Coach",
        navGames: "Games",
        navCompare: "Comparison",
        navHero: "Main hero",
        colResult: "Result",
        colHero: "Hero",
        colKda: "K / D / A",
        colGpm: "Gold/min",
        colLh10: "Last hits by 10:00",
        colDuration: "Time",
        colScore: "Score",
        colItems: "Items",
        colWhen: "Played",
        win: "Win",
        loss: "Loss",
        unknownResult: "—",
        noMatchesTitle: "No matches yet",
        noMatchesHint: "Play a match with the coach running, or press Refresh to load your history from OpenDota.",
        more: "Show more",
        liveMatch: (hero) => `Recording the current match${hero ? ` (${hero})` : ""} — the review appears right after it ends.`,
        back: "Matches",
        palPlaceholder: "Where to go or what to do…",
        palEmpty: "Nothing found. Try a hero, a tab or a setting.",
        palHint: "↑↓ choose · Enter open · Esc close",
        palGroups: { tabs: "Tab", actions: "Action", heroes: "Progress", matches: "Match", settings: "Setting" },
        palProgressHero: (hero) => `Progress on ${hero}`,
        palSync: "Update the match history",
        palOpenNumber: "Open a match by its number",
        palHotkeys: "Hotkeys",
        palTour: "Show the tour",
        palReport: "Report a problem",
        noteAdd: "Add a note",
        noteAddHint: "Your own line on this match: lag, a new build, who you played with. Kept on this computer only.",
        noteEdit: "Edit the note",
        noteLabel: "Your note",
        notePlaceholder: "For example: lag, tried a new build",
        noteSave: "Save",
        noteCancel: "Cancel",
        noteFailed: "Could not save the note. Try again.",
        backTo: { home: "Home", matches: "Matches", progress: "Progress", profile: "Profile", settings: "Settings" },
        filterResult: "Result",
        filterResults: { all: "All", win: "Wins", loss: "Losses" },
        filterHero: "Hero",
        filterAllHeroes: "All heroes",
        filterSummary: (games, winrate, score) =>
          [`${games} ${games === 1 ? "match" : "matches"}`, winrate == null ? null : `${winrate}% wins`, score == null ? null : `average score ${score}`].filter(Boolean).join(" · "),
        skippedModes: (count, turbo, of) =>
          `${count} of your last ${of} games are not reviewed${turbo ? ` (Turbo: ${turbo})` : ""}: Turbo, bot games and special modes have different norms.`,
        filterEmptyTitle: "No matches for this filter",
        filterEmptyHint: "Pick another hero or result.",
        pdfSave: "Save PDF",
        pdfSaved: (name) => `Saved: ${name}`,
        pdfFailed: "Could not save the PDF",
        reviewLoading: "Loading the match…",
        reviewPending: "The review appears once the match data is loaded.",
        reviewError: "Could not open the match",
        reviewRetry: "Try again",
        matchErrors: {
          backend_down: "The coach is not running: the review opens once it runs again.",
          request_failed: "The coach did not answer in time. Try again in a few seconds.",
          match_not_found: "This match is no longer in your history."
        },
        reviewRenderFailed: "This is a bug in the app. Please report it (Settings → Help → Report a problem) so it can be fixed.",
        scoreOf: "of 100",
        sourcesParsed: "Full replay parsed by OpenDota",
        sourcesBasic: "Match totals only — the full replay review is not ready yet",
        sourcesGsi: "Recorded by the app during the match",
        parseStatus: {
          waiting_opendota: "Full replay review in a few minutes (OpenDota).",
          parsing: "OpenDota is studying the replay — the review fills in by itself.",
          basic: "Replay not parsed: no minute-by-minute data.",
          not_parsed: "OpenDota could not study the replay, so the review is shorter.",
          gsi_only: "Only the app's own recording is available (OpenDota is off).",
          private: "This match is private on OpenDota. In Dota: Settings → Social → Expose Public Match Data (works for the next matches); the review uses the app's own recording meanwhile.",
          "error:not_found": "OpenDota doesn't have this match yet — try again in a few minutes.",
          "error:offline": "No internet — showing the app's own recording.",
          "error:rate_limited": "OpenDota is busy — try again in a minute.",
          "error:bad_response": "OpenDota answered with an error."
        },
        requestParse: "Request replay parse",
        parseRequested: "Requested — it usually takes 2–10 minutes.",
        focusTitle: "Focus for the next game",
        sectionsTitle: "Breakdown",
        explainTitle: "What does this mean?",
        explainScore:
          "The score (0 to 100) shows how close the match was to good play for your role: lane, farm, survival, fights, items and, for a support, vision, each on its own scale. 65+ is good (B), 80+ is great (A), under 50 is a match to learn from (D). A win or a loss does not change it: you can lose with 80 and win with 30.",
        explainRank:
          "Matchmaking puts players of about the same rank into one game, so the player of your role in this match (on either side) shows what is usual at your rank. Above them — you did better than your rank; below — there is room to grow.",
        explainFocus:
          "The focus is the one mistake you work on. After every match the coach checks whether it happened again: a green mark means it did not. One thing at a time is easier to fix than everything at once.",
        chartTitle: "Over the match",
        mapTitle: "Match map",
        deathsTitle: (count) => `Deaths · ${count}`,
        weekGames: "Matches",
        weekVsPrevious: "vs the week before",
        weekRecord: (w, l) => `${w}W · ${l}L`,
        weekScoreNote: {
          no_score: "No reviewed matches this week yet",
          no_previous: "No matches the week before to compare with",
          no_previous_score: "The week before has no reviewed matches"
        },
        weekChartTitle: "Score of every match this week",
        weekBest: "Best match",
        weekHeroes: "Heroes:",
        weekHeroTitle: (hero, games, wins) => `${hero}: ${games} ${games === 1 ? "match" : "matches"}, ${wins} ${wins === 1 ? "win" : "wins"}`,
        weekProblem: "Most often:",
        weekProblemText: (title, count, of) => `${title} — in ${count} of ${of} matches`,
        weekFocus: "Focus:",
        weekPlanProgress: (met, played, plan) => `${met} of ${played} done · plan: ${plan} matches in a row`,
        weekPlanNext: "Next match",
        sessionGames: "Matches",
        sessionScore: "Average score",
        sessionVsUsual: "vs your usual",
        sessionUsual: (score) => `Your usual: ${score}`,
        sessionNoScore: "No reviewed matches yet",
        sessionTime: (minutes) => (minutes >= 60 ? `${Math.floor(minutes / 60)} h ${String(minutes % 60).padStart(2, "0")} min played` : `${minutes} min played`),
        sessionDeaths: (deaths) => `deaths a match on average: ${deaths}`,
        sessionProblem: "To work on:",
        sessionProblemText: (title, count, of) => `${title} — in ${count} of ${of}`,
        sessionFocus: (title, met, total) => `Focus “${title}”: done in ${met} of ${total}`,
        sessionCopy: "Copy for friends",
        sessionCopied: "Copied",
        sessionPreview: "What will be copied",
        deathsNoPattern: "No repeating cause across these deaths.",
        deathNoFacts: "Nothing else is known about this death.",
        deathGold: (gold) => `${gold} unspent gold`,
        deathAfterRespawn: (seconds) => `${seconds} s after respawning`,
        deathWarned: (time, action) => `The coach warned at ${time}: “${action}”`,
        deathNote: {
          enemy_half: "on the enemy half",
          unspent_gold: "with 1000+ unspent gold",
          warned: "after a warning",
          soon_after_respawn: "right after respawning",
          saver_ready: "a saving item was ready",
          burst: "killed in under 3 s"
        },
        deathLastTitle: "HP in the last 20 s",
        deathBurst: (seconds) => `From 70%+ HP to death in ${seconds} s`,
        deathReady: "Ready and not used:",
        deathReadyStunned: "Ready, but you were disabled:",
        deathZone: { top: "top lane", mid: "mid lane", bot: "bottom lane", jungle: "jungle", base: "base" },
        mapEmpty: "No positions for this match yet. They come from a parsed replay (the app asks OpenDota to parse your 5 newest matches of the week) or from a match played with the app running: your path and where you died.",
        mapHint: {
          path: "Where your hero went (every 15 s, recorded by the app) and where you died.",
          replay: "From the parsed replay: where you stood in the lane, where you placed wards and where you died in team fights.",
          both: "Your path (recorded by the app), laning position, wards from the replay and where you died."
        },
        mapLabels: {
          radiant: "Radiant",
          dire: "Dire",
          death: "Death",
          observer: "Observer ward",
          sentry: "Sentry ward",
          path: "Your path",
          lane: "Laning position",
          spot: "Where deaths repeat"
        },
        mapSpotTitle: (count, place) => `${count} deaths · ${place}`,
        mapSpotLine: (place, count) => `Most often: ${place} (${count} ${count === 1 ? "death" : "deaths"})`,
        watchMoment: "Watch",
        watchMomentHint: "Copies a Dota console command. Open this match's replay in Dota, press \\ for the console and paste it: the replay jumps to about 10 s before this moment.",
        watchCopied: "Copied: paste in the replay console",
        watchFailed: "Could not copy",
        bestOnHeroLine: (score) => `Your best match on this hero (${score})`,
        bestOnHeroNote: (score, when) => `Dashed: your best match on this hero, score ${score} (${when}).`,
        bestOnHeroSelf: (of) => `This is your best match on this hero out of ${of}.`,
        mapDeaths: "Deaths",
        killedBy: (hero) => `Killed by ${hero}`,
        mapSide: { own: "on your half", river: "in the river", enemy: "on the enemy half" },
        mapWards: "Wards placed",
        mapWardsLine: (obs, sen) => `${obs} observer · ${sen} sentry`,
        chartLh: "Last hits",
        chartGold: "Gold earned",
        chartXp: "Experience",
        you: "You",
        target: "Target pace",
        deathsMarker: "Death",
        minuteLabel: (m) => `${m}:00`,
        strengthsTitle: "What went well",
        improveTitle: "What to improve",
        foldMore: (n) => `Show ${n} more`,
        foldLess: "Show less",
        repeatInARow: (n) => `${n} matches in a row — a habit, not bad luck`,
        repeatInLast: (n, of) => `Also in ${n} of your previous ${of} matches`,
        nothingToImprove: "No serious mistakes found in this match.",
        nothingStrong: "Nothing stood out this time.",
        drill: "Drill",
        momentsTitle: "Key moments",
        adviceLogTitle: "Advice during the match",
        adviceWhy: "Why this advice?",
        adviceLogHint: (n, urgent) => `${n} ${n === 1 ? "tip" : "tips"} over the game, ${urgent} urgent. Worth checking whether you followed them.`,
        adviceLogMore: (n) => `Show all ${n}`,
        adviceLogDeath: (time) => `Died at ${time}`,
        momentDeath: (killer) => (killer ? `Died to ${killer}` : "Died"),
        momentGold: (gold) => `${gold} gold on hand`,
        momentItem: (item) => item,
        momentBuyback: "Buyback",
        momentStall: (to) => `Farm stall until ${to}`,
        scoreboardTitle: "Scoreboard",
        radiant: "Radiant",
        dire: "Dire",
        colPlayer: "Player",
        colNw: "Net worth",
        colDmg: "Damage",
        stats: {
          kda: "K / D / A",
          gpm: "Gold and XP per minute",
          lh: "Last hits / denies",
          nw: "Net worth",
          dmg: "Hero damage",
          duration: "Duration",
          items: "Items at the end"
        },
        sectionFacts: {
          laning: (s) => [s.lh10 != null && `${s.lh10} last hits by 10:00`, s.lane_efficiency != null && `lane efficiency ${Math.round(s.lane_efficiency)}%`, s.lane_deaths ? `${s.lane_deaths} deaths in lane` : null, s.runes != null && `${s.runes} runes${s.enemy_runes != null ? ` (enemy mid ${s.enemy_runes})` : ""}`],
          farm: (s) => [s.gpm != null && `${s.gpm} gold a minute`, s.gpm_pct != null && `better than ${Math.round(s.gpm_pct * 100)}%`],
          survival: (s) => [`${s.deaths} deaths`, s.deaths_per_10 != null && `${decimal(s.deaths_per_10)} per 10 min`],
          fights: (s) => [s.kill_participation != null && `${s.kill_participation}% kill participation`, s.stuns != null && `${decimal(s.stuns)} s of stuns${s.enemy_stuns != null ? ` (enemy offlaner ${decimal(s.enemy_stuns)} s)` : ""}`, s.enemy_tower_damage != null && s.tower_damage != null && `${number(s.tower_damage)} building damage (enemy offlaner ${number(s.enemy_tower_damage)})`],
          items: (s) => [
            s.first_item && `${s.first_item.item} at ${clock(s.first_item.t)}`,
            s.save_item && `Save item: ${s.save_item.item} at ${clock(s.save_item.t)}`,
            "save_item" in s && !s.save_item && "No save item"
          ],
          vision: (s) => [s.obs_placed != null && `${s.obs_placed} observers`, s.sen_placed != null && `${s.sen_placed} sentries`, s.camps_stacked != null && `${s.camps_stacked} stacks`]
        },
        progressEmptyTitle: "Not enough matches yet",
        progressEmptyHint: "Statistics appear after a few reviewed matches. Refresh your history on the Matches tab.",
        tiles: { winrate: "Win rate", kda: "KDA", gpm: "Gold per minute", lh10: "Last hits at 10:00", score: "Avg. score" },
        vsPrevious: (n) => `vs previous ${n}`,
        streakWin: (n) => `${n} wins in a row`,
        streakLoss: (n) => `${n} losses in a row`,
        recordLine: (w, l, n) => `${w}W – ${l}L over ${n} matches`,
        scoreChartTitle: "Score by match",
        scoreChartHint: "Last 20 matches, oldest on the left. Click a column to open the review; no column means the match has no detailed review.",
        scoreLabel: "Score",
        winKey: "win",
        lossKey: "loss",
        baselineIntro: (games, hero) => `Against your ${games} other ${games === 1 ? "match" : "matches"} on ${hero}:`,
        baselineLabels: { score: "score", gpm: "gold/min", lh_10: "last hits at 10", deaths: "deaths" },
        baselineSame: "as usual",
        baselineTitle: (average) => `Your average: ${average}`,
        goalTitle: "Your focus",
        goalHint: "One problem at a time: every next match shows whether it came back.",
        goalSince: (date) => `since ${date}`,
        goalProgress: (met, total) => `Done in ${met} of ${total} ${total === 1 ? "match" : "matches"}`,
        goalWaiting: "Play a match: after it you will see here whether it worked.",
        goalStreak: (n) => `${n} matches in a row without it`,
        goalClear: "Stop tracking",
        goalSet: "Make it my focus",
        goalSetFailed: "Could not save the focus, try again",
        goalCurrent: "Focus",
        goalMet: "done",
        goalMissed: "happened again",
        goalMatch: (title, met) => `Your focus “${title}”: ${met ? "done in this match" : "it happened again"}`,
        planTitle: "What to work on",
        planHint: "Problems that keep coming back in your recent matches, with one drill each.",
        planEmpty: "No repeated problems found — keep it up.",
        strengthsRecurring: "Your strengths",
        heroesTitle: "Heroes",
        colMatches: "Matches",
        colWinrate: "Win rate",
        analyzed: (a, n) => `${a} of ${n} matches reviewed in depth`,
        buildTitle: "Build",
        lanesTitle: "Your lanes",
        lanesLine: (won, even, lost, games) => `Of your last ${games} lanes: ${won} won, ${even} even, ${lost} lost.`,
        lanesGold: (diff) => `On average ${diff} gold against your lane opponent by minute 10.`,
        lanesHard: (list) => `Lanes lost more than once against: ${list}.`,
        lanesDot: (hero, enemy, result, diff) => `${hero} against ${enemy}: ${result}, ${diff} gold by minute 10`,
        laneTitle: "Lane",
        laneVs: "against",
        laneResult: { won: "Lane won", even: "Even lane", lost: "Lane lost" },
        laneMinute: (m) => `${m}:00`,
        laneColMinute: "Minute",
        laneColLh: "Last hits",
        laneColDn: "Denies",
        laneColGold: "Gold",
        laneColXp: "XP",
        laneTurn: (m) => `The gap opened at minute ${m}.`,
        laneOthers: (heroes, diff) => `Also in the lane: ${heroes}; the whole lane's gold by minute 10: ${diff}.`,
        laneNote: "You : them; gold and XP as the difference. From the parsed replay.",
        skillsTitle: "Skill order",
        skillsYours: "Yours first:",
        skillsPro: "How pros max their skills on this hero:",
        skillsSame: (name) => `You also maxed ${name} first, like the pros.`,
        skillsDiff: (yours, pro) => `You maxed ${yours} first; pros start with ${pro}.`,
        skillsNote: (agree, games) => `${agree} of ${games} recent pro games start this way. The in-game tip names where each point goes.`,
        buildTimingNote: "Win rate of the hero by purchase time (OpenDota public matches). Your timing is highlighted. The earliest timings mostly come from games that were already going well, so the target is the usual timing.",
        buildNoTimings: "No timing data for these items yet.",
        buildItemLine: (wr, t, typicalT, typicalWr) => `${wr}% wins when bought by ${t} · usually bought by ${typicalT} — ${typicalWr}%`,
        buildItemTypical: (wr, t) => `${wr}% wins when bought by ${t} · the usual timing for the hero`,
        buildBy: (t) => `by ${t}`,
        buildPopular: "Common build (pro players)",
        buildPhase: { early: "Early", mid: "Core", late: "Late" },
        buildBought: "bought",
        buildTimingTip: (t) => `Bought by ${t}`,
        winrateLabel: "Win rate",
        rankTitle: "You and your rank",
        rankMatchNote: (rank, role, heroes) => `${rank ? `Match rank: ${rank} · ` : ""}compared with the ${role} of this match${heroes ? ` (${heroes})` : ""}`,
        rankNoPeers: "No player of the same role in this match to compare with.",
        colMetric: "Metric",
        colYou: "You",
        colOpponent: "Opponent",
        colPeers: "Your rank",
        colDiff: "Difference",
        metrics: { gpm: "Gold per minute", xpm: "XP per minute", lh_10: "Last hits at 10:00", lh_per_min: "Last hits per minute", deaths: "Deaths", kda: "KDA", damage_per_min: "Damage per minute", net_worth: "Net worth" },
        rankCareerTitle: "You and players of your rank",
        rankCareerNote: (rank, role, n) => `${rank || "Your rank"} · ${role} · same-role players in your ${n} reviewed matches`,
        rankCareerEmpty: "Appears after a few matches reviewed with OpenDota data.",
        colBracket: "At your rank",
        bracketHint: (rank) => `Hero win rate among all ${rank} players (OpenDota)`,
        shareButton: "Share",
        shareTitle: "Share this review",
        shareWhat: "A page with this review: hero, result, score, the match numbers, the areas and what to improve. Anyone with the link can open it.",
        shareNot: "Not published: the match number, your Steam ID, nickname and the other players. The link works for 90 days, and you can delete it at any time.",
        shareCoach: "Add the AI coach's summary",
        shareCreate: "Create a link",
        shareCreating: "Creating the link…",
        shareLink: "Link to the review",
        shareCopy: "Copy",
        shareCopied: "Copied.",
        shareOpen: "Open",
        shareDelete: "Delete the link",
        shareDeleted: "The link is deleted.",
        shareExpires: (date) => `Works until ${date}.`,
        shareWithCoach: "With the AI coach's summary.",
        shareFailed: (code) => `Could not do it${code ? ` (${code})` : ""}: check the internet and try again.`,
        shareTitleProgress: "Share your progress",
        shareWhatProgress: "A page with your progress over all heroes: matches, win rate, averages, the last 10 against the 10 before, top heroes, what goes well and what to work on. Anyone with the link can open it.",
        shareNotProgress: "Not published: match numbers, your Steam ID, nickname, the other players and your questions to the coach. The link works for 90 days, and you can delete it at any time.",
        shareLinkProgress: "Link to your progress",
        trendTitle: (item) => `${item}: timing game by game`,
        trendLine: (recent, n, before, m) => `Last ${n} games: ${recent}; the ${m} before: ${before}.`,
        trendRecentOnly: (recent, n) => `Last ${n} games: ${recent} (median).`,
        trendSooner: (gap) => `${gap} sooner`,
        trendLater: (gap) => `${gap} later`,
        trendSame: "about the same",
        trendMinute: "Minute",
        deathMapTitle: "Where you die",
        deathMapNote: (matches, total, per) => `${total} ${total === 1 ? "death" : "deaths"} in ${matches} ${matches === 1 ? "match" : "matches"} with a map, ${per} a match.`,
        deathMapTurned: "Dire games are turned half a turn, so your base is always bottom left.",
        deathMapSpot: (place, count, matches) => `${place}: ${count} deaths in ${matches} matches`,
        deathMapSpots: "Deaths keep repeating here:",
        deathMapLate: (pct) => `After minute 10: ${pct}% of deaths on the enemy half`,
        opponentsTitle: "Enemy heroes",
        opponentsNote: (n, min) => `Your record against each enemy hero in ${n} matches with a known lineup (heroes met ${min}+ times).`,
        opponentsHard: "Hardest to play against",
        opponentsEasy: "You beat them most often",
        opponentRecord: (w, l, wr) => `${w}–${l} · ${wr}%`,
        poolTitle: "Your hero pool",
        poolNote: "Your win rate on each hero (4+ games) against how players of your rank do on it.",
        poolMore: "Play them more",
        poolPark: "Better to park them for now",
        poolRecord: (w, n, wr, br) => `${w} of ${n} won · ${wr}%${br == null ? "" : ` (your rank: ${br}%)`}`,
        goalsTitle: "Your goals",
        streaksTitle: "Streaks",
        goalMakeTop: (title) => `Make it the focus: ${title}`,
        zoneGoals: "Goals",
        zoneGoalsHint: "What you work on and how the last matches went",
        summaryLast: "Last match",
        summaryTip: "Main thing to fix",
        summaryStrength: "What went well",
        summaryOpen: "Open the review",
        summaryToday: "Today",
        summaryNoGames: "No matches yet today",
        summaryFocus: "Your focus",
        summaryFocusProgress: (met, total) => `done in ${met} of ${total}`,
        summaryNoFocus: "Pick one problem to work on: the coach checks every match against it.",
        summaryPickFocus: "Pick in Progress",
        streakFewDeaths: (target) => `${target} matches in a row with 5 deaths or fewer`,
        streakGoodScore: (target) => `${target} matches in a row with a score of 60+`,
        streakProgress: (cur, target) => `${Math.min(cur, target)} of ${target}`,
        streakMet: (cur) => `done: ${cur} in a row`,
        streakBest: (best) => `Your best run in the last 30 matches: ${best}`,
        tiltLosses: (n) => `${n} losses in a row. Maybe take a break, or play something just for fun.`,
        tiltScore: (a, b, usual) => `Your last two scores are ${a} and ${b}, while you usually get about ${usual}. Maybe take a break.`,
        friendTitle: "Compare with a friend",
        friendHint: "A friend's Friend ID, Steam ID or profile link (steamcommunity.com/profiles/…). Their public OpenDota matches are compared with yours: the last 20 games of each.",
        friendPlaceholder: "Friend ID, Steam ID or profile link",
        friendCompare: "Compare",
        friendSelf: "That is your own account.",
        friendFailed: "Could not save the friend.",
        friendLoading: (name) => `Loading the matches of ${name} from OpenDota…`,
        friendPrivate: (name) => `${name} hides their match data.`,
        friendPrivateHint: "They can allow it in Dota 2: Settings → Social → “Expose Public Match Data”. Then press Refresh (OpenDota needs a match played after that).",
        friendOffline: "The comparison needs OpenDota (internet).",
        friendError: (code) => `OpenDota did not answer${code ? ` (${code})` : ""}. Try Refresh later.`,
        friendRefresh: "Refresh",
        friendUpdating: "Updating…",
        friendChange: "Another friend",
        friendGroup: "Games",
        friendGroups: { all: "All games", core: "Core", support: "Support" },
        friendYou: "You",
        friendGames: (me, friend) => `games: you ${me}, friend ${friend}`,
        friendFew: (n) => `Too few games to say who is ahead: ${n}+ for each of you.`,
        friendMetrics: { win_rate: "Win rate", kills: "Kills", deaths: "Deaths", assists: "Assists", gpm: "Gold per minute", xpm: "XP per minute", lh_per_min: "Last hits per minute", damage_per_min: "Hero damage per minute" },
        friendCommon: "Heroes you both played",
        friendHeroGames: (g1, w1, g2, w2) => `you ${g1} · ${w1 ?? "—"}%   friend ${g2} · ${w2 ?? "—"}%`,
        friendTheirHeroes: (name) => `Most played by ${name}`,
        friendNote: "Averages per game, public OpenDota data, ranked and normal modes only. Core or support is judged by last hits a minute.",
        rankHistoryTitle: "Your rank medal",
        rankUp: (from, to, since) => `Up from ${from} to ${to} since ${since}.`,
        rankDown: (from, to, since) => `Down from ${from} to ${to} since ${since}.`,
        rankNote: "The app notes your medal every time it updates your history, and marks when it changes.",
        heroBuildTitle: (hero) => `Your build on ${hero}`,
        buildNote: (n, wins) => `Your items in ${n} reviewed games on the hero (${wins} wins): when they come in wins and in losses, and how often you win with and without them.`,
        buildItem: "Item",
        buildGames: "Games",
        buildWinrate: "Wins with it",
        buildWithout: "Without it",
        buildWinTime: "In wins",
        buildLossTime: "In losses",
        selfTitle: (hero) => `Your best vs your worst games on ${hero}`,
        selfNote: (n) => `The best third of your last ${n} reviewed games on the hero against the worst third, by review score.`,
        selfBest: "Best",
        selfWorst: "Worst",
        selfGroup: (count, wr) => `${count} games · ${wr}% wins`,
        selfMetrics: {
          lh_10: "Last hits at 10:00",
          gpm: "Gold/min",
          deaths: "Deaths",
          lane_deaths: "Lane deaths",
          kill_participation: "Kill participation",
          first_item_t: "First big item"
        },
        draftTitle: "Draft",
        draftNote: (hero) => `How often ${hero} wins against each enemy hero (public match statistics from OpenDota).`,
        draftNoData: "No statistics for these heroes yet: they load the next time your history updates.",
        draftEnemy: "Enemy",
        draftWinrate: "Your win rate",
        draftGames: "games",
        draftPool: "Your heroes against this lineup",
        draftPoolNote: "Average win rate edge over 50% against these five heroes.",
        draftPicked: "your pick",
        draftBetter: (hero) => `${hero} fit this lineup best.`,
        draftCounters: "Answers to the enemy heroes",
        draftReasons: { evasion: "evasion", illusions: "illusions", invisibility: "invisibility", healing: "healing", targeted: "killed you with a disable" },
        draftForSupports: "support's job",
        draftBought: "bought",
        coachTitle: "Coach's review",
        coachCareerTitle: "Coach's review of your recent games",
        coachTag: "AI",
        coachPending: "The coach is writing the review. It takes up to a minute.",
        coachCareerPending: "The coach is looking through your recent matches. It takes up to a minute.",
        coachWaiting: "The AI waits until OpenDota has studied the replay (usually a few minutes): then it has more to go on.",
        coachNow: "Review now",
        coachUpdating: "Updating with the new data…",
        coachRetry: "Try again",
        coachRewrite: "Rewrite",
        coachNotEnough: (n) => `The coach needs at least ${n} reviewed matches.`,
        coachTurning: "Turning points",
        coachMistakes: "Main mistakes",
        coachFix: "Next time",
        coachStrengths: "What went well",
        coachNextGame: "Goals for the next game",
        coachPatterns: "Recurring problems",
        coachTrain: "How to train it",
        coachPlan: "Plan for the next games",
        coachFooter: (provider, model) => `Written by AI (${provider} · ${model}) from the data of the review. Numbers, times, heroes and items are checked against it.`,
        coachErrors: {
          rate_limited: "The free AI limit is used up for now. Try again in a few minutes.",
          busy: "The AI is overloaded right now. Try again in a few minutes.",
          invalid_key: "The key did not work. Check it in the AI coach settings.",
          region: "This AI does not work from your country. Choose another one (OpenRouter, for example) or turn on a VPN; the key is kept.",
          timeout: "The AI took too long to answer.",
          offline: "No connection to the AI: check the internet.",
          unverified: "The AI answer mentioned facts that are not in the data, so it was not shown. Try again.",
          bad_response: "The AI answered with an error. Try again later.",
          no_key: "No key yet."
        },
        askTitle: "Ask the coach",
        askHint: "A question about this match. The answer uses only this match's data and goes through the same fact check.",
        askPlaceholder: "For example: why did I lose the lane?",
        askButton: "Ask",
        askThinking: "The coach is thinking…",
        askSuggestions: ["What decided this game for me?", "What should I change in the lane?", "Was my build on time?"],
        askCareerHint: "A question about your recent matches: heroes, enemies, habits. The answer uses only your statistics and goes through the same fact check.",
        askCareerPlaceholder: "For example: which enemy heroes are hardest for me?",
        askCareerSuggestions: ["Which enemy heroes are hardest for me?", "What mistake costs me the most games?", "Which hero should I play more?"],
        askErrors: {
          unverified: "The coach could not answer this from the match data. Try asking differently.",
          empty_question: "Type a question first.",
          no_review: "The review of this match is not ready yet.",
          not_enough: "Not enough reviewed matches yet: open a few reviews first.",
          off: "Turn the AI coach on in Settings first.",
          pending: "The answer is taking long. Ask again in a minute: while it is being prepared, asking again waits for the same answer.",
          bad_request: "This question could not be sent. Ask it again."
        },
        aiSettingsTitle: "AI coach",
        aiOnTitle: "AI coach is on",
        aiCheckNow: "Check key",
        aiCheckOk: "The key works.",
        aiOffTitle: "AI coach is off",
        aiOffHint: "After every match the AI explains in plain words what went well and what to fix, like a coach watching your replay. Free: you only need a key from Google (Gemini), Groq or OpenRouter.",
        aiTurnOn: "Turn on",
        aiSetupHint: "A key is like a password that lets the app use the AI. Get a free one (a minute, no card) and paste it here. The AI only explains: every number still comes from the review. Your match data (without your Steam ID) goes to the site you chose.",
        aiService: "Where the key is from",
        aiKey: "Key",
        aiKeyPlaceholder: "Paste the key",
        aiModel: "AI model",
        aiAdvanced: "For advanced users",
        aiModelHint: "leave empty for the default",
        aiGetKey: "Get a free key",
        aiSave: "Check and save",
        aiChecking: "Checking the key…",
        aiSaved: "The key works. The coach is on.",
        aiSavedWarn: (reason) => `Key saved, but the check failed: ${reason}`,
        aiSettings: "AI settings",
        aiCurrent: (provider, model, hint) => [provider, model, hint ? `key ${hint}` : ""].filter(Boolean).join(" · "),
        aiEnvKey: "A key is already set in the settings file of the app.",
        aiChangeKey: "Change key",
        aiDisable: "Turn off",
        aiCancel: "Cancel"
      },
      ru: {
        pfTitle: "Профиль",
        pfSub: "Ваш рейтинг, уровень и награды с Wardly.",
        pfLevel: (n) => `Уровень ${n}`,
        pfXp: (into, need) => `${into} / ${need} опыта до следующего уровня`,
        pfSparks: "Искры",
        pfSparksHint: "Даются за игру с тренером: 10 за матч, ещё 5 за победу и больше за каждую ступень награды. Тратятся на оформление профиля.",
        pfGames: "Матчей с Wardly",
        pfWithApp: "С тренером",
        pfNextBadge: "Ближайшая награда",
        pfWinrate: "Процент побед",
        pfHours: "Часов с тренером",
        pfNoName: "Игрок",
        pfRating: "Рейтинг",
        pfRatingNone: "Введите свой MMR из Доты, чтобы начать график: дальше его двигает каждая рейтинговая игра.",
        pfRatingMedal: "Оценка по медали. Введите свой MMR из Доты — график станет вашим.",
        pfRatingManual: (step) => `Это оценка: рейтинговая игра двигает его примерно на ${step}. Поправьте, если разойдётся с Дотой.`,
        pfNow: "Сейчас",
        pfPeak: "Пик",
        pfLast20: "За 20 игр",
        pfRecord: (w, l) => `${w}–${l}`,
        pfMmrLabel: "Ваш MMR сейчас",
        pfMmrPlaceholder: "например, 3200",
        pfMmrSave: "Сохранить",
        pfMmrClear: "Вернуть оценку по медали",
        pfMmrBad: "Введите число от 0 до 15000.",
        pfWin: "Победа",
        pfLoss: "Поражение",
        pfAnchor: "Ваше число",
        pfAchievements: "Награды",
        pfAchievementsHint: "За матчи, сыгранные с Wardly. Каждая ступень даёт искры.",
        pfTierNone: "Не начато",
        pfTier: (name, tier, tiers) => `${name} · ${tier}/${tiers}`,
        pfDone: "Все ступени пройдены",
        pfReward: (n) => `+${n} искр`,
        pfProgress: (value, target) => `${value} / ${target}`,
        pfEmpty: "Сыграйте матч с запущенным Wardly — с него начнутся уровень, награды и искры.",
        pfFriends: "Друзья",
        pfFriendsHint: "Покажите профиль друзьям по коду и смотрите их: уровень, рейтинг, оформление и награды.",
        pfFriendsOff: "Сейчас ваш профиль видите только вы. Покажите его — и друзья с вашим кодом увидят карточку: ник, уровень, медаль, награды, оформление и матчи с Wardly. Без Steam ID и списка матчей.",
        pfFriendsShow: "Показать профиль друзьям",
        pfFriendsHide: "Скрыть профиль",
        pfFriendsCode: "Ваш код друга",
        pfFriendsCopy: "Скопировать код",
        pfFriendsCopyLink: "Скопировать ссылку",
        pfFriendsOpen: "Открыть страницу",
        pfFriendsCopied: "Скопировано.",
        pfFriendsShowMmr: "Показывать мой рейтинг",
        pfFriendsAdd: "Добавить",
        pfFriendsAddPlaceholder: "Код друга, например WD-4K7P9QX2",
        pfFriendsEmpty: "Друзей пока нет: отправьте им свой код и добавьте их.",
        pfFriendsYou: "Вы",
        pfFriendsRemove: "Убрать",
        pfFriendsWeek: (n) => `${n} за неделю`,
        pfFriendsMissing: (codes) => `Скрыты или не найдены: ${codes}`,
        pfFriendsErrors: { bad_code: "Это не код друга.", own_code: "Это ваш собственный код.", already: "Уже в списке.", too_many: "Не больше 50 друзей.", offline: "Нет связи с сервером.", disabled: "Друзья на сервере сейчас выключены.", rate_limited: "Слишком много запросов: попробуйте через час.", backend_down: "Служба тренера не запущена." },
        pfShop: "Оформление",
        pfShopHint: "Тратьте искры на вид профиля. Редкие вещи открываются с уровнем или за награду.",
        pfKinds: { frame: "Рамки аватара", banner: "Баннеры", name: "Цвет ника", title: "Титулы" },
        pfBuy: (price) => `Купить · ${price}`,
        pfWear: "Надеть",
        pfWorn: "Надето",
        pfFree: "Бесплатно",
        pfNeedSparks: (n) => `Ещё ${n} ${plural(n, "искра", "искры", "искр")}`,
        pfLockedHint: "Пока закрыто: условие написано выше",
        pfNeedLevel: (n) => `С ${n}-го уровня`,
        pfNeedAchievement: (name, tier) => `За награду «${name}», ступень ${tier}`,
        pfShopErrors: { not_enough: "Пока не хватает искр.", locked_level: "Нужен уровень выше.", locked_achievement: "Даётся за награду.", owned: "Уже есть." },
        linkTitle: "Привяжите аккаунт Steam",
        linkHint:
          "Тренер сам узнаёт ваш аккаунт из Доты, когда вы играете. Можно и вручную: Friend ID из профиля в Доте, ссылка steamcommunity.com/profiles/… или ссылка на OpenDota/Dotabuff.",
        linkPlaceholder: "Friend ID, Steam ID или ссылка на профиль",
        linkButton: "Привязать",
        linkSoon: "Когда аккаунт привязан, здесь будут:",
        offlineStarting: "Тренер запускается",
        offlineStartingHint: "Пара секунд — страница откроется сама.",
        offlineTitle: "Тренер не отвечает",
        offlineHint: "Ваши матчи и разборы на месте: они появятся, когда тренер снова заработает.",
        offlineStart: "Запустить тренера",
        newerMatch: "Новее",
        olderMatch: "Старее",
        newerMatchHint: (hero) => `Более новый матч${hero ? ` (${hero})` : ""} · ←`,
        olderMatchHint: (hero) => `Более старый матч${hero ? ` (${hero})` : ""} · →`,
        prevRowMatch: "Предыдущий",
        nextRowMatch: "Следующий",
        prevRowMatchHint: (hero) => `Строка выше в списке${hero ? ` (${hero})` : ""} · ←`,
        nextRowMatchHint: (hero) => `Строка ниже в списке${hero ? ` (${hero})` : ""} · →`,
        sortBy: (label) => `Сортировать по «${label}»: нажмите ещё раз, чтобы перевернуть`,
        openOnSite: (name) => `Открыть этот матч на ${name}`,
        progressSoon: "Когда разобранных матчей станет больше, здесь будут:",
        linkPerks: {
          matches: [
            ["target", "все ваши игры с оценкой и тем, что исправить в первую очередь"],
            ["skull", "каждая смерть: минута, место и что было готово к нажатию"],
            ["swords", "ваш билд рядом с про-игроками и игроками вашего ранга"]
          ],
          progress: [
            ["trending-up", "последние 10 игр против 10 игр до них"],
            ["repeat", "ошибки, которые повторяются, и один фокус на следующую игру"],
            ["map", "ваши герои, ваши линии и где вы умираете чаще всего"]
          ],
          profile: [
            ["chart-line", "график рейтинга и ваш уровень"],
            ["trophy", "награды и оформление вашей карточки"],
            ["users", "друзья по коду и таблица лидеров"]
          ]
        },
        progressSub: "Как меняется ваша игра от матча к матчу",
        linkErrors: {
          empty: "Введите Friend ID, Steam ID или ссылку на профиль.",
          vanity_url: "Короткие ссылки (steamcommunity.com/id/…) не распознать. Возьмите Friend ID из профиля в Доте.",
          unrecognized: "Это не похоже на аккаунт Steam.",
          out_of_range: "Такого аккаунта Steam не бывает.",
          backend_down: "Тренер не запущен.",
          request_failed: "Не удалось привязать аккаунт."
        },
        detected: (name) => `Сейчас в Доте: ${name}.`,
        detectedLink: "Привязать этот аккаунт",
        detectedOther: (name) => `В Доте другой аккаунт: ${name}.`,
        switchAccount: "Переключиться",
        friendId: (id) => `Friend ID ${id}`,
        sourceLabel: { gsi: "найден в Доте", manual: "привязан вручную", opendota: "OpenDota" },
        change: "Сменить",
        refresh: "Обновить",
        syncing: "Обновляем историю…",
        syncedAt: (when) => `История обновлена ${when}`,
        syncNever: "История ещё не загружена",
        syncOffline: "OpenDota выключен — видны только матчи, записанные приложением.",
        syncError: {
          offline: "Нет интернета — показываем матчи, записанные приложением.",
          private: "Данные матчей скрыты. В Доте: Настройки → Социальное → включите общий доступ к данным матчей (Expose Public Match Data).",
          rate_limited: "OpenDota перегружен, попробуйте через минуту.",
          not_found: "OpenDota пока не знает этот аккаунт.",
          bad_response: "OpenDota ответил ошибкой."
        },
        matchesTitle: "Матчи",
        matchesSub: "Все игры с разборами: откройте матч, чтобы увидеть, что исправить",
        matchesTableTitle: "История матчей",
        progressTitle: "Прогресс",
        zoneFix: "Что исправить",
        zoneFixHint: "Разбор тренера и цель на следующую игру",
        zoneStory: "Как шёл матч",
        zoneStoryHint: "Фарм и золото по ходу игры, смерти, ваши подсказки",
        zoneScores: "Оценки и сравнение",
        zoneScoresHint: "Разделы игры, что получилось, ваш ранг",
        zoneMapItems: "Карта и предметы",
        zoneMapItemsHint: "Где вы были, что и когда купили",
        zoneTeams: "Составы",
        zoneSummary: "Итоги",
        zoneSummaryHint: "Последние 10 матчей против 10 предыдущих",
        zoneCoach: "Тренер",
        zoneCoachHint: "Что повторяется и что тренировать",
        zoneGames: "Матчи и герои",
        zoneGamesHint: "Оценка каждого матча и ваши герои",
        zoneCompare: "Сравнение",
        zoneCompareHint: "Игроки вашего ранга, вражеские герои, друг",
        zoneHero: "Ваш основной герой",
        zoneHeroHint: "Лучшие игры против худших, ваш билд",
        sectionNav: "Разделы страницы",
        openPlaceholder: "Номер или ссылка на матч",
        openButton: "Открыть",
        openBad: "Не вижу номера матча: вставьте номер или ссылку OpenDota, Dotabuff или STRATZ.",
        openLoading: "Загружаю матч из OpenDota…",
        openErrors: {
          not_player: "Вас нет в этом матче (или ваш профиль OpenDota скрыт).",
          mode: "Турбо, игры с ботами и похожие режимы не разбираются.",
          not_found: "OpenDota пока не знает этот матч: проверьте номер или попробуйте через несколько минут.",
          offline: "Нет связи с OpenDota: попробуйте чуть позже.",
          rate_limited: "OpenDota перегружен: попробуйте через минуту.",
          unlinked: "Сначала привяжите аккаунт Steam.",
          pending: "OpenDota ещё отвечает: попробуйте через минуту.",
          error: "Не получилось загрузить матч: попробуйте чуть позже."
        },
        dialogClose: "Закрыть",
        navFix: "Исправить",
        navStory: "Ход матча",
        navScores: "Оценки",
        navMap: "Карта и предметы",
        navTeams: "Составы",
        navSummary: "Итоги",
        navGoals: "Цели",
        navCoach: "Тренер",
        navGames: "Матчи",
        navCompare: "Сравнение",
        navHero: "Герой",
        colResult: "Итог",
        colHero: "Герой",
        colKda: "У / С / П",
        colGpm: "Золото/мин",
        colLh10: "Добив. к 10",
        colDuration: "Время",
        colScore: "Оценка",
        colItems: "Предметы",
        colWhen: "Когда",
        win: "Победа",
        loss: "Поражение",
        unknownResult: "—",
        noMatchesTitle: "Матчей пока нет",
        noMatchesHint: "Сыграйте матч с запущенным тренером или нажмите «Обновить», чтобы загрузить историю из OpenDota.",
        more: "Показать ещё",
        liveMatch: (hero) => `Записываем текущий матч${hero ? ` (${hero})` : ""} — разбор появится сразу после него.`,
        back: "Матчи",
        palPlaceholder: "Куда перейти или что сделать…",
        palEmpty: "Ничего не нашлось. Попробуйте героя, вкладку или настройку.",
        palHint: "↑↓ выбрать · Enter открыть · Esc закрыть",
        palGroups: { tabs: "Вкладка", actions: "Действие", heroes: "Прогресс", matches: "Матч", settings: "Настройка" },
        palProgressHero: (hero) => `Прогресс на ${hero}`,
        palSync: "Обновить историю матчей",
        palOpenNumber: "Открыть матч по номеру",
        palHotkeys: "Горячие клавиши",
        palTour: "Показать обучение",
        palReport: "Сообщить о проблеме",
        noteAdd: "Заметка",
        noteAddHint: "Ваша строчка к этому матчу: лагало, новый билд, с кем играли. Хранится только на этом компьютере.",
        noteEdit: "Изменить заметку",
        noteLabel: "Ваша заметка",
        notePlaceholder: "Например: лагало, пробовал новый билд",
        noteSave: "Сохранить",
        noteCancel: "Отмена",
        noteFailed: "Не удалось сохранить заметку. Попробуйте ещё раз.",
        backTo: { home: "Главная", matches: "Матчи", progress: "Прогресс", profile: "Профиль", settings: "Настройки" },
        filterResult: "Результат",
        filterResults: { all: "Все", win: "Победы", loss: "Поражения" },
        filterHero: "Герой",
        filterAllHeroes: "Все герои",
        filterSummary: (games, winrate, score) =>
          [`${games} ${plural(games, "матч", "матча", "матчей")}`, winrate == null ? null : `${winrate}% побед`, score == null ? null : `средняя оценка ${score}`].filter(Boolean).join(" · "),
        skippedModes: (count, turbo, of) =>
          `Не разбираем ${count} из ${of} последних игр${turbo ? ` (Турбо: ${turbo})` : ""}: в Турбо, играх с ботами и особых режимах другие нормы.`,
        filterEmptyTitle: "Нет матчей под этот фильтр",
        filterEmptyHint: "Выберите другого героя или результат.",
        pdfSave: "Сохранить PDF",
        pdfSaved: (name) => `Сохранено: ${name}`,
        pdfFailed: "Не удалось сохранить PDF",
        reviewLoading: "Загружаем матч…",
        reviewPending: "Разбор появится, когда загрузятся данные матча.",
        reviewError: "Не удалось открыть матч",
        reviewRetry: "Попробовать ещё раз",
        matchErrors: {
          backend_down: "Тренер сейчас не запущен: разбор откроется, когда он снова заработает.",
          request_failed: "Тренер не успел ответить. Попробуйте ещё раз через пару секунд.",
          match_not_found: "Этого матча больше нет в истории."
        },
        reviewRenderFailed: "Это ошибка приложения. Сообщите о ней («Настройки → Помощь → Сообщить о проблеме»), чтобы её исправили.",
        scoreOf: "из 100",
        sourcesParsed: "Полный разбор реплея (OpenDota)",
        sourcesBasic: "Пока только итоги матча — полный разбор реплея ещё не готов",
        sourcesGsi: "Записано приложением во время матча",
        parseStatus: {
          waiting_opendota: "Полный разбор реплея будет через несколько минут (OpenDota).",
          parsing: "OpenDota изучает реплей — разбор дополнится сам.",
          basic: "Реплей не разобран: нет данных по минутам.",
          not_parsed: "OpenDota не смог изучить реплей, поэтому разбор короче.",
          gsi_only: "Есть только запись приложения (OpenDota выключен).",
          private: "Матч скрыт в OpenDota. В Доте: Настройки → Социальное → включите общий доступ к данным матчей (Expose Public Match Data) (сработает для следующих матчей); пока разбор строится по записи приложения.",
          "error:not_found": "OpenDota пока не знает этот матч — попробуйте через несколько минут.",
          "error:offline": "Нет интернета — показываем запись приложения.",
          "error:rate_limited": "OpenDota перегружен — попробуйте через минуту.",
          "error:bad_response": "OpenDota ответил ошибкой."
        },
        requestParse: "Запросить разбор реплея",
        parseRequested: "Запрос отправлен — обычно это 2–10 минут.",
        focusTitle: "Главное на следующую игру",
        sectionsTitle: "По разделам",
        explainTitle: "Что это значит?",
        explainScore:
          "Оценка от 0 до 100 — насколько матч похож на хорошую игру на вашей роли: линия, фарм, выживание, драки, предметы, а у саппорта ещё и обзор, у каждой части своя шкала. 65 и выше — хорошо (B), 80 и выше — отлично (A), ниже 50 — матч, на котором стоит поучиться (D). Победа или поражение на оценку не влияют: можно проиграть с 80 и выиграть с 30.",
        explainRank:
          "Подбор матчей собирает в одну игру игроков примерно одного ранга, поэтому игрок вашей роли в этом матче (из любой команды) показывает, как обычно играют на вашем ранге. Вы выше него — сыграли лучше своего ранга; ниже — есть куда расти.",
        explainFocus:
          "Фокус — одна ошибка, над которой вы работаете. После каждого матча тренер проверяет, повторилась ли она: зелёная отметка — не повторилась. Одну вещь исправить проще, чем всё сразу.",
        chartTitle: "По ходу матча",
        mapTitle: "Карта матча",
        deathsTitle: (count) => `Смерти · ${count}`,
        weekGames: "Матчи",
        weekVsPrevious: "к прошлой неделе",
        weekRecord: (w, l) => `${w} ${plural(w, "победа", "победы", "побед")} · ${l} ${plural(l, "поражение", "поражения", "поражений")}`,
        weekScoreNote: {
          no_score: "На этой неделе ещё нет разобранных матчей",
          no_previous: "Неделей раньше матчей не было — сравнить не с чем",
          no_previous_score: "Неделей раньше нет разобранных матчей"
        },
        weekChartTitle: "Оценка каждого матча за неделю",
        weekBest: "Лучший матч",
        weekHeroes: "Герои:",
        weekHeroTitle: (hero, games, wins) => `${hero}: матчей ${games}, побед ${wins}`,
        weekProblem: "Чаще всего:",
        weekProblemText: (title, count, of) => `${title} — в ${count} из ${of} матчей`,
        weekFocus: "Фокус:",
        weekPlanProgress: (met, played, plan) => `получилось ${met} из ${played} · план: ${plan} матча подряд`,
        weekPlanNext: "Следующий матч",
        sessionGames: "Матчи",
        sessionScore: "Средняя оценка",
        sessionVsUsual: "к обычной",
        sessionUsual: (score) => `Обычно: ${score}`,
        sessionNoScore: "Разборов пока нет",
        sessionTime: (minutes) => (minutes >= 60 ? `${Math.floor(minutes / 60)} ч ${String(minutes % 60).padStart(2, "0")} мин в игре` : `${minutes} мин в игре`),
        sessionDeaths: (deaths) => `смертей за матч в среднем: ${String(deaths).replace(".", ",")}`,
        sessionProblem: "Над чем работать:",
        sessionProblemText: (title, count, of) => `${title} — в ${count} из ${of}`,
        sessionFocus: (title, met, total) => `Фокус «${title}»: получилось в ${met} из ${total}`,
        sessionCopy: "Скопировать для друзей",
        sessionCopied: "Скопировано",
        sessionPreview: "Что скопируется",
        deathsNoPattern: "Повторяющейся причины у этих смертей нет.",
        deathNoFacts: "Больше об этой смерти ничего не известно.",
        deathGold: (gold) => `${gold} непотраченного золота`,
        deathAfterRespawn: (seconds) => `через ${seconds} с после возрождения`,
        deathWarned: (time, action) => `Тренер предупреждал в ${time}: «${action}»`,
        deathNote: {
          enemy_half: "на половине врага",
          unspent_gold: "с 1000+ непотраченного золота",
          warned: "после предупреждения",
          soon_after_respawn: "сразу после возрождения",
          saver_ready: "спасающий предмет был готов",
          burst: "убиты быстрее 3 с"
        },
        deathLastTitle: "Здоровье за последние 20 с",
        deathBurst: (seconds) => `С 70%+ здоровья до смерти за ${seconds} с`,
        deathReady: "Был готов и не нажат:",
        deathReadyStunned: "Был готов, но герой был в контроле:",
        deathZone: { top: "верхняя линия", mid: "центр", bot: "нижняя линия", jungle: "лес", base: "база" },
        mapEmpty: "Для этого матча пока нет позиций. Они берутся из разобранного реплея (приложение само просит OpenDota разобрать 5 последних матчей за неделю) или из матча, сыгранного с запущенным приложением: ваш путь и места смертей.",
        mapHint: {
          path: "Где был ваш герой (каждые 15 с, записало приложение) и где вы умирали.",
          replay: "По разобранному реплею: где вы стояли на линии, где ставили варды и где умирали в драках.",
          both: "Ваш путь (записало приложение), позиция на линии и варды из реплея, места смертей."
        },
        mapLabels: {
          radiant: "Силы Света",
          dire: "Силы Тьмы",
          death: "Смерть",
          observer: "Обзорный вард",
          sentry: "Сентри",
          path: "Ваш путь",
          lane: "Позиция на линии",
          spot: "Место, где умираете снова"
        },
        mapSpotTitle: (count, place) => `${count} ${plural(count, "смерть", "смерти", "смертей")} · ${place}`,
        mapSpotLine: (place, count) => `Чаще всего: ${place} (${count} ${plural(count, "смерть", "смерти", "смертей")})`,
        watchMoment: "Смотреть",
        watchMomentHint: "Копирует команду консоли Доты. Откройте запись этого матча в Доте, нажмите \\ (консоль) и вставьте: запись перемотается примерно за 10 с до этого момента.",
        watchCopied: "Скопировано: вставьте в консоль записи",
        watchFailed: "Не удалось скопировать",
        bestOnHeroLine: (score) => `Ваш лучший матч на герое (${score})`,
        bestOnHeroNote: (score, when) => `Пунктир — ваш лучший матч на этом герое, оценка ${score} (${when}).`,
        bestOnHeroSelf: (of) => `Это ваш лучший матч на этом герое из ${of}.`,
        mapDeaths: "Смерти",
        killedBy: (hero) => `Смерть от ${hero}`,
        mapSide: { own: "на своей половине", river: "у реки", enemy: "на половине противника" },
        mapWards: "Поставлено вардов",
        mapWardsLine: (obs, sen) => `${obs} обзорных · ${sen} сентри`,
        chartLh: "Добивания",
        chartGold: "Золото",
        chartXp: "Опыт",
        you: "Вы",
        target: "Хороший темп",
        deathsMarker: "Смерть",
        minuteLabel: (m) => `${m}:00`,
        strengthsTitle: "Что получилось",
        improveTitle: "Что улучшить",
        foldMore: (n) => `Показать ещё ${n}`,
        foldLess: "Свернуть",
        repeatInARow: (n) => `${n}-й матч подряд — это привычка, а не случайность`,
        repeatInLast: (n, of) => `Было и в ${n} из ${of} прошлых матчей`,
        nothingToImprove: "Серьёзных ошибок в этом матче не найдено.",
        nothingStrong: "В этот раз ничего не выделилось.",
        drill: "Упражнение",
        momentsTitle: "Ключевые моменты",
        adviceLogTitle: "Подсказки во время матча",
        adviceWhy: "Почему этот совет?",
        adviceLogHint: (n, urgent) => `${n} ${plural(n, "подсказка", "подсказки", "подсказок")} за игру, срочных — ${urgent}. Стоит проверить, получилось ли им следовать.`,
        adviceLogMore: (n) => `Показать все (${n})`,
        adviceLogDeath: (time) => `Смерть в ${time}`,
        momentDeath: (killer) => (killer ? `Смерть от ${killer}` : "Смерть"),
        momentGold: (gold) => `${gold} золота на руках`,
        momentItem: (item) => item,
        momentBuyback: "Байбэк",
        momentStall: (to) => `Провал в фарме до ${to}`,
        scoreboardTitle: "Итоги матча",
        radiant: "Силы Света",
        dire: "Силы Тьмы",
        colPlayer: "Игрок",
        colNw: "Стоимость",
        colDmg: "Урон",
        stats: {
          kda: "У / С / П",
          gpm: "Золото и опыт в минуту",
          lh: "Добивания / денаи",
          nw: "Стоимость героя",
          dmg: "Урон по героям",
          duration: "Длительность",
          items: "Предметы в конце"
        },
        sectionFacts: {
          laning: (s) => [s.lh10 != null && `${s.lh10} добиваний к 10:00`, s.lane_efficiency != null && `эффективность ${Math.round(s.lane_efficiency)}%`, s.lane_deaths ? `смертей на линии: ${s.lane_deaths}` : null, s.runes != null && `рун: ${s.runes}${s.enemy_runes != null ? ` (у вражеского мида ${s.enemy_runes})` : ""}`],
          farm: (s) => [s.gpm != null && `${s.gpm} золота в минуту`, s.gpm_pct != null && `лучше ${Math.round(s.gpm_pct * 100)}% игроков`],
          survival: (s) => [`смертей: ${s.deaths}`, s.deaths_per_10 != null && `${decimal(s.deaths_per_10)} за 10 мин`],
          fights: (s) => [s.kill_participation != null && `участие в убийствах ${s.kill_participation}%`, s.stuns != null && `оглушений ${decimal(s.stuns)} с${s.enemy_stuns != null ? ` (у вражеского хардлайнера ${decimal(s.enemy_stuns)} с)` : ""}`, s.enemy_tower_damage != null && s.tower_damage != null && `урон по строениям ${number(s.tower_damage)} (у вражеского хардлайнера ${number(s.enemy_tower_damage)})`],
          items: (s) => [
            s.first_item && `${s.first_item.item} к ${clock(s.first_item.t)}`,
            s.save_item && `Спасающий предмет: ${s.save_item.item} к ${clock(s.save_item.t)}`,
            "save_item" in s && !s.save_item && "Нет спасающего предмета"
          ],
          vision: (s) => [s.obs_placed != null && `обсерверов: ${s.obs_placed}`, s.sen_placed != null && `сентри: ${s.sen_placed}`, s.camps_stacked != null && `стаков: ${s.camps_stacked}`]
        },
        progressEmptyTitle: "Пока мало матчей",
        progressEmptyHint: "Статистика появится после нескольких разобранных матчей. Обновите историю на вкладке «Матчи».",
        tiles: { winrate: "Винрейт", kda: "KDA", gpm: "Золото в минуту", lh10: "Добивания к 10:00", score: "Средняя оценка" },
        vsPrevious: (n) => `к прошлым ${n}`,
        streakWin: (n) => `${n} ${plural(n, "победа", "победы", "побед")} подряд`,
        streakLoss: (n) => `${n} ${plural(n, "поражение", "поражения", "поражений")} подряд`,
        recordLine: (w, l, n) => `${w} ${plural(w, "победа", "победы", "побед")} и ${l} ${plural(l, "поражение", "поражения", "поражений")} за ${n} ${plural(n, "матч", "матча", "матчей")}`,
        scoreChartTitle: "Оценка по матчам",
        scoreChartHint: "Последние 20 матчей, старые слева. Нажмите на столбец, чтобы открыть разбор; нет столбца — у матча нет подробного разбора.",
        scoreLabel: "Оценка",
        winKey: "победа",
        lossKey: "поражение",
        baselineIntro: (games, hero) => `Против ваших ${games} ${plural(games, "другого матча", "других матчей", "других матчей")} на ${hero}:`,
        baselineLabels: { score: "оценка", gpm: "золото/мин", lh_10: "добиваний к 10", deaths: "смертей" },
        baselineSame: "как обычно",
        baselineTitle: (average) => `Ваш средний: ${average}`,
        goalTitle: "Ваш фокус",
        goalHint: "Одна проблема за раз: в каждом следующем матче видно, повторилась ли она.",
        goalSince: (date) => `с ${date}`,
        goalProgress: (met, total) => `Получилось в ${met} из ${total} ${plural(total, "матча", "матчей", "матчей")}`,
        goalWaiting: "Сыграйте матч — после него здесь будет видно, получилось ли.",
        goalStreak: (n) => `${n} ${plural(n, "матч", "матча", "матчей")} подряд без этой ошибки`,
        goalClear: "Снять фокус",
        goalSet: "Сделать фокусом",
        goalSetFailed: "Не удалось сохранить фокус, попробуйте ещё раз",
        goalCurrent: "Фокус",
        goalMet: "получилось",
        goalMissed: "повторилось",
        goalMatch: (title, met) => `Ваш фокус «${title}»: ${met ? "в этом матче получилось" : "снова повторилось"}`,
        planTitle: "Над чем работать",
        planHint: "Ошибки, которые повторяются в последних матчах, и по одному упражнению на каждую.",
        planEmpty: "Повторяющихся ошибок не найдено — так держать.",
        strengthsRecurring: "Ваши сильные стороны",
        heroesTitle: "Герои",
        colMatches: "Матчи",
        colWinrate: "Винрейт",
        analyzed: (a, n) => `Подробно разобрано ${a} из ${n} матчей`,
        buildTitle: "Сборка",
        lanesTitle: "Ваши линии",
        lanesLine: (won, even, lost, games) => `Из последних ${games} линий: выиграно ${won}, на равных ${even}, проиграно ${lost}.`,
        lanesGold: (diff) => `В среднем ${diff} золота против соперника по линии к 10-й минуте.`,
        lanesHard: (list) => `Линии, проигранные не раз, против: ${list}.`,
        lanesDot: (hero, enemy, result, diff) => `${hero} против ${enemy}: ${result.toLowerCase()}, ${diff} золота к 10-й минуте`,
        laneTitle: "Линия",
        laneVs: "против",
        laneResult: { won: "Линия выиграна", even: "Линия на равных", lost: "Линия проиграна" },
        laneMinute: (m) => `${m}:00`,
        laneColMinute: "Минута",
        laneColLh: "Добивания",
        laneColDn: "Денаи",
        laneColGold: "Золото",
        laneColXp: "Опыт",
        laneTurn: (m) => `Разрыв появился с ${m}-й минуты.`,
        laneOthers: (heroes, diff) => `Ещё на линии: ${heroes}; золото всей линии к 10-й минуте: ${diff}.`,
        laneNote: "Вы : соперник; золото и опыт — разница. По разобранной записи матча.",
        skillsTitle: "Прокачка",
        skillsYours: "Ваше первое:",
        skillsPro: "Как максят умения про-игроки на этом герое:",
        skillsSame: (name) => `Первым вы вкачали до конца ${name} — как и про-игроки.`,
        skillsDiff: (yours, pro) => `Первым вы вкачали до конца ${yours}, а про-игроки начинают с ${pro}.`,
        skillsNote: (agree, games) => `Так начинают ${agree} из ${games} недавних про-матчей. Подсказка в игре назовёт, куда вложить каждое очко.`,
        buildTimingNote: "Винрейт героя в зависимости от времени покупки (публичные матчи OpenDota). Ваш тайминг выделен. Самые ранние тайминги — чаще всего игры, которые и так шли хорошо, поэтому цель — обычный тайминг.",
        buildNoTimings: "По этим предметам пока нет данных о таймингах.",
        buildItemLine: (wr, t, typicalT, typicalWr) => `${wr}% побед при покупке к ${t} · обычно покупают к ${typicalT}: ${typicalWr}%`,
        buildItemTypical: (wr, t) => `${wr}% побед при покупке к ${t} · обычный тайминг для героя`,
        buildBy: (t) => `к ${t}`,
        buildPopular: "Частая сборка (про-игроки)",
        buildPhase: { early: "Начало", mid: "Основа", late: "Поздняя игра" },
        buildBought: "куплено",
        buildTimingTip: (t) => `Покупка к ${t}`,
        winrateLabel: "Винрейт",
        rankTitle: "Вы и ваш ранг",
        rankMatchNote: (rank, role, heroes) => `${rank ? `Ранг матча: ${rank} · ` : ""}сравнение с ${role} этого матча${heroes ? ` (${heroes})` : ""}`,
        rankNoPeers: "В этом матче нет игрока той же роли для сравнения.",
        colMetric: "Показатель",
        colYou: "Вы",
        colOpponent: "Соперник",
        colPeers: "Ваш ранг",
        colDiff: "Разница",
        metrics: { gpm: "Золото в минуту", xpm: "Опыт в минуту", lh_10: "Добивания к 10:00", lh_per_min: "Добиваний в минуту", deaths: "Смерти", kda: "KDA", damage_per_min: "Урон в минуту", net_worth: "Стоимость героя" },
        rankCareerTitle: "Вы и игроки вашего ранга",
        rankCareerNote: (rank, role, n) => `${rank || "Ваш ранг"} · ${role} · игроки той же роли в ваших ${n} разобранных матчах`,
        rankCareerEmpty: "Появится после нескольких матчей, разобранных по данным OpenDota.",
        colBracket: "На вашем ранге",
        bracketHint: (rank) => `Винрейт героя у всех игроков ранга ${rank} (OpenDota)`,
        shareButton: "Поделиться",
        shareTitle: "Поделиться разбором",
        shareWhat: "Страница с этим разбором: герой, результат, оценка, цифры матча, разделы и что улучшить. Открыть её сможет любой, у кого есть ссылка.",
        shareNot: "Не публикуется: номер матча, ваш Steam ID, ник и другие игроки. Ссылка работает 90 дней, её можно удалить в любой момент.",
        shareCoach: "Добавить вывод ИИ-тренера",
        shareCreate: "Создать ссылку",
        shareCreating: "Создаю ссылку…",
        shareLink: "Ссылка на разбор",
        shareCopy: "Копировать",
        shareCopied: "Скопировано.",
        shareOpen: "Открыть",
        shareDelete: "Удалить ссылку",
        shareDeleted: "Ссылка удалена.",
        shareExpires: (date) => `Работает до ${date}.`,
        shareWithCoach: "С выводом ИИ-тренера.",
        shareFailed: (code) => `Не получилось${code ? ` (${code})` : ""}: проверьте интернет и попробуйте ещё раз.`,
        shareTitleProgress: "Поделиться прогрессом",
        shareWhatProgress: "Страница с вашим прогрессом по всем героям: матчи, процент побед, средние цифры, последние 10 матчей против 10 до них, главные герои, что получается и над чем работать. Открыть её сможет любой, у кого есть ссылка.",
        shareNotProgress: "Не публикуется: номера матчей, ваш Steam ID, ник, другие игроки и ваши вопросы тренеру. Ссылка работает 90 дней, её можно удалить в любой момент.",
        shareLinkProgress: "Ссылка на прогресс",
        trendTitle: (item) => `${item}: тайминг по играм`,
        trendLine: (recent, n, before, m) => `Последние ${n} ${plural(n, "игра", "игры", "игр")}: ${recent}; ${m} ${plural(m, "игра", "игры", "игр")} до этого: ${before}.`,
        trendRecentOnly: (recent, n) => `Последние ${n} ${plural(n, "игра", "игры", "игр")}: ${recent} (медиана).`,
        trendSooner: (gap) => `на ${gap} раньше`,
        trendLater: (gap) => `на ${gap} позже`,
        trendSame: "примерно так же",
        trendMinute: "Минута",
        deathMapTitle: "Где вы умираете",
        deathMapNote: (matches, total, per) => `${total} ${plural(total, "смерть", "смерти", "смертей")} в ${matches} ${plural(matches, "матче", "матчах", "матчах")} с картой, ${String(per).replace(".", ",")} за матч.`,
        deathMapTurned: "Игры за Силы Тьмы повёрнуты на пол-оборота: ваша база всегда слева внизу.",
        deathMapSpot: (place, count, matches) => `${place}: ${count} ${plural(count, "смерть", "смерти", "смертей")} в ${matches} ${plural(matches, "матче", "матчах", "матчах")}`,
        deathMapSpots: "Здесь смерти повторяются:",
        deathMapLate: (pct) => `После 10-й минуты на половине противника: ${pct}% смертей`,
        opponentsTitle: "Вражеские герои",
        opponentsNote: (n, min) => `Ваш счёт против каждого вражеского героя в ${n} матчах с известным составом (герои, встреченные ${min}+ раза).`,
        opponentsHard: "Против них сложнее всего",
        opponentsEasy: "Их вы обыгрываете чаще всего",
        opponentRecord: (w, l, wr) => `${w}–${l} · ${wr}%`,
        poolTitle: "Ваш пул героев",
        poolNote: "Ваш процент побед на каждом герое (от 4 игр) против того, как на нём играют игроки вашего звания.",
        poolMore: "Играйте на них чаще",
        poolPark: "Их лучше пока отложить",
        poolRecord: (w, n, wr, br) => `${w} из ${n} побед · ${wr}%${br == null ? "" : ` (на вашем звании ${br}%)`}`,
        goalsTitle: "Ваши цели",
        streaksTitle: "Серии",
        goalMakeTop: (title) => `Сделать фокусом: ${title}`,
        zoneGoals: "Цели",
        zoneGoalsHint: "Над чем вы работаете и как прошли последние матчи",
        summaryLast: "Последний матч",
        summaryTip: "Главное исправить",
        summaryStrength: "Что получилось",
        summaryOpen: "Открыть разбор",
        summaryToday: "Сегодня",
        summaryNoGames: "Сегодня матчей ещё не было",
        summaryFocus: "Ваш фокус",
        summaryFocusProgress: (met, total) => `получилось в ${met} из ${total}`,
        summaryNoFocus: "Выберите одну проблему, над которой работать: тренер проверит по ней каждый матч.",
        summaryPickFocus: "Выбрать в «Прогрессе»",
        streakFewDeaths: (target) => `${target} ${plural(target, "матч", "матча", "матчей")} подряд — не больше 5 смертей`,
        streakGoodScore: (target) => `${target} ${plural(target, "матч", "матча", "матчей")} подряд с оценкой 60+`,
        streakProgress: (cur, target) => `${Math.min(cur, target)} из ${target}`,
        streakMet: (cur) => `выполнено: ${cur} подряд`,
        streakBest: (best) => `Лучшая серия за последние 30 матчей: ${best}`,
        tiltLosses: (n) => `${n} ${plural(n, "поражение", "поражения", "поражений")} подряд. Может, перерыв — или сыграйте что-нибудь просто для удовольствия.`,
        tiltScore: (a, b, usual) => `Две последние оценки — ${a} и ${b}, а обычно у вас около ${usual}. Может, сделать перерыв?`,
        friendTitle: "Сравнение с другом",
        friendHint: "Friend ID друга, Steam ID или ссылка на профиль (steamcommunity.com/profiles/…). Сравниваются открытые матчи из OpenDota: последние 20 игр каждого.",
        friendPlaceholder: "Friend ID, Steam ID или ссылка на профиль",
        friendCompare: "Сравнить",
        friendSelf: "Это ваш собственный аккаунт.",
        friendFailed: "Не удалось сохранить друга.",
        friendLoading: (name) => `Загружаю матчи ${name} из OpenDota…`,
        friendPrivate: (name) => `${name} скрывает данные матчей.`,
        friendPrivateHint: "Их можно открыть в Dota 2: Настройки → Сообщество → «Открыть данные матчей». Потом нажмите «Обновить» (OpenDota нужен хотя бы один матч после этого).",
        friendOffline: "Для сравнения нужен OpenDota (интернет).",
        friendError: (code) => `OpenDota не ответил${code ? ` (${code})` : ""}. Попробуйте «Обновить» позже.`,
        friendRefresh: "Обновить",
        friendUpdating: "Обновляю…",
        friendChange: "Другой друг",
        friendGroup: "Игры",
        friendGroups: { all: "Все игры", core: "Кор", support: "Саппорт" },
        friendYou: "Вы",
        friendGames: (me, friend) => `игр: у вас ${me}, у друга ${friend}`,
        friendFew: (n) => `Слишком мало игр, чтобы сказать, кто впереди: нужно ${n}+ у каждого.`,
        friendMetrics: { win_rate: "Процент побед", kills: "Убийства", deaths: "Смерти", assists: "Помощь", gpm: "Золото в минуту", xpm: "Опыт в минуту", lh_per_min: "Добивания в минуту", damage_per_min: "Урон по героям в минуту" },
        friendCommon: "Герои, на которых играли оба",
        friendHeroGames: (g1, w1, g2, w2) => `вы ${g1} · ${w1 ?? "—"}%   друг ${g2} · ${w2 ?? "—"}%`,
        friendTheirHeroes: (name) => `Чаще всего играет ${name}`,
        friendNote: "Средние за игру, открытые данные OpenDota, только рейтинговые и обычные режимы. Кор или саппорт — по добиваниям в минуту.",
        rankHistoryTitle: "Ваше звание",
        rankUp: (from, to, since) => `С ${since} вы поднялись с ${from} до ${to}.`,
        rankDown: (from, to, since) => `С ${since} звание снизилось с ${from} до ${to}.`,
        rankNote: "Приложение запоминает ваше звание каждый раз, когда обновляет историю, и отмечает, когда оно меняется.",
        heroBuildTitle: (hero) => `Ваш билд на ${hero}`,
        buildNote: (n, wins) => `Ваши предметы в ${n} разобранных матчах на герое (побед: ${wins}): когда они приходят в победах и в поражениях и как часто вы выигрываете с ними и без них.`,
        buildItem: "Предмет",
        buildGames: "Игр",
        buildWinrate: "Побед с ним",
        buildWithout: "Без него",
        buildWinTime: "В победах",
        buildLossTime: "В поражениях",
        selfTitle: (hero) => `Лучшие и худшие матчи на ${hero}`,
        selfNote: (n) => `Лучшая треть из ${n} последних разобранных матчей на герое против худшей трети, по оценке разбора.`,
        selfBest: "Лучшие",
        selfWorst: "Худшие",
        selfGroup: (count, wr) => `${count} матча · ${wr}% побед`,
        selfMetrics: {
          lh_10: "Добивания к 10:00",
          gpm: "Золото/мин",
          deaths: "Смерти",
          lane_deaths: "Смерти на линии",
          kill_participation: "Участие в убийствах",
          first_item_t: "Первый большой предмет"
        },
        draftTitle: "Драфт",
        draftNote: (hero) => `Как часто ${hero} побеждает каждого вражеского героя (статистика публичных матчей OpenDota).`,
        draftNoData: "Статистики по этим героям пока нет: она загрузится при следующем обновлении истории.",
        draftEnemy: "Враг",
        draftWinrate: "Ваш винрейт",
        draftGames: "игр",
        draftPool: "Ваши герои против этого состава",
        draftPoolNote: "Средний перевес по винрейту над 50% против этих пяти героев.",
        draftPicked: "ваш пик",
        draftBetter: (hero) => `Лучше всего против этого состава подходил ${hero}.`,
        draftCounters: "Ответы на вражеских героев",
        draftReasons: { evasion: "уклонение", illusions: "иллюзии", invisibility: "невидимость", healing: "лечение", targeted: "убивал контролем" },
        draftForSupports: "задача саппорта",
        draftBought: "куплен",
        coachTitle: "Разбор тренера",
        coachCareerTitle: "Разбор тренера по последним матчам",
        coachTag: "ИИ",
        coachPending: "Тренер пишет разбор. Это занимает до минуты.",
        coachCareerPending: "Тренер смотрит ваши последние матчи. Это занимает до минуты.",
        coachWaiting: "ИИ ждёт, пока OpenDota изучит реплей (обычно несколько минут): так у него больше данных.",
        coachNow: "Разобрать сейчас",
        coachUpdating: "Обновляется по новым данным…",
        coachRetry: "Повторить",
        coachRewrite: "Написать заново",
        coachNotEnough: (n) => `Тренеру нужно хотя бы ${n} разобранных матча.`,
        coachTurning: "Ключевые моменты",
        coachMistakes: "Главные ошибки",
        coachFix: "В следующий раз",
        coachStrengths: "Что получилось",
        coachNextGame: "Цели на следующую игру",
        coachPatterns: "Повторяющиеся проблемы",
        coachTrain: "Как тренировать",
        coachPlan: "План на следующие игры",
        coachFooter: (provider, model) => `Написано ИИ (${provider} · ${model}) по данным разбора. Числа, время, герои и предметы сверены с ними.`,
        coachErrors: {
          rate_limited: "Бесплатный лимит ИИ пока исчерпан. Попробуйте через несколько минут.",
          busy: "ИИ сейчас перегружен. Попробуйте через несколько минут.",
          invalid_key: "Ключ не подошёл. Проверьте его в настройках ИИ-тренера.",
          region: "Этот ИИ не работает из вашей страны. Выберите другой (например, OpenRouter) или включите VPN; ключ сохранён.",
          timeout: "ИИ слишком долго отвечал.",
          offline: "Нет связи с ИИ: проверьте интернет.",
          unverified: "В ответе ИИ были факты, которых нет в данных, поэтому он не показан. Попробуйте ещё раз.",
          bad_response: "ИИ ответил ошибкой. Попробуйте позже.",
          no_key: "Ключ ещё не указан."
        },
        askTitle: "Спросить тренера",
        askHint: "Вопрос об этом матче. Ответ строится только по данным матча и проходит ту же проверку фактов.",
        askPlaceholder: "Например: почему я проиграл линию?",
        askButton: "Спросить",
        askThinking: "Тренер думает…",
        askSuggestions: ["Что решило эту игру?", "Что изменить на линии?", "Вовремя ли я собрал предметы?"],
        askCareerHint: "Вопрос о ваших последних матчах: герои, противники, привычки. Ответ строится только по вашей статистике и проходит ту же проверку фактов.",
        askCareerPlaceholder: "Например: против каких героев мне сложнее всего?",
        askCareerSuggestions: ["Против каких героев мне сложнее всего?", "Какая ошибка стоит мне больше всего игр?", "На каком герое мне стоит играть чаще?"],
        askErrors: {
          unverified: "Тренер не смог ответить по данным этого матча. Попробуйте спросить иначе.",
          empty_question: "Сначала напишите вопрос.",
          no_review: "Разбор этого матча ещё не готов.",
          not_enough: "Пока мало разобранных матчей: сначала откройте несколько разборов.",
          off: "Сначала включите ИИ-тренера в настройках.",
          pending: "Ответ готовится дольше обычного. Спросите ещё раз через минуту — пока он готовится, повторный вопрос дождётся того же ответа.",
          bad_request: "Не удалось отправить вопрос. Спросите ещё раз."
        },
        aiSettingsTitle: "ИИ-тренер",
        aiOnTitle: "ИИ-тренер включён",
        aiCheckNow: "Проверить ключ",
        aiCheckOk: "Ключ работает.",
        aiOffTitle: "ИИ-тренер выключен",
        aiOffHint: "После каждого матча ИИ простыми словами объясняет, что получилось и что исправить, — как тренер, который посмотрел ваш реплей. Бесплатно: нужен только ключ от Google (Gemini), Groq или OpenRouter.",
        aiTurnOn: "Включить",
        aiSetupHint: "Ключ — это как пароль, с которым приложение может обращаться к ИИ. Получите бесплатный (минута, без карты) и вставьте сюда. ИИ только объясняет: все числа по-прежнему берутся из разбора. Данные матча (без вашего Steam ID) уходят на выбранный сайт.",
        aiService: "Откуда ключ",
        aiKey: "Ключ",
        aiKeyPlaceholder: "Вставьте ключ",
        aiModel: "Модель ИИ",
        aiAdvanced: "Для опытных",
        aiModelHint: "оставьте пустым — будет по умолчанию",
        aiGetKey: "Получить бесплатный ключ",
        aiSave: "Проверить и сохранить",
        aiChecking: "Проверяем ключ…",
        aiSaved: "Ключ работает. Тренер включён.",
        aiSavedWarn: (reason) => `Ключ сохранён, но проверка не прошла: ${reason}`,
        aiSettings: "Настройки ИИ",
        aiCurrent: (provider, model, hint) => [provider, model, hint ? `ключ ${hint}` : ""].filter(Boolean).join(" · "),
        aiEnvKey: "Ключ уже задан в файле настроек приложения.",
        aiChangeKey: "Сменить ключ",
        aiDisable: "Отключить",
        aiCancel: "Отмена"
      }
    };
    return TEXT;
  }

  const exported = { create };
  if (typeof module === "object" && module.exports) module.exports = exported;
  else window.WardlyMatchTexts = exported;
})();
