"use strict";

// UK/EN copy is independent of view state and DOM. Formatters are supplied by
// the view so numbers continue to follow its current locale after switching.
(function () {
  function create({ number, decimal, clock, plural }) {
    const TEXT = {
      en: {
        pfTitle: "Profile",
        pfSub: "Your rating, level and achievements with Wardly.",
        pfLevel: (n) => `Level ${n}`,
        pfXp: (into, need) => `${into} / ${need} XP to the next level`,
        pfSparks: "Sparks",
        pfSparksHint: "Earned by playing with the coach: 10 a match, 5 more for a win, more for every achievement tier. Spend them on profile looks.",
        pfGames: "Matches with Wardly",
        pfWithApp: "With the coach",
        pfNextBadge: "Closest award",
        pfWinrate: "Win rate",
        pfHours: "Hours with the coach",
        pfNoName: "Player",
        pfRating: "Rating",
        pfRatingNone: "Enter your MMR from Dota to start the graph: every ranked game then moves it.",
        pfRatingMedal: "Estimated from your medal. Enter your MMR from Dota for your own line.",
        pfRatingManual: (step) => `An estimate: a ranked game moves it by about ${step}. Correct it when it drifts from Dota.`,
        pfNow: "Now",
        pfPeak: "Peak",
        pfLast20: "Last 20 games",
        pfRecord: (w, l) => `${w}–${l}`,
        pfMmrLabel: "Your MMR now",
        pfMmrPlaceholder: "e.g. 3200",
        pfMmrSave: "Save",
        pfMmrClear: "Back to the medal estimate",
        pfMmrBad: "Enter a number from 0 to 15000.",
        pfWin: "Win",
        pfLoss: "Loss",
        pfAnchor: "Your number",
        pfAchievements: "Achievements",
        pfAchievementsHint: "For matches played with Wardly. Every tier gives sparks.",
        pfTierNone: "Not started",
        pfTier: (name, tier, tiers) => `${name} · ${tier}/${tiers}`,
        pfDone: "All tiers done",
        pfReward: (n) => `+${n} sparks`,
        pfProgress: (value, target) => `${value} / ${target}`,
        pfEmpty: "Play a match with Wardly running: it starts your level, achievements and sparks.",
        pfFriends: "Friends",
        pfFriendsHint: "Show your profile to friends by a code and see theirs: level, rating, looks and achievements.",
        pfFriendsOff: "Your profile is visible only to you. Show it, and friends who have your code see your card: name, level, medal, achievements, looks and matches with Wardly — no Steam ID and no match list.",
        pfFriendsShow: "Show my profile to friends",
        pfFriendsHide: "Hide my profile",
        pfFriendsCode: "Your friend code",
        pfFriendsCopy: "Copy code",
        pfFriendsCopyLink: "Copy link",
        pfFriendsOpen: "Open the page",
        pfFriendsCopied: "Copied.",
        pfFriendsShowMmr: "Show my rating",
        pfFriendsAdd: "Add",
        pfFriendsAddPlaceholder: "Friend code, e.g. WD-4K7P9QX2",
        pfFriendsEmpty: "No friends yet: send them your code, and add theirs.",
        pfFriendsYou: "You",
        pfFriendsRemove: "Remove",
        pfFriendsWeek: (n) => `${n} this week`,
        pfFriendsMissing: (codes) => `Hidden or not found: ${codes}`,
        pfFriendsErrors: { bad_code: "That is not a friend code.", own_code: "That is your own code.", already: "Already in the list.", too_many: "50 friends at most.", offline: "No connection to the server.", disabled: "Friends are switched off on the server for now.", rate_limited: "Too many requests: try again in an hour.", backend_down: "The coach service is not running." },
        pfShop: "Profile looks",
        pfShopHint: "Spend sparks on how your profile looks. Rare ones need a level or an achievement.",
        pfKinds: { frame: "Avatar frames", banner: "Banners", name: "Name colour", title: "Titles" },
        pfBuy: (price) => `Buy · ${price}`,
        pfWear: "Wear",
        pfWorn: "Worn",
        pfFree: "Free",
        pfNeedSparks: (n) => `${n} more ${n === 1 ? "spark" : "sparks"}`,
        pfLockedHint: "Not open yet: see the line above",
        pfNeedLevel: (n) => `From level ${n}`,
        pfNeedAchievement: (name, tier) => `For “${name}”, tier ${tier}`,
        pfShopErrors: { not_enough: "Not enough sparks yet.", locked_level: "Your level is too low for it.", locked_achievement: "It comes with an achievement.", owned: "You already have it." },
        linkTitle: "Link your Steam account",
        linkHint:
          "The coach reads your account from Dota automatically when you play. You can also paste your Friend ID (Dota profile), a steamcommunity.com/profiles/… link or an OpenDota/Dotabuff link.",
        linkPlaceholder: "Friend ID, Steam ID or profile link",
        linkButton: "Link",
        linkSoon: "Once your account is linked, here you get:",
        offlineStarting: "The coach is starting",
        offlineStartingHint: "A few seconds: this page opens by itself.",
        offlineTitle: "The coach is not answering",
        offlineHint: "Your matches and reviews are safe: they show again once the coach runs.",
        offlineStart: "Start the coach",
        newerMatch: "Newer",
        olderMatch: "Older",
        newerMatchHint: (hero) => `The newer match${hero ? ` (${hero})` : ""} · ←`,
        olderMatchHint: (hero) => `The older match${hero ? ` (${hero})` : ""} · →`,
        prevRowMatch: "Previous",
        nextRowMatch: "Next",
        prevRowMatchHint: (hero) => `The row above in the list${hero ? ` (${hero})` : ""} · ←`,
        nextRowMatchHint: (hero) => `The row below in the list${hero ? ` (${hero})` : ""} · →`,
        sortBy: (label) => `Sort by “${label}”: click again to flip the order`,
        openOnSite: (name) => `Open this match on ${name}`,
        progressSoon: "Once a few matches are reviewed, here you get:",
        linkPerks: {
          matches: [
            ["target", "every game with its score and what to fix first"],
            ["skull", "each death: the minute, the place and what was ready to press"],
            ["swords", "your build next to the pros and players of your rank"]
          ],
          progress: [
            ["trending-up", "your last 10 games against the 10 before"],
            ["repeat", "the mistakes that repeat, and one focus for the next game"],
            ["map", "your heroes, your lanes and where you die most"]
          ],
          profile: [
            ["chart-line", "your rating graph and your level"],
            ["trophy", "achievements and looks for your card"],
            ["users", "friends by code and a leaderboard"]
          ]
        },
        progressSub: "How your game changes from match to match",
        linkErrors: {
          empty: "Enter a Friend ID, Steam ID or profile link.",
          vanity_url: "Custom links (steamcommunity.com/id/…) can't be resolved. Use your Friend ID from the Dota profile.",
          unrecognized: "This doesn't look like a Steam account.",
          out_of_range: "This number is not a valid Steam account.",
          backend_down: "The coach is not running.",
          request_failed: "Could not link the account."
        },
        detected: (name) => `Playing now: ${name}.`,
        detectedLink: "Link this account",
        detectedOther: (name) => `Dota is running on another account: ${name}.`,
        switchAccount: "Switch",
        friendId: (id) => `Friend ID ${id}`,
        sourceLabel: { gsi: "detected in Dota", manual: "linked by hand", opendota: "OpenDota" },
        change: "Change",
        refresh: "Refresh",
        syncing: "Updating history…",
        syncedAt: (when) => `History updated ${when}`,
        syncNever: "History not loaded yet",
        syncOffline: "OpenDota is off — only matches recorded by the app are shown.",
        syncError: {
          offline: "No internet — showing matches recorded by the app.",
          private: "Match data is private. In Dota: Settings → Social → Expose Public Match Data.",
          rate_limited: "OpenDota is busy, try again in a minute.",
          not_found: "OpenDota doesn't know this account yet.",
          bad_response: "OpenDota answered with an error."
        },
        matchesTitle: "Matches",
        matchesSub: "Every game with its review: open one to see what to fix",
        matchesTableTitle: "Match history",
        progressTitle: "Progress",
        zoneFix: "What to fix",
        zoneFixHint: "The coach's review and the goal for the next game",
        zoneStory: "How the match went",
        zoneStoryHint: "Farm and gold over time, deaths, the advice you got",
        zoneScores: "Scores and comparison",
        zoneScoresHint: "Areas of the game, what went well, your rank",
        zoneMapItems: "Map and items",
        zoneMapItemsHint: "Where you were, what you bought and when",
        zoneTeams: "Teams",
        zoneSummary: "Summary",
        zoneSummaryHint: "Your last 10 matches against the 10 before",
        zoneCoach: "Coach",
        zoneCoachHint: "What keeps coming back and what to train",
        zoneGames: "Games and heroes",
        zoneGamesHint: "The score of every match and your heroes",
        zoneCompare: "Comparison",
        zoneCompareHint: "Players of your rank, enemy heroes, a friend",
        zoneHero: "Your main hero",
        zoneHeroHint: "Your best games against your worst, your build",
        sectionNav: "Page sections",
        openPlaceholder: "Match number or link",
        openButton: "Open",
        openBad: "No match number there: paste the number or an OpenDota, Dotabuff or STRATZ link.",
        openLoading: "Fetching the match from OpenDota…",
        openErrors: {
          not_player: "You did not play in this match (or your OpenDota profile hides it).",
          mode: "Turbo, bot games and the like are not reviewed.",
          not_found: "OpenDota does not know this match yet: check the number, or try again in a few minutes.",
          offline: "No connection to OpenDota: try again a little later.",
          rate_limited: "OpenDota is busy: try again in a minute.",
          unlinked: "Link your Steam account first.",
          pending: "OpenDota is still answering: try again in a minute.",
          error: "The match could not be fetched: try again a little later."
        },
        dialogClose: "Close",
        navFix: "Fix",
        navStory: "The match",
        navScores: "Scores",
        navMap: "Map and items",
        navTeams: "Teams",
        navSummary: "Summary",
        navGoals: "Goals",
        navCoach: "Coach",
        navGames: "Games",
        navCompare: "Comparison",
        navHero: "Main hero",
        colResult: "Result",
        colHero: "Hero",
        colKda: "K / D / A",
        colGpm: "Gold/min",
        colLh10: "Last hits by 10:00",
        colDuration: "Time",
        colScore: "Score",
        colItems: "Items",
        colWhen: "Played",
        win: "Win",
        loss: "Loss",
        unknownResult: "—",
        noMatchesTitle: "No matches yet",
        noMatchesHint: "Play a match with the coach running, or press Refresh to load your history from OpenDota.",
        more: "Show more",
        liveMatch: (hero) => `Recording the current match${hero ? ` (${hero})` : ""} — the review appears right after it ends.`,
        back: "Matches",
        palPlaceholder: "Where to go or what to do…",
        palEmpty: "Nothing found. Try a hero, a tab or a setting.",
        palHint: "↑↓ choose · Enter open · Esc close",
        palGroups: { tabs: "Tab", actions: "Action", heroes: "Progress", matches: "Match", settings: "Setting" },
        palProgressHero: (hero) => `Progress on ${hero}`,
        palSync: "Update the match history",
        palOpenNumber: "Open a match by its number",
        palHotkeys: "Hotkeys",
        palTour: "Show the tour",
        palReport: "Report a problem",
        noteAdd: "Add a note",
        noteAddHint: "Your own line on this match: lag, a new build, who you played with. Kept on this computer only.",
        noteEdit: "Edit the note",
        noteLabel: "Your note",
        notePlaceholder: "For example: lag, tried a new build",
        noteSave: "Save",
        noteCancel: "Cancel",
        noteFailed: "Could not save the note. Try again.",
        backTo: { home: "Home", matches: "Matches", progress: "Progress", profile: "Profile", settings: "Settings" },
        filterResult: "Result",
        filterResults: { all: "All", win: "Wins", loss: "Losses" },
        filterHero: "Hero",
        filterAllHeroes: "All heroes",
        filterSummary: (games, winrate, score) =>
          [`${games} ${games === 1 ? "match" : "matches"}`, winrate == null ? null : `${winrate}% wins`, score == null ? null : `average score ${score}`].filter(Boolean).join(" · "),
        skippedModes: (count, turbo, of) =>
          `${count} of your last ${of} games are not reviewed${turbo ? ` (Turbo: ${turbo})` : ""}: Turbo, bot games and special modes have different norms.`,
        filterEmptyTitle: "No matches for this filter",
        filterEmptyHint: "Pick another hero or result.",
        pdfSave: "Save PDF",
        pdfSaved: (name) => `Saved: ${name}`,
        pdfFailed: "Could not save the PDF",
        reviewLoading: "Loading the match…",
        reviewPending: "The review appears once the match data is loaded.",
        reviewError: "Could not open the match",
        reviewRetry: "Try again",
        matchErrors: {
          backend_down: "The coach is not running: the review opens once it runs again.",
          request_failed: "The coach did not answer in time. Try again in a few seconds.",
          match_not_found: "This match is no longer in your history."
        },
        reviewRenderFailed: "This is a bug in the app. Please report it (Settings → Help → Report a problem) so it can be fixed.",
        scoreOf: "of 100",
        sourcesParsed: "Full replay parsed by OpenDota",
        basisTitle: "What is this review based on?",
        basisRules: (v) => `Review rules: version ${v}.`,
        basisData: (list) => `Data: ${list}.`,
        basisDataParsed: "the replay parsed by OpenDota",
        basisDataOpenDota: "OpenDota match data (replay not parsed)",
        basisDataRecorded: "Wardly's own recording of the game",
        basisReason: {
          new: (when) => `Built on ${when}.`,
          rules: (when, from) => `Rebuilt on ${when}: the review rules changed${from ? ` (version ${from} before)` : ""}.`,
          data: (when) => `Rebuilt on ${when}: more data arrived.`
        },
        basisOld: "Built by an earlier version of Wardly; the details appear when it is next rebuilt.",
        basisHint: "Numbers the data cannot show are left out rather than guessed.",
        basisCareerRules: (n, v) => `All ${n} reviews are counted by the same rules (version ${v}).`,
        basisCareerPatches: (n) => `They span ${n} Dota patches: compare numbers across patches with care.`,
        basisCareerParsed: (parsed, n) => `${parsed} of ${n} have a parsed replay; some metrics exist only for those.`,
        sourcesBasic: "Match totals only — the full replay review is not ready yet",
        sourcesGsi: "Recorded by the app during the match",
        parseStatus: {
          waiting_opendota: "Full replay review in a few minutes (OpenDota).",
          parsing: "OpenDota is studying the replay — the review fills in by itself.",
          basic: "Replay not parsed: no minute-by-minute data.",
          not_parsed: "OpenDota could not study the replay, so the review is shorter.",
          gsi_only: "Only the app's own recording is available (OpenDota is off).",
          private: "This match is private on OpenDota. In Dota: Settings → Social → Expose Public Match Data (works for the next matches); the review uses the app's own recording meanwhile.",
          "error:not_found": "OpenDota doesn't have this match yet — try again in a few minutes.",
          "error:offline": "No internet — showing the app's own recording.",
          "error:rate_limited": "OpenDota is busy — try again in a minute.",
          "error:bad_response": "OpenDota answered with an error."
        },
        requestParse: "Request replay parse",
        parseRequested: "Requested — it usually takes 2–10 minutes.",
        focusTitle: "Focus for the next game",
        sectionsTitle: "Breakdown",
        explainTitle: "What does this mean?",
        explainScore:
          "The score (0 to 100) shows how close the match was to good play for your role: lane, farm, survival, fights, items and, for a support, vision, each on its own scale. 65+ is good (B), 80+ is great (A), under 50 is a match to learn from (D). A win or a loss does not change it: you can lose with 80 and win with 30.",
        explainRank:
          "Matchmaking puts players of about the same rank into one game, so the player of your role in this match (on either side) shows what is usual at your rank. Above them — you did better than your rank; below — there is room to grow.",
        explainFocus:
          "The focus is the one mistake you work on. After every match the coach checks whether it happened again: a green mark means it did not. One thing at a time is easier to fix than everything at once.",
        chartTitle: "Over the match",
        mapTitle: "Match map",
        deathsTitle: (count) => `Deaths · ${count}`,
        weekGames: "Matches",
        weekVsPrevious: "vs the week before",
        weekRecord: (w, l) => `${w}W · ${l}L`,
        weekScoreNote: {
          no_score: "No reviewed matches this week yet",
          no_previous: "No matches the week before to compare with",
          no_previous_score: "The week before has no reviewed matches"
        },
        weekChartTitle: "Score of every match this week",
        weekBest: "Best match",
        weekHeroes: "Heroes:",
        weekHeroTitle: (hero, games, wins) => `${hero}: ${games} ${games === 1 ? "match" : "matches"}, ${wins} ${wins === 1 ? "win" : "wins"}`,
        weekProblem: "Most often:",
        weekProblemText: (title, count, of) => `${title} — in ${count} of ${of} matches`,
        weekFocus: "Focus:",
        weekPlanProgress: (met, played, plan) => `${met} of ${played} done · plan: ${plan} matches in a row`,
        weekPlanNext: "Next match",
        sessionGames: "Matches",
        sessionScore: "Average score",
        sessionVsUsual: "vs your usual",
        sessionUsual: (score) => `Your usual: ${score}`,
        sessionNoScore: "No reviewed matches yet",
        sessionTime: (minutes) => (minutes >= 60 ? `${Math.floor(minutes / 60)} h ${String(minutes % 60).padStart(2, "0")} min played` : `${minutes} min played`),
        sessionDeaths: (deaths) => `deaths a match on average: ${deaths}`,
        sessionProblem: "To work on:",
        sessionProblemText: (title, count, of) => `${title} — in ${count} of ${of}`,
        sessionFocus: (title, met, total) => `Focus “${title}”: done in ${met} of ${total}`,
        sessionCopy: "Copy for friends",
        sessionCopied: "Copied",
        sessionPreview: "What will be copied",
        deathsNoPattern: "No repeating cause across these deaths.",
        deathNoFacts: "Nothing else is known about this death.",
        deathGold: (gold) => `${gold} unspent gold`,
        deathAfterRespawn: (seconds) => `${seconds} s after respawning`,
        deathWarned: (time, action) => `The coach warned at ${time}: “${action}”`,
        deathNote: {
          enemy_half: "on the enemy half",
          unspent_gold: "with 1000+ unspent gold",
          warned: "after a warning",
          soon_after_respawn: "right after respawning",
          saver_ready: "a saving item was ready",
          burst: "killed in under 3 s"
        },
        deathLastTitle: "HP in the last 20 s",
        deathBurst: (seconds) => `From 70%+ HP to death in ${seconds} s`,
        deathReady: "Ready and not used:",
        deathReadyStunned: "Ready, but you were disabled:",
        deathZone: { top: "top lane", mid: "mid lane", bot: "bottom lane", jungle: "jungle", base: "base" },
        mapEmpty: "No positions for this match yet. They come from a parsed replay (the app asks OpenDota to parse your 5 newest matches of the week) or from a match played with the app running: your path and where you died.",
        mapHint: {
          path: "Where your hero went (every 15 s, recorded by the app) and where you died.",
          replay: "From the parsed replay: where you stood in the lane, where you placed wards and where you died in team fights.",
          both: "Your path (recorded by the app), laning position, wards from the replay and where you died."
        },
        mapLabels: {
          radiant: "Radiant",
          dire: "Dire",
          death: "Death",
          observer: "Observer ward",
          sentry: "Sentry ward",
          path: "Your path",
          lane: "Laning position",
          spot: "Where deaths repeat"
        },
        mapSpotTitle: (count, place) => `${count} deaths · ${place}`,
        mapSpotLine: (place, count) => `Most often: ${place} (${count} ${count === 1 ? "death" : "deaths"})`,
        watchMoment: "Watch",
        watchMomentHint: "Copies a Dota console command. Open this match's replay in Dota, press \\ for the console and paste it: the replay jumps to about 10 s before this moment.",
        watchCopied: "Copied: paste in the replay console",
        watchFailed: "Could not copy",
        bestOnHeroLine: (score) => `Your best match on this hero (${score})`,
        bestOnHeroNote: (score, when) => `Dashed: your best match on this hero, score ${score} (${when}).`,
        bestOnHeroSelf: (of) => `This is your best match on this hero out of ${of}.`,
        mapDeaths: "Deaths",
        killedBy: (hero) => `Killed by ${hero}`,
        mapSide: { own: "on your half", river: "in the river", enemy: "on the enemy half" },
        mapWards: "Wards placed",
        mapWardsLine: (obs, sen) => `${obs} observer · ${sen} sentry`,
        chartLh: "Last hits",
        chartGold: "Gold earned",
        chartXp: "Experience",
        you: "You",
        target: "Target pace",
        deathsMarker: "Death",
        minuteLabel: (m) => `${m}:00`,
        strengthsTitle: "What went well",
        improveTitle: "What to improve",
        foldMore: (n) => `Show ${n} more`,
        foldLess: "Show less",
        repeatInARow: (n) => `${n} matches in a row — a habit, not bad luck`,
        repeatInLast: (n, of) => `Also in ${n} of your previous ${of} matches`,
        nothingToImprove: "No serious mistakes found in this match.",
        nothingStrong: "Nothing stood out this time.",
        drill: "Drill",
        momentsTitle: "Key moments",
        adviceLogTitle: "Advice during the match",
        adviceWhy: "Why this advice?",
        adviceRate: "Rate this advice (kept on this computer)",
        adviceVerdicts: { useful: "Useful", irrelevant: "Not to the point", repeated: "Repeated" },
        adviceRateHint: "Mark a few cards: «Useful», «Not to the point» or «Repeated». The marks stay on this computer and show which advice to fix.",
        adviceLogHint: (n, urgent) => `${n} ${n === 1 ? "tip" : "tips"} over the game, ${urgent} urgent. Worth checking whether you followed them.`,
        adviceLogMore: (n) => `Show all ${n}`,
        adviceLogDeath: (time) => `Died at ${time}`,
        momentDeath: (killer) => (killer ? `Died to ${killer}` : "Died"),
        momentGold: (gold) => `${gold} gold on hand`,
        momentItem: (item) => item,
        momentBuyback: "Buyback",
        momentStall: (to) => `Farm stall until ${to}`,
        scoreboardTitle: "Scoreboard",
        radiant: "Radiant",
        dire: "Dire",
        colPlayer: "Player",
        colNw: "Net worth",
        colDmg: "Damage",
        stats: {
          kda: "K / D / A",
          gpm: "Gold and XP per minute",
          lh: "Last hits / denies",
          nw: "Net worth",
          dmg: "Hero damage",
          duration: "Duration",
          items: "Items at the end"
        },
        sectionFacts: {
          laning: (s) => [s.lh10 != null && `${s.lh10} last hits by 10:00`, s.lane_efficiency != null && `lane efficiency ${Math.round(s.lane_efficiency)}%`, s.lane_deaths ? `${s.lane_deaths} deaths in lane` : null, s.runes != null && `${s.runes} runes${s.enemy_runes != null ? ` (enemy mid ${s.enemy_runes})` : ""}`],
          farm: (s) => [s.gpm != null && `${s.gpm} gold a minute`, s.gpm_pct != null && `better than ${Math.round(s.gpm_pct * 100)}%`],
          survival: (s) => [`${s.deaths} deaths`, s.deaths_per_10 != null && `${decimal(s.deaths_per_10)} per 10 min`],
          fights: (s) => [s.kill_participation != null && `${s.kill_participation}% kill participation`, s.stuns != null && `${decimal(s.stuns)} s of stuns${s.enemy_stuns != null ? ` (enemy offlaner ${decimal(s.enemy_stuns)} s)` : ""}`, s.enemy_tower_damage != null && s.tower_damage != null && `${number(s.tower_damage)} building damage (enemy offlaner ${number(s.enemy_tower_damage)})`],
          items: (s) => [
            s.first_item && `${s.first_item.item} at ${clock(s.first_item.t)}`,
            s.save_item && `Save item: ${s.save_item.item} at ${clock(s.save_item.t)}`,
            "save_item" in s && !s.save_item && "No save item"
          ],
          vision: (s) => [s.obs_placed != null && `${s.obs_placed} observers`, s.sen_placed != null && `${s.sen_placed} sentries`, s.camps_stacked != null && `${s.camps_stacked} stacks`]
        },
        progressEmptyTitle: "Not enough matches yet",
        progressEmptyHint: "Statistics appear after a few reviewed matches. Refresh your history on the Matches tab.",
        tiles: { winrate: "Win rate", kda: "KDA", gpm: "Gold per minute", lh10: "Last hits at 10:00", score: "Avg. score" },
        vsPrevious: (n) => `vs previous ${n}`,
        streakWin: (n) => `${n} wins in a row`,
        streakLoss: (n) => `${n} losses in a row`,
        recordLine: (w, l, n) => `${w}W – ${l}L over ${n} matches`,
        scoreChartTitle: "Score by match",
        scoreChartHint: "Last 20 matches, oldest on the left. Click a column to open the review; no column means the match has no detailed review.",
        scoreLabel: "Score",
        winKey: "win",
        lossKey: "loss",
        baselineIntro: (games, hero) => `Against your ${games} other ${games === 1 ? "match" : "matches"} on ${hero}:`,
        baselineLabels: { score: "score", gpm: "gold/min", lh_10: "last hits at 10", deaths: "deaths" },
        baselineSame: "as usual",
        baselineTitle: (average) => `Your average: ${average}`,
        goalTitle: "Your focus",
        goalHint: "One problem at a time: every next match shows whether it came back.",
        goalSince: (date) => `since ${date}`,
        goalProgress: (met, total) => `Done in ${met} of ${total} ${total === 1 ? "match" : "matches"}`,
        goalWaiting: "Play a match: after it you will see here whether it worked.",
        goalStreak: (n) => `${n} matches in a row without it`,
        goalClear: "Stop tracking",
        goalSet: "Make it my focus",
        goalSetFailed: "Could not save the focus, try again",
        goalCurrent: "Focus",
        goalMet: "done",
        goalMissed: "happened again",
        goalMatch: (title, met) => `Your focus “${title}”: ${met ? "done in this match" : "it happened again"}`,
        planTitle: "What to work on",
        planHint: "Problems that keep coming back in your recent matches, with one drill each.",
        planEmpty: "No repeated problems found — keep it up.",
        strengthsRecurring: "Your strengths",
        heroesTitle: "Heroes",
        colMatches: "Matches",
        colWinrate: "Win rate",
        analyzed: (a, n) => `${a} of ${n} matches reviewed in depth`,
        buildTitle: "Build",
        lanesTitle: "Your lanes",
        lanesLine: (won, even, lost, games) => `Of your last ${games} lanes: ${won} won, ${even} even, ${lost} lost.`,
        lanesGold: (diff) => `On average ${diff} gold against your lane opponent by minute 10.`,
        lanesHard: (list) => `Lanes lost more than once against: ${list}.`,
        lanesDot: (hero, enemy, result, diff) => `${hero} against ${enemy}: ${result}, ${diff} gold by minute 10`,
        laneTitle: "Lane",
        laneVs: "against",
        laneResult: { won: "Lane won", even: "Even lane", lost: "Lane lost" },
        laneMinute: (m) => `${m}:00`,
        laneColMinute: "Minute",
        laneColLh: "Last hits",
        laneColDn: "Denies",
        laneColGold: "Gold",
        laneColXp: "XP",
        laneTurn: (m) => `The gap opened at minute ${m}.`,
        laneOthers: (heroes, diff) => `Also in the lane: ${heroes}; the whole lane's gold by minute 10: ${diff}.`,
        laneNote: "You : them; gold and XP as the difference. From the parsed replay.",
        skillsTitle: "Skill order",
        skillsYours: "Yours first:",
        skillsPro: "How pros max their skills on this hero:",
        skillsSame: (name) => `You also maxed ${name} first, like the pros.`,
        skillsDiff: (yours, pro) => `You maxed ${yours} first; pros start with ${pro}.`,
        skillsNote: (agree, games) => `${agree} of ${games} recent pro games start this way. The in-game tip names where each point goes.`,
        buildTimingNote: "Win rate of the hero by purchase time (OpenDota public matches). Your timing is highlighted. The earliest timings mostly come from games that were already going well, so the target is the usual timing.",
        buildNoTimings: "No timing data for these items yet.",
        buildItemLine: (wr, t, typicalT, typicalWr) => `${wr}% wins when bought by ${t} · usually bought by ${typicalT} — ${typicalWr}%`,
        buildItemTypical: (wr, t) => `${wr}% wins when bought by ${t} · the usual timing for the hero`,
        buildBy: (t) => `by ${t}`,
        buildPopular: "Common build (pro players)",
        buildPhase: { early: "Early", mid: "Core", late: "Late" },
        buildBought: "bought",
        buildTimingTip: (t) => `Bought by ${t}`,
        winrateLabel: "Win rate",
        rankTitle: "You and your rank",
        rankMatchNote: (rank, role, heroes) => `${rank ? `Match rank: ${rank} · ` : ""}compared with the ${role} of this match${heroes ? ` (${heroes})` : ""}`,
        rankNoPeers: "No player of the same role in this match to compare with.",
        colMetric: "Metric",
        colYou: "You",
        colOpponent: "Opponent",
        colPeers: "Your rank",
        colDiff: "Difference",
        metrics: { gpm: "Gold per minute", xpm: "XP per minute", lh_10: "Last hits at 10:00", lh_per_min: "Last hits per minute", deaths: "Deaths", kda: "KDA", damage_per_min: "Damage per minute", net_worth: "Net worth" },
        rankCareerTitle: "You and players of your rank",
        rankCareerNote: (rank, role, n) => `${rank || "Your rank"} · ${role} · same-role players in your ${n} reviewed matches`,
        rankCareerEmpty: "Appears after a few matches reviewed with OpenDota data.",
        colBracket: "At your rank",
        bracketHint: (rank) => `Hero win rate among all ${rank} players (OpenDota)`,
        shareButton: "Share",
        shareTitle: "Share this review",
        shareWhat: "A page with this review: hero, result, score, the match numbers, the areas and what to improve. Anyone with the link can open it.",
        shareNot: "Not published: the match number, your Steam ID, nickname and the other players. The link works for 90 days, and you can delete it at any time.",
        shareCoach: "Add the AI coach's summary",
        shareCreate: "Create a link",
        shareCreating: "Creating the link…",
        shareLink: "Link to the review",
        shareCopy: "Copy",
        shareCopied: "Copied.",
        shareOpen: "Open",
        shareDelete: "Delete the link",
        shareDeleted: "The link is deleted.",
        shareExpires: (date) => `Works until ${date}.`,
        shareWithCoach: "With the AI coach's summary.",
        shareFailed: (code) => `Could not do it${code ? ` (${code})` : ""}: check the internet and try again.`,
        shareTitleProgress: "Share your progress",
        shareWhatProgress: "A page with your progress over all heroes: matches, win rate, averages, the last 10 against the 10 before, top heroes, what goes well and what to work on. Anyone with the link can open it.",
        shareNotProgress: "Not published: match numbers, your Steam ID, nickname, the other players and your questions to the coach. The link works for 90 days, and you can delete it at any time.",
        shareLinkProgress: "Link to your progress",
        trendTitle: (item) => `${item}: timing game by game`,
        trendLine: (recent, n, before, m) => `Last ${n} games: ${recent}; the ${m} before: ${before}.`,
        trendRecentOnly: (recent, n) => `Last ${n} games: ${recent} (median).`,
        trendSooner: (gap) => `${gap} sooner`,
        trendLater: (gap) => `${gap} later`,
        trendSame: "about the same",
        trendMinute: "Minute",
        deathMapTitle: "Where you die",
        deathMapNote: (matches, total, per) => `${total} ${total === 1 ? "death" : "deaths"} in ${matches} ${matches === 1 ? "match" : "matches"} with a map, ${per} a match.`,
        deathMapTurned: "Dire games are turned half a turn, so your base is always bottom left.",
        deathMapSpot: (place, count, matches) => `${place}: ${count} deaths in ${matches} matches`,
        deathMapSpots: "Deaths keep repeating here:",
        deathMapLate: (pct) => `After minute 10: ${pct}% of deaths on the enemy half`,
        opponentsTitle: "Enemy heroes",
        opponentsNote: (n, min) => `Your record against each enemy hero in ${n} matches with a known lineup (heroes met ${min}+ times).`,
        opponentsHard: "Hardest to play against",
        opponentsEasy: "You beat them most often",
        opponentRecord: (w, l, wr) => `${w}–${l} · ${wr}%`,
        poolTitle: "Your hero pool",
        poolNote: "Your win rate on each hero (4+ games) against how players of your rank do on it.",
        poolMore: "Play them more",
        poolPark: "Better to park them for now",
        poolRecord: (w, n, wr, br) => `${w} of ${n} won · ${wr}%${br == null ? "" : ` (your rank: ${br}%)`}`,
        goalsTitle: "Your goals",
        streaksTitle: "Streaks",
        goalMakeTop: (title) => `Make it the focus: ${title}`,
        zoneGoals: "Goals",
        zoneGoalsHint: "What you work on and how the last matches went",
        summaryLast: "Last match",
        summaryTip: "Main thing to fix",
        summaryStrength: "What went well",
        summaryOpen: "Open the review",
        summaryToday: "Today",
        summaryNoGames: "No matches yet today",
        summaryFocus: "Your focus",
        summaryFocusProgress: (met, total) => `done in ${met} of ${total}`,
        summaryNoFocus: "Pick one problem to work on: the coach checks every match against it.",
        summaryPickFocus: "Pick in Progress",
        streakFewDeaths: (target) => `${target} matches in a row with 5 deaths or fewer`,
        streakGoodScore: (target) => `${target} matches in a row with a score of 60+`,
        streakProgress: (cur, target) => `${Math.min(cur, target)} of ${target}`,
        streakMet: (cur) => `done: ${cur} in a row`,
        streakBest: (best) => `Your best run in the last 30 matches: ${best}`,
        tiltLosses: (n) => `${n} losses in a row. Maybe take a break, or play something just for fun.`,
        tiltScore: (a, b, usual) => `Your last two scores are ${a} and ${b}, while you usually get about ${usual}. Maybe take a break.`,
        friendTitle: "Compare with a friend",
        friendHint: "A friend's Friend ID, Steam ID or profile link (steamcommunity.com/profiles/…). Their public OpenDota matches are compared with yours: the last 20 games of each.",
        friendPlaceholder: "Friend ID, Steam ID or profile link",
        friendCompare: "Compare",
        friendSelf: "That is your own account.",
        friendFailed: "Could not save the friend.",
        friendLoading: (name) => `Loading the matches of ${name} from OpenDota…`,
        friendPrivate: (name) => `${name} hides their match data.`,
        friendPrivateHint: "They can allow it in Dota 2: Settings → Social → “Expose Public Match Data”. Then press Refresh (OpenDota needs a match played after that).",
        friendOffline: "The comparison needs OpenDota (internet).",
        friendError: (code) => `OpenDota did not answer${code ? ` (${code})` : ""}. Try Refresh later.`,
        friendRefresh: "Refresh",
        friendUpdating: "Updating…",
        friendChange: "Another friend",
        friendGroup: "Games",
        friendGroups: { all: "All games", core: "Core", support: "Support" },
        friendYou: "You",
        friendGames: (me, friend) => `games: you ${me}, friend ${friend}`,
        friendFew: (n) => `Too few games to say who is ahead: ${n}+ for each of you.`,
        friendMetrics: { win_rate: "Win rate", kills: "Kills", deaths: "Deaths", assists: "Assists", gpm: "Gold per minute", xpm: "XP per minute", lh_per_min: "Last hits per minute", damage_per_min: "Hero damage per minute" },
        friendCommon: "Heroes you both played",
        friendHeroGames: (g1, w1, g2, w2) => `you ${g1} · ${w1 ?? "—"}%   friend ${g2} · ${w2 ?? "—"}%`,
        friendTheirHeroes: (name) => `Most played by ${name}`,
        friendNote: "Averages per game, public OpenDota data, ranked and normal modes only. Core or support is judged by last hits a minute.",
        rankHistoryTitle: "Your rank medal",
        rankUp: (from, to, since) => `Up from ${from} to ${to} since ${since}.`,
        rankDown: (from, to, since) => `Down from ${from} to ${to} since ${since}.`,
        rankNote: "The app notes your medal every time it updates your history, and marks when it changes.",
        heroBuildTitle: (hero) => `Your build on ${hero}`,
        buildNote: (n, wins) => `Your items in ${n} reviewed games on the hero (${wins} wins): when they come in wins and in losses, and how often you win with and without them.`,
        buildItem: "Item",
        buildGames: "Games",
        buildWinrate: "Wins with it",
        buildWithout: "Without it",
        buildWinTime: "In wins",
        buildLossTime: "In losses",
        selfTitle: (hero) => `Your best vs your worst games on ${hero}`,
        selfNote: (n) => `The best third of your last ${n} reviewed games on the hero against the worst third, by review score.`,
        selfBest: "Best",
        selfWorst: "Worst",
        selfGroup: (count, wr) => `${count} games · ${wr}% wins`,
        selfMetrics: {
          lh_10: "Last hits at 10:00",
          gpm: "Gold/min",
          deaths: "Deaths",
          lane_deaths: "Lane deaths",
          kill_participation: "Kill participation",
          first_item_t: "First big item"
        },
        draftTitle: "Draft",
        draftNote: (hero) => `How often ${hero} wins against each enemy hero (public match statistics from OpenDota).`,
        draftNoData: "No statistics for these heroes yet: they load the next time your history updates.",
        draftEnemy: "Enemy",
        draftWinrate: "Your win rate",
        draftGames: "games",
        draftPool: "Your heroes against this lineup",
        draftPoolNote: "Average win rate edge over 50% against these five heroes.",
        draftPicked: "your pick",
        draftBetter: (hero) => `${hero} fit this lineup best.`,
        draftCounters: "Answers to the enemy heroes",
        draftReasons: { evasion: "evasion", illusions: "illusions", invisibility: "invisibility", healing: "healing", targeted: "killed you with a disable" },
        draftForSupports: "support's job",
        draftBought: "bought",
        coachTitle: "Coach's review",
        coachCareerTitle: "Coach's review of your recent games",
        coachTag: "AI",
        coachPending: "The coach is writing the review. It takes up to a minute.",
        coachCareerPending: "The coach is looking through your recent matches. It takes up to a minute.",
        coachWaiting: "The AI waits until OpenDota has studied the replay (usually a few minutes): then it has more to go on.",
        coachNow: "Review now",
        coachUpdating: "Updating with the new data…",
        coachRetry: "Try again",
        coachRewrite: "Rewrite",
        coachNotEnough: (n) => `The coach needs at least ${n} reviewed matches.`,
        coachTurning: "Turning points",
        coachMistakes: "Main mistakes",
        coachFix: "Next time",
        coachStrengths: "What went well",
        coachNextGame: "Goals for the next game",
        coachPatterns: "Recurring problems",
        coachTrain: "How to train it",
        coachPlan: "Plan for the next games",
        coachFooter: (provider, model) => `Written by AI (${provider} · ${model}) from the data of the review. Numbers, times, heroes and items are checked against it.`,
        coachErrors: {
          rate_limited: "The free AI limit is used up for now. Try again in a few minutes.",
          busy: "The AI is overloaded right now. Try again in a few minutes.",
          invalid_key: "The key did not work. Check it in the AI coach settings.",
          region: "This AI does not work from your country. Choose another one (OpenRouter, for example) or turn on a VPN; the key is kept.",
          timeout: "The AI took too long to answer.",
          offline: "No connection to the AI: check the internet.",
          unverified: "The AI answer mentioned facts that are not in the data, so it was not shown. Try again.",
          bad_response: "The AI answered with an error. Try again later.",
          no_key: "No key yet."
        },
        askTitle: "Ask the coach",
        askHint: "A question about this match. The answer uses only this match's data and goes through the same fact check.",
        askPlaceholder: "For example: why did I lose the lane?",
        askButton: "Ask",
        askThinking: "The coach is thinking…",
        askSuggestions: ["What decided this game for me?", "What should I change in the lane?", "Was my build on time?"],
        askCareerHint: "A question about your recent matches: heroes, enemies, habits. The answer uses only your statistics and goes through the same fact check.",
        askCareerPlaceholder: "For example: which enemy heroes are hardest for me?",
        askCareerSuggestions: ["Which enemy heroes are hardest for me?", "What mistake costs me the most games?", "Which hero should I play more?"],
        askErrors: {
          unverified: "The coach could not answer this from the match data. Try asking differently.",
          empty_question: "Type a question first.",
          no_review: "The review of this match is not ready yet.",
          not_enough: "Not enough reviewed matches yet: open a few reviews first.",
          off: "Turn the AI coach on in Settings first.",
          pending: "The answer is taking long. Ask again in a minute: while it is being prepared, asking again waits for the same answer.",
          bad_request: "This question could not be sent. Ask it again."
        },
        aiSettingsTitle: "AI coach",
        aiOnTitle: "AI coach is on",
        aiCheckNow: "Check key",
        aiCheckOk: "The key works.",
        aiOffTitle: "AI coach is off",
        aiOffHint: "After every match the AI explains in plain words what went well and what to fix, like a coach watching your replay. Free: you only need a key from Google (Gemini), Groq or OpenRouter.",
        aiTurnOn: "Turn on",
        aiSetupHint: "A key is like a password that lets the app use the AI. Get a free one (a minute, no card) and paste it here. The AI only explains: every number still comes from the review. Your match data (without your Steam ID) goes to the site you chose.",
        aiService: "Where the key is from",
        aiKey: "Key",
        aiKeyPlaceholder: "Paste the key",
        aiModel: "AI model",
        aiAdvanced: "For advanced users",
        aiModelHint: "leave empty for the default",
        aiGetKey: "Get a free key",
        aiSave: "Check and save",
        aiChecking: "Checking the key…",
        aiSaved: "The key works. The coach is on.",
        aiSavedWarn: (reason) => `Key saved, but the check failed: ${reason}`,
        aiSettings: "AI settings",
        aiCurrent: (provider, model, hint) => [provider, model, hint ? `key ${hint}` : ""].filter(Boolean).join(" · "),
        aiEnvKey: "A key is already set in the settings file of the app.",
        aiChangeKey: "Change key",
        aiDisable: "Turn off",
        aiCancel: "Cancel"
      },
      uk: {
        pfTitle: "Профіль",
        pfSub: "Ваш рейтинг, рівень і нагороди з Wardly.",
        pfLevel: (n) => `Рівень ${n}`,
        pfXp: (into, need) => `${into} / ${need} досвіду до наступного рівня`,
        pfSparks: "Іскри",
        pfSparksHint: "Даються за гру з тренером: 10 за матч, ще 5 за перемогу й більше за кожен щабель нагороди. Витрачаються на оформлення профілю.",
        pfGames: "Матчів з Wardly",
        pfWithApp: "З тренером",
        pfNextBadge: "Найближча нагорода",
        pfWinrate: "Відсоток перемог",
        pfHours: "Годин із тренером",
        pfNoName: "Гравець",
        pfRating: "Рейтинг",
        pfRatingNone: "Введіть свій MMR з Доти, щоб почати графік: далі його рухає кожна рейтингова гра.",
        pfRatingMedal: "Оцінка за медаллю. Введіть свій MMR з Доти — графік стане вашим.",
        pfRatingManual: (step) => `Це оцінка: рейтингова гра рухає його приблизно на ${step}. Виправте, якщо розійдеться з Дотою.`,
        pfNow: "Зараз",
        pfPeak: "Пік",
        pfLast20: "За 20 ігор",
        pfRecord: (w, l) => `${w}–${l}`,
        pfMmrLabel: "Ваш MMR зараз",
        pfMmrPlaceholder: "наприклад, 3200",
        pfMmrSave: "Зберегти",
        pfMmrClear: "Повернути оцінку за медаллю",
        pfMmrBad: "Введіть число від 0 до 15000.",
        pfWin: "Перемога",
        pfLoss: "Поразка",
        pfAnchor: "Ваше число",
        pfAchievements: "Нагороди",
        pfAchievementsHint: "За матчі, зіграні з Wardly. Кожен щабель дає іскри.",
        pfTierNone: "Не розпочато",
        pfTier: (name, tier, tiers) => `${name} · ${tier}/${tiers}`,
        pfDone: "Усі щаблі пройдено",
        pfReward: (n) => `+${n} іскор`,
        pfProgress: (value, target) => `${value} / ${target}`,
        pfEmpty: "Зіграйте матч із запущеним Wardly — з нього почнуться рівень, нагороди й іскри.",
        pfFriends: "Друзі",
        pfFriendsHint: "Покажіть профіль друзям за кодом і дивіться їхні: рівень, рейтинг, оформлення й нагороди.",
        pfFriendsOff: "Зараз ваш профіль бачите лише ви. Покажіть його — і друзі з вашим кодом побачать картку: нік, рівень, медаль, нагороди, оформлення й матчі з Wardly. Без Steam ID і списку матчів.",
        pfFriendsShow: "Показати профіль друзям",
        pfFriendsHide: "Сховати профіль",
        pfFriendsCode: "Ваш код друга",
        pfFriendsCopy: "Скопіювати код",
        pfFriendsCopyLink: "Скопіювати посилання",
        pfFriendsOpen: "Відкрити сторінку",
        pfFriendsCopied: "Скопійовано.",
        pfFriendsShowMmr: "Показувати мій рейтинг",
        pfFriendsAdd: "Додати",
        pfFriendsAddPlaceholder: "Код друга, наприклад WD-4K7P9QX2",
        pfFriendsEmpty: "Друзів поки немає: надішліть їм свій код і додайте їх.",
        pfFriendsYou: "Ви",
        pfFriendsRemove: "Прибрати",
        pfFriendsWeek: (n) => `${n} за тиждень`,
        pfFriendsMissing: (codes) => `Приховані або не знайдені: ${codes}`,
        pfFriendsErrors: { bad_code: "Це не код друга.", own_code: "Це ваш власний код.", already: "Уже в списку.", too_many: "Не більше 50 друзів.", offline: "Немає зв'язку із сервером.", disabled: "Друзів на сервері зараз вимкнено.", rate_limited: "Забагато запитів: спробуйте за годину.", backend_down: "Службу тренера не запущено." },
        pfShop: "Оформлення",
        pfShopHint: "Витрачайте іскри на вигляд профілю. Рідкісні речі відкриваються з рівнем або за нагороду.",
        pfKinds: { frame: "Рамки аватара", banner: "Банери", name: "Колір ніка", title: "Титули" },
        pfBuy: (price) => `Купити · ${price}`,
        pfWear: "Одягнути",
        pfWorn: "Одягнено",
        pfFree: "Безкоштовно",
        pfNeedSparks: (n) => `Ще ${n} ${plural(n, "іскра", "іскри", "іскор")}`,
        pfLockedHint: "Поки закрито: умову написано вище",
        pfNeedLevel: (n) => `З ${n}-го рівня`,
        pfNeedAchievement: (name, tier) => `За нагороду «${name}», щабель ${tier}`,
        pfShopErrors: { not_enough: "Поки бракує іскор.", locked_level: "Потрібен вищий рівень.", locked_achievement: "Дається за нагороду.", owned: "Уже є." },
        linkTitle: "Прив'яжіть акаунт Steam",
        linkHint:
          "Тренер сам дізнається ваш акаунт з Доти, коли ви граєте. Можна й вручну: Friend ID із профілю в Доті, посилання steamcommunity.com/profiles/… або посилання на OpenDota/Dotabuff.",
        linkPlaceholder: "Friend ID, Steam ID або посилання на профіль",
        linkButton: "Прив'язати",
        linkSoon: "Коли акаунт прив'язано, тут будуть:",
        offlineStarting: "Тренер запускається",
        offlineStartingHint: "Кілька секунд — сторінка відкриється сама.",
        offlineTitle: "Тренер не відповідає",
        offlineHint: "Ваші матчі й розбори на місці: вони з'являться, коли тренер знову запрацює.",
        offlineStart: "Запустити тренера",
        newerMatch: "Новіший",
        olderMatch: "Старіший",
        newerMatchHint: (hero) => `Новіший матч${hero ? ` (${hero})` : ""} · ←`,
        olderMatchHint: (hero) => `Старіший матч${hero ? ` (${hero})` : ""} · →`,
        prevRowMatch: "Попередній",
        nextRowMatch: "Наступний",
        prevRowMatchHint: (hero) => `Рядок вище в списку${hero ? ` (${hero})` : ""} · ←`,
        nextRowMatchHint: (hero) => `Рядок нижче в списку${hero ? ` (${hero})` : ""} · →`,
        sortBy: (label) => `Сортувати за «${label}»: натисніть ще раз, щоб перевернути`,
        openOnSite: (name) => `Відкрити цей матч на ${name}`,
        progressSoon: "Коли розібраних матчів стане більше, тут будуть:",
        linkPerks: {
          matches: [
            ["target", "усі ваші ігри з оцінкою й тим, що виправити насамперед"],
            ["skull", "кожна смерть: хвилина, місце й що було готове до натискання"],
            ["swords", "ваш білд поруч із про-гравцями й гравцями вашого рангу"]
          ],
          progress: [
            ["trending-up", "останні 10 ігор проти 10 ігор до них"],
            ["repeat", "помилки, що повторюються, і один фокус на наступну гру"],
            ["map", "ваші герої, ваші лінії й де ви помираєте найчастіше"]
          ],
          profile: [
            ["chart-line", "графік рейтингу й ваш рівень"],
            ["trophy", "нагороди й оформлення вашої картки"],
            ["users", "друзі за кодом і таблиця лідерів"]
          ]
        },
        progressSub: "Як змінюється ваша гра від матчу до матчу",
        linkErrors: {
          empty: "Введіть Friend ID, Steam ID або посилання на профіль.",
          vanity_url: "Короткі посилання (steamcommunity.com/id/…) не розпізнати. Візьміть Friend ID із профілю в Доті.",
          unrecognized: "Це не схоже на акаунт Steam.",
          out_of_range: "Такого акаунта Steam не буває.",
          backend_down: "Тренера не запущено.",
          request_failed: "Не вдалося прив'язати акаунт."
        },
        detected: (name) => `Зараз у Доті: ${name}.`,
        detectedLink: "Прив'язати цей акаунт",
        detectedOther: (name) => `У Доті інший акаунт: ${name}.`,
        switchAccount: "Перемкнутися",
        friendId: (id) => `Friend ID ${id}`,
        sourceLabel: { gsi: "знайдено в Доті", manual: "прив'язано вручну", opendota: "OpenDota" },
        change: "Змінити",
        refresh: "Оновити",
        syncing: "Оновлюємо історію…",
        syncedAt: (when) => `Історію оновлено ${when}`,
        syncNever: "Історію ще не завантажено",
        syncOffline: "OpenDota вимкнено — видно лише матчі, записані застосунком.",
        syncError: {
          offline: "Немає інтернету — показуємо матчі, записані застосунком.",
          private: "Дані матчів приховано. У Доті: Налаштування → Соціальне → увімкніть загальний доступ до даних матчів (Expose Public Match Data).",
          rate_limited: "OpenDota перевантажено, спробуйте за хвилину.",
          not_found: "OpenDota поки не знає цей акаунт.",
          bad_response: "OpenDota відповів помилкою."
        },
        matchesTitle: "Матчі",
        matchesSub: "Усі ігри з розборами: відкрийте матч, щоб побачити, що виправити",
        matchesTableTitle: "Історія матчів",
        progressTitle: "Прогрес",
        zoneFix: "Що виправити",
        zoneFixHint: "Розбір тренера й мета на наступну гру",
        zoneStory: "Як ішов матч",
        zoneStoryHint: "Фарм і золото протягом гри, смерті, ваші підказки",
        zoneScores: "Оцінки й порівняння",
        zoneScoresHint: "Розділи гри, що вдалося, ваш ранг",
        zoneMapItems: "Мапа й предмети",
        zoneMapItemsHint: "Де ви були, що й коли купили",
        zoneTeams: "Склади",
        zoneSummary: "Підсумки",
        zoneSummaryHint: "Останні 10 матчів проти 10 попередніх",
        zoneCoach: "Тренер",
        zoneCoachHint: "Що повторюється й що тренувати",
        zoneGames: "Матчі й герої",
        zoneGamesHint: "Оцінка кожного матчу й ваші герої",
        zoneCompare: "Порівняння",
        zoneCompareHint: "Гравці вашого рангу, ворожі герої, друг",
        zoneHero: "Ваш основний герой",
        zoneHeroHint: "Найкращі ігри проти найгірших, ваш білд",
        sectionNav: "Розділи сторінки",
        openPlaceholder: "Номер або посилання на матч",
        openButton: "Відкрити",
        openBad: "Не бачу номера матчу: вставте номер або посилання OpenDota, Dotabuff чи STRATZ.",
        openLoading: "Завантажую матч з OpenDota…",
        openErrors: {
          not_player: "Вас немає в цьому матчі (або ваш профіль OpenDota приховано).",
          mode: "Турбо, ігри з ботами й подібні режими не розбираються.",
          not_found: "OpenDota поки не знає цей матч: перевірте номер або спробуйте за кілька хвилин.",
          offline: "Немає зв'язку з OpenDota: спробуйте трохи пізніше.",
          rate_limited: "OpenDota перевантажено: спробуйте за хвилину.",
          unlinked: "Спершу прив'яжіть акаунт Steam.",
          pending: "OpenDota ще відповідає: спробуйте за хвилину.",
          error: "Не вдалося завантажити матч: спробуйте трохи пізніше."
        },
        dialogClose: "Закрити",
        navFix: "Виправити",
        navStory: "Перебіг матчу",
        navScores: "Оцінки",
        navMap: "Мапа й предмети",
        navTeams: "Склади",
        navSummary: "Підсумки",
        navGoals: "Цілі",
        navCoach: "Тренер",
        navGames: "Матчі",
        navCompare: "Порівняння",
        navHero: "Герой",
        colResult: "Підсумок",
        colHero: "Герой",
        colKda: "В / С / Д",
        colGpm: "Золото/хв",
        colLh10: "Добив. до 10",
        colDuration: "Час",
        colScore: "Оцінка",
        colItems: "Предмети",
        colWhen: "Коли",
        win: "Перемога",
        loss: "Поразка",
        unknownResult: "—",
        noMatchesTitle: "Матчів поки немає",
        noMatchesHint: "Зіграйте матч із запущеним тренером або натисніть «Оновити», щоб завантажити історію з OpenDota.",
        more: "Показати ще",
        liveMatch: (hero) => `Записуємо поточний матч${hero ? ` (${hero})` : ""} — розбір з'явиться одразу після нього.`,
        back: "Матчі",
        palPlaceholder: "Куди перейти чи що зробити…",
        palEmpty: "Нічого не знайшлося. Спробуйте героя, вкладку або налаштування.",
        palHint: "↑↓ обрати · Enter відкрити · Esc закрити",
        palGroups: { tabs: "Вкладка", actions: "Дія", heroes: "Прогрес", matches: "Матч", settings: "Налаштування" },
        palProgressHero: (hero) => `Прогрес на ${hero}`,
        palSync: "Оновити історію матчів",
        palOpenNumber: "Відкрити матч за номером",
        palHotkeys: "Гарячі клавіші",
        palTour: "Показати навчання",
        palReport: "Повідомити про проблему",
        noteAdd: "Нотатка",
        noteAddHint: "Ваш рядок до цього матчу: лагало, новий білд, з ким грали. Зберігається лише на цьому комп'ютері.",
        noteEdit: "Змінити нотатку",
        noteLabel: "Ваша нотатка",
        notePlaceholder: "Наприклад: лагало, пробував новий білд",
        noteSave: "Зберегти",
        noteCancel: "Скасувати",
        noteFailed: "Не вдалося зберегти нотатку. Спробуйте ще раз.",
        backTo: { home: "Головна", matches: "Матчі", progress: "Прогрес", profile: "Профіль", settings: "Налаштування" },
        filterResult: "Результат",
        filterResults: { all: "Усі", win: "Перемоги", loss: "Поразки" },
        filterHero: "Герой",
        filterAllHeroes: "Усі герої",
        filterSummary: (games, winrate, score) =>
          [`${games} ${plural(games, "матч", "матчі", "матчів")}`, winrate == null ? null : `${winrate}% перемог`, score == null ? null : `середня оцінка ${score}`].filter(Boolean).join(" · "),
        skippedModes: (count, turbo, of) =>
          `Не розбираємо ${count} з ${of} останніх ігор${turbo ? ` (Турбо: ${turbo})` : ""}: у Турбо, іграх із ботами й особливих режимах інші норми.`,
        filterEmptyTitle: "Немає матчів під цей фільтр",
        filterEmptyHint: "Оберіть іншого героя або результат.",
        pdfSave: "Зберегти PDF",
        pdfSaved: (name) => `Збережено: ${name}`,
        pdfFailed: "Не вдалося зберегти PDF",
        reviewLoading: "Завантажуємо матч…",
        reviewPending: "Розбір з'явиться, коли завантажаться дані матчу.",
        reviewError: "Не вдалося відкрити матч",
        reviewRetry: "Спробувати ще раз",
        matchErrors: {
          backend_down: "Тренера зараз не запущено: розбір відкриється, коли він знову запрацює.",
          request_failed: "Тренер не встиг відповісти. Спробуйте ще раз за кілька секунд.",
          match_not_found: "Цього матчу більше немає в історії."
        },
        reviewRenderFailed: "Це помилка застосунку. Повідомте про неї («Налаштування → Допомога → Повідомити про проблему»), щоб її виправили.",
        scoreOf: "зі 100",
        sourcesParsed: "Повний розбір реплею (OpenDota)",
        basisTitle: "На чому ґрунтується розбір?",
        basisRules: (v) => `Правила розбору: версія ${v}.`,
        basisData: (list) => `Дані: ${list}.`,
        basisDataParsed: "реплей, розібраний OpenDota",
        basisDataOpenDota: "дані матчу OpenDota (реплей не розібрано)",
        basisDataRecorded: "власний запис гри Wardly",
        basisReason: {
          new: (when) => `Зібрано ${when}.`,
          rules: (when, from) => `Перераховано ${when}: правила розбору оновилися${from ? ` (була версія ${from})` : ""}.`,
          data: (when) => `Перераховано ${when}: надійшли нові дані.`
        },
        basisOld: "Зібрано попередньою версією Wardly; подробиці з'являться під час наступного перерахунку.",
        basisHint: "Те, чого немає в даних, не вгадується, а пропускається.",
        basisCareerRules: (n, v) => `Усі ${n} розборів пораховано за одними правилами (версія ${v}).`,
        basisCareerPatches: (n) => `Вони з ${n} різних патчів Dota: цифри між патчами порівнюйте обережно.`,
        basisCareerParsed: (parsed, n) => `Розібраний реплей є в ${parsed} з ${n}; частина метрик рахується лише за ними.`,
        sourcesBasic: "Поки лише підсумки матчу — повний розбір реплею ще не готовий",
        sourcesGsi: "Записано застосунком під час матчу",
        parseStatus: {
          waiting_opendota: "Повний розбір реплею буде за кілька хвилин (OpenDota).",
          parsing: "OpenDota вивчає реплей — розбір доповниться сам.",
          basic: "Реплей не розібрано: немає даних по хвилинах.",
          not_parsed: "OpenDota не зміг вивчити реплей, тому розбір коротший.",
          gsi_only: "Є лише запис застосунку (OpenDota вимкнено).",
          private: "Матч приховано в OpenDota. У Доті: Налаштування → Соціальне → увімкніть загальний доступ до даних матчів (Expose Public Match Data) (спрацює для наступних матчів); поки розбір будується за записом застосунку.",
          "error:not_found": "OpenDota поки не знає цей матч — спробуйте за кілька хвилин.",
          "error:offline": "Немає інтернету — показуємо запис застосунку.",
          "error:rate_limited": "OpenDota перевантажено — спробуйте за хвилину.",
          "error:bad_response": "OpenDota відповів помилкою."
        },
        requestParse: "Запросити розбір реплею",
        parseRequested: "Запит надіслано — зазвичай це 2–10 хвилин.",
        focusTitle: "Головне на наступну гру",
        sectionsTitle: "За розділами",
        explainTitle: "Що це означає?",
        explainScore:
          "Оцінка від 0 до 100 — наскільки матч схожий на добру гру на вашій ролі: лінія, фарм, виживання, бійки, предмети, а в саппорта ще й огляд, у кожної частини своя шкала. 65 і вище — добре (B), 80 і вище — чудово (A), нижче 50 — матч, на якому варто повчитися (D). Перемога чи поразка на оцінку не впливають: можна програти з 80 і виграти з 30.",
        explainRank:
          "Підбір матчів збирає в одну гру гравців приблизно одного рангу, тому гравець вашої ролі в цьому матчі (з будь-якої команди) показує, як зазвичай грають на вашому ранзі. Ви вище за нього — зіграли краще за свій ранг; нижче — є куди рости.",
        explainFocus:
          "Фокус — одна помилка, над якою ви працюєте. Після кожного матчу тренер перевіряє, чи повторилася вона: зелена позначка — не повторилася. Одну річ виправити легше, ніж усе одразу.",
        chartTitle: "Протягом матчу",
        mapTitle: "Мапа матчу",
        deathsTitle: (count) => `Смерті · ${count}`,
        weekGames: "Матчі",
        weekVsPrevious: "до минулого тижня",
        weekRecord: (w, l) => `${w} ${plural(w, "перемога", "перемоги", "перемог")} · ${l} ${plural(l, "поразка", "поразки", "поразок")}`,
        weekScoreNote: {
          no_score: "Цього тижня ще немає розібраних матчів",
          no_previous: "Тижнем раніше матчів не було — порівняти нема з чим",
          no_previous_score: "Тижнем раніше немає розібраних матчів"
        },
        weekChartTitle: "Оцінка кожного матчу за тиждень",
        weekBest: "Найкращий матч",
        weekHeroes: "Герої:",
        weekHeroTitle: (hero, games, wins) => `${hero}: матчів ${games}, перемог ${wins}`,
        weekProblem: "Найчастіше:",
        weekProblemText: (title, count, of) => `${title} — у ${count} з ${of} матчів`,
        weekFocus: "Фокус:",
        weekPlanProgress: (met, played, plan) => `вдалося ${met} з ${played} · план: ${plan} матчі поспіль`,
        weekPlanNext: "Наступний матч",
        sessionGames: "Матчі",
        sessionScore: "Середня оцінка",
        sessionVsUsual: "до звичайної",
        sessionUsual: (score) => `Зазвичай: ${score}`,
        sessionNoScore: "Розборів поки немає",
        sessionTime: (minutes) => (minutes >= 60 ? `${Math.floor(minutes / 60)} год ${String(minutes % 60).padStart(2, "0")} хв у грі` : `${minutes} хв у грі`),
        sessionDeaths: (deaths) => `смертей за матч у середньому: ${String(deaths).replace(".", ",")}`,
        sessionProblem: "Над чим працювати:",
        sessionProblemText: (title, count, of) => `${title} — у ${count} з ${of}`,
        sessionFocus: (title, met, total) => `Фокус «${title}»: вдалося в ${met} з ${total}`,
        sessionCopy: "Скопіювати для друзів",
        sessionCopied: "Скопійовано",
        sessionPreview: "Що скопіюється",
        deathsNoPattern: "Повторюваної причини в цих смертей немає.",
        deathNoFacts: "Більше про цю смерть нічого не відомо.",
        deathGold: (gold) => `${gold} невитраченого золота`,
        deathAfterRespawn: (seconds) => `через ${seconds} с після відродження`,
        deathWarned: (time, action) => `Тренер попереджав о ${time}: «${action}»`,
        deathNote: {
          enemy_half: "на половині ворога",
          unspent_gold: "з 1000+ невитраченого золота",
          warned: "після попередження",
          soon_after_respawn: "одразу після відродження",
          saver_ready: "рятівний предмет був готовий",
          burst: "убиті швидше за 3 с"
        },
        deathLastTitle: "Здоров'я за останні 20 с",
        deathBurst: (seconds) => `Із 70%+ здоров'я до смерті за ${seconds} с`,
        deathReady: "Був готовий і не натиснутий:",
        deathReadyStunned: "Був готовий, але герой був під контролем:",
        deathZone: { top: "верхня лінія", mid: "центр", bot: "нижня лінія", jungle: "ліс", base: "база" },
        mapEmpty: "Для цього матчу поки немає позицій. Вони беруться з розібраного реплею (застосунок сам просить OpenDota розібрати 5 останніх матчів за тиждень) або з матчу, зіграного із запущеним застосунком: ваш шлях і місця смертей.",
        mapHint: {
          path: "Де був ваш герой (кожні 15 с, записав застосунок) і де ви помирали.",
          replay: "За розібраним реплеєм: де ви стояли на лінії, де ставили варди й де помирали в бійках.",
          both: "Ваш шлях (записав застосунок), позиція на лінії й варди з реплею, місця смертей."
        },
        mapLabels: {
          radiant: "Сили Світла",
          dire: "Сили Темряви",
          death: "Смерть",
          observer: "Оглядовий вард",
          sentry: "Сентрі",
          path: "Ваш шлях",
          lane: "Позиція на лінії",
          spot: "Місце, де помираєте знову"
        },
        mapSpotTitle: (count, place) => `${count} ${plural(count, "смерть", "смерті", "смертей")} · ${place}`,
        mapSpotLine: (place, count) => `Найчастіше: ${place} (${count} ${plural(count, "смерть", "смерті", "смертей")})`,
        watchMoment: "Дивитися",
        watchMomentHint: "Копіює команду консолі Доти. Відкрийте запис цього матчу в Доті, натисніть \\ (консоль) і вставте: запис перемотається приблизно за 10 с до цього моменту.",
        watchCopied: "Скопійовано: вставте в консоль запису",
        watchFailed: "Не вдалося скопіювати",
        bestOnHeroLine: (score) => `Ваш найкращий матч на герої (${score})`,
        bestOnHeroNote: (score, when) => `Пунктир — ваш найкращий матч на цьому герої, оцінка ${score} (${when}).`,
        bestOnHeroSelf: (of) => `Це ваш найкращий матч на цьому герої з ${of}.`,
        mapDeaths: "Смерті",
        killedBy: (hero) => `Смерть від ${hero}`,
        mapSide: { own: "на своїй половині", river: "біля річки", enemy: "на половині суперника" },
        mapWards: "Поставлено вардів",
        mapWardsLine: (obs, sen) => `${obs} оглядових · ${sen} сентрі`,
        chartLh: "Добивання",
        chartGold: "Золото",
        chartXp: "Досвід",
        you: "Ви",
        target: "Добрий темп",
        deathsMarker: "Смерть",
        minuteLabel: (m) => `${m}:00`,
        strengthsTitle: "Що вдалося",
        improveTitle: "Що покращити",
        foldMore: (n) => `Показати ще ${n}`,
        foldLess: "Згорнути",
        repeatInARow: (n) => `${n}-й матч поспіль — це звичка, а не випадковість`,
        repeatInLast: (n, of) => `Було й у ${n} з ${of} минулих матчів`,
        nothingToImprove: "Серйозних помилок у цьому матчі не знайдено.",
        nothingStrong: "Цього разу нічого не виділилося.",
        drill: "Вправа",
        momentsTitle: "Ключові моменти",
        adviceLogTitle: "Підказки під час матчу",
        adviceWhy: "Чому ця порада?",
        adviceRate: "Оцінити пораду (зберігається на цьому комп'ютері)",
        adviceVerdicts: { useful: "Корисно", irrelevant: "Не до речі", repeated: "Повторювалося" },
        adviceRateHint: "Позначте кілька карток: «Корисно», «Не до речі» або «Повторювалося». Позначки лишаються на цьому комп'ютері й показують, які поради виправити.",
        adviceLogHint: (n, urgent) => `${n} ${plural(n, "підказка", "підказки", "підказок")} за гру, термінових — ${urgent}. Варто перевірити, чи вдалося їм слідувати.`,
        adviceLogMore: (n) => `Показати всі (${n})`,
        adviceLogDeath: (time) => `Смерть о ${time}`,
        momentDeath: (killer) => (killer ? `Смерть від ${killer}` : "Смерть"),
        momentGold: (gold) => `${gold} золота на руках`,
        momentItem: (item) => item,
        momentBuyback: "Байбек",
        momentStall: (to) => `Провал у фармі до ${to}`,
        scoreboardTitle: "Підсумки матчу",
        radiant: "Сили Світла",
        dire: "Сили Темряви",
        colPlayer: "Гравець",
        colNw: "Вартість",
        colDmg: "Шкода",
        stats: {
          kda: "В / С / Д",
          gpm: "Золото й досвід за хвилину",
          lh: "Добивання / денаї",
          nw: "Вартість героя",
          dmg: "Шкода по героях",
          duration: "Тривалість",
          items: "Предмети наприкінці"
        },
        sectionFacts: {
          laning: (s) => [s.lh10 != null && `${s.lh10} добивань до 10:00`, s.lane_efficiency != null && `ефективність ${Math.round(s.lane_efficiency)}%`, s.lane_deaths ? `смертей на лінії: ${s.lane_deaths}` : null, s.runes != null && `рун: ${s.runes}${s.enemy_runes != null ? ` (у ворожого міда ${s.enemy_runes})` : ""}`],
          farm: (s) => [s.gpm != null && `${s.gpm} золота за хвилину`, s.gpm_pct != null && `краще, ніж у ${Math.round(s.gpm_pct * 100)}% гравців`],
          survival: (s) => [`смертей: ${s.deaths}`, s.deaths_per_10 != null && `${decimal(s.deaths_per_10)} за 10 хв`],
          fights: (s) => [s.kill_participation != null && `участь у вбивствах ${s.kill_participation}%`, s.stuns != null && `оглушень ${decimal(s.stuns)} с${s.enemy_stuns != null ? ` (у ворожого хардлайнера ${decimal(s.enemy_stuns)} с)` : ""}`, s.enemy_tower_damage != null && s.tower_damage != null && `шкода по будівлях ${number(s.tower_damage)} (у ворожого хардлайнера ${number(s.enemy_tower_damage)})`],
          items: (s) => [
            s.first_item && `${s.first_item.item} до ${clock(s.first_item.t)}`,
            s.save_item && `Рятівний предмет: ${s.save_item.item} до ${clock(s.save_item.t)}`,
            "save_item" in s && !s.save_item && "Немає рятівного предмета"
          ],
          vision: (s) => [s.obs_placed != null && `обсерверів: ${s.obs_placed}`, s.sen_placed != null && `сентрі: ${s.sen_placed}`, s.camps_stacked != null && `стаків: ${s.camps_stacked}`]
        },
        progressEmptyTitle: "Поки мало матчів",
        progressEmptyHint: "Статистика з'явиться після кількох розібраних матчів. Оновіть історію на вкладці «Матчі».",
        tiles: { winrate: "Вінрейт", kda: "KDA", gpm: "Золото за хвилину", lh10: "Добивання до 10:00", score: "Середня оцінка" },
        vsPrevious: (n) => `до минулих ${n}`,
        streakWin: (n) => `${n} ${plural(n, "перемога", "перемоги", "перемог")} поспіль`,
        streakLoss: (n) => `${n} ${plural(n, "поразка", "поразки", "поразок")} поспіль`,
        recordLine: (w, l, n) => `${w} ${plural(w, "перемога", "перемоги", "перемог")} і ${l} ${plural(l, "поразка", "поразки", "поразок")} за ${n} ${plural(n, "матч", "матчі", "матчів")}`,
        scoreChartTitle: "Оцінка за матчами",
        scoreChartHint: "Останні 20 матчів, старі ліворуч. Натисніть на стовпчик, щоб відкрити розбір; немає стовпчика — у матчу немає докладного розбору.",
        scoreLabel: "Оцінка",
        winKey: "перемога",
        lossKey: "поразка",
        baselineIntro: (games, hero) => `Проти ваших ${games} ${plural(games, "іншого матчу", "інших матчів", "інших матчів")} на ${hero}:`,
        baselineLabels: { score: "оцінка", gpm: "золото/хв", lh_10: "добивань до 10", deaths: "смертей" },
        baselineSame: "як зазвичай",
        baselineTitle: (average) => `Ваш середній: ${average}`,
        goalTitle: "Ваш фокус",
        goalHint: "Одна проблема за раз: у кожному наступному матчі видно, чи повторилася вона.",
        goalSince: (date) => `з ${date}`,
        goalProgress: (met, total) => `Вдалося в ${met} з ${total} ${plural(total, "матчу", "матчів", "матчів")}`,
        goalWaiting: "Зіграйте матч — після нього тут буде видно, чи вдалося.",
        goalStreak: (n) => `${n} ${plural(n, "матч", "матчі", "матчів")} поспіль без цієї помилки`,
        goalClear: "Зняти фокус",
        goalSet: "Зробити фокусом",
        goalSetFailed: "Не вдалося зберегти фокус, спробуйте ще раз",
        goalCurrent: "Фокус",
        goalMet: "вдалося",
        goalMissed: "повторилося",
        goalMatch: (title, met) => `Ваш фокус «${title}»: ${met ? "у цьому матчі вдалося" : "знову повторилося"}`,
        planTitle: "Над чим працювати",
        planHint: "Помилки, що повторюються в останніх матчах, і по одній вправі на кожну.",
        planEmpty: "Повторюваних помилок не знайдено — так тримати.",
        strengthsRecurring: "Ваші сильні сторони",
        heroesTitle: "Герої",
        colMatches: "Матчі",
        colWinrate: "Вінрейт",
        analyzed: (a, n) => `Детально розібрано ${a} з ${n} матчів`,
        buildTitle: "Збірка",
        lanesTitle: "Ваші лінії",
        lanesLine: (won, even, lost, games) => `З останніх ${games} ліній: виграно ${won}, на рівних ${even}, програно ${lost}.`,
        lanesGold: (diff) => `У середньому ${diff} золота проти суперника по лінії до 10-ї хвилини.`,
        lanesHard: (list) => `Лінії, програні не раз, проти: ${list}.`,
        lanesDot: (hero, enemy, result, diff) => `${hero} проти ${enemy}: ${result.toLowerCase()}, ${diff} золота до 10-ї хвилини`,
        laneTitle: "Лінія",
        laneVs: "проти",
        laneResult: { won: "Лінію виграно", even: "Лінія на рівних", lost: "Лінію програно" },
        laneMinute: (m) => `${m}:00`,
        laneColMinute: "Хвилина",
        laneColLh: "Добивання",
        laneColDn: "Денаї",
        laneColGold: "Золото",
        laneColXp: "Досвід",
        laneTurn: (m) => `Розрив з'явився з ${m}-ї хвилини.`,
        laneOthers: (heroes, diff) => `Ще на лінії: ${heroes}; золото всієї лінії до 10-ї хвилини: ${diff}.`,
        laneNote: "Ви : суперник; золото й досвід — різниця. За розібраним записом матчу.",
        skillsTitle: "Прокачка",
        skillsYours: "Ваше перше:",
        skillsPro: "Як максять уміння про-гравці на цьому герої:",
        skillsSame: (name) => `Першою ви прокачали до кінця ${name} — як і про-гравці.`,
        skillsDiff: (yours, pro) => `Першою ви прокачали до кінця ${yours}, а про-гравці починають з ${pro}.`,
        skillsNote: (agree, games) => `Так починають ${agree} з ${games} нещодавніх про-матчів. Підказка в грі назве, куди вкласти кожне очко.`,
        buildTimingNote: "Вінрейт героя залежно від часу покупки (публічні матчі OpenDota). Ваш таймінг виділено. Найраніші таймінги — найчастіше ігри, які й так ішли добре, тому мета — звичайний таймінг.",
        buildNoTimings: "Щодо цих предметів поки немає даних про таймінги.",
        buildItemLine: (wr, t, typicalT, typicalWr) => `${wr}% перемог при покупці до ${t} · зазвичай купують до ${typicalT}: ${typicalWr}%`,
        buildItemTypical: (wr, t) => `${wr}% перемог при покупці до ${t} · звичайний таймінг для героя`,
        buildBy: (t) => `до ${t}`,
        buildPopular: "Часта збірка (про-гравці)",
        buildPhase: { early: "Початок", mid: "Основа", late: "Пізня гра" },
        buildBought: "куплено",
        buildTimingTip: (t) => `Покупка до ${t}`,
        winrateLabel: "Вінрейт",
        rankTitle: "Ви й ваш ранг",
        rankMatchNote: (rank, role, heroes) => `${rank ? `Ранг матчу: ${rank} · ` : ""}порівняння з ${role} цього матчу${heroes ? ` (${heroes})` : ""}`,
        rankNoPeers: "У цьому матчі немає гравця тієї самої ролі для порівняння.",
        colMetric: "Показник",
        colYou: "Ви",
        colOpponent: "Суперник",
        colPeers: "Ваш ранг",
        colDiff: "Різниця",
        metrics: { gpm: "Золото за хвилину", xpm: "Досвід за хвилину", lh_10: "Добивання до 10:00", lh_per_min: "Добивань за хвилину", deaths: "Смерті", kda: "KDA", damage_per_min: "Шкода за хвилину", net_worth: "Вартість героя" },
        rankCareerTitle: "Ви й гравці вашого рангу",
        rankCareerNote: (rank, role, n) => `${rank || "Ваш ранг"} · ${role} · гравці тієї самої ролі у ваших ${n} розібраних матчах`,
        rankCareerEmpty: "З'явиться після кількох матчів, розібраних за даними OpenDota.",
        colBracket: "На вашому ранзі",
        bracketHint: (rank) => `Вінрейт героя в усіх гравців рангу ${rank} (OpenDota)`,
        shareButton: "Поділитися",
        shareTitle: "Поділитися розбором",
        shareWhat: "Сторінка з цим розбором: герой, результат, оцінка, цифри матчу, розділи й що покращити. Відкрити її зможе будь-хто, у кого є посилання.",
        shareNot: "Не публікується: номер матчу, ваш Steam ID, нік та інші гравці. Посилання працює 90 днів, його можна видалити будь-коли.",
        shareCoach: "Додати висновок ШІ-тренера",
        shareCreate: "Створити посилання",
        shareCreating: "Створюю посилання…",
        shareLink: "Посилання на розбір",
        shareCopy: "Копіювати",
        shareCopied: "Скопійовано.",
        shareOpen: "Відкрити",
        shareDelete: "Видалити посилання",
        shareDeleted: "Посилання видалено.",
        shareExpires: (date) => `Працює до ${date}.`,
        shareWithCoach: "З висновком ШІ-тренера.",
        shareFailed: (code) => `Не вдалося${code ? ` (${code})` : ""}: перевірте інтернет і спробуйте ще раз.`,
        shareTitleProgress: "Поділитися прогресом",
        shareWhatProgress: "Сторінка з вашим прогресом по всіх героях: матчі, відсоток перемог, середні цифри, останні 10 матчів проти 10 до них, головні герої, що вдається й над чим працювати. Відкрити її зможе будь-хто, у кого є посилання.",
        shareNotProgress: "Не публікується: номери матчів, ваш Steam ID, нік, інші гравці й ваші запитання тренерові. Посилання працює 90 днів, його можна видалити будь-коли.",
        shareLinkProgress: "Посилання на прогрес",
        trendTitle: (item) => `${item}: таймінг за іграми`,
        trendLine: (recent, n, before, m) => `Останні ${n} ${plural(n, "гра", "гри", "ігор")}: ${recent}; ${m} ${plural(m, "гра", "гри", "ігор")} до того: ${before}.`,
        trendRecentOnly: (recent, n) => `Останні ${n} ${plural(n, "гра", "гри", "ігор")}: ${recent} (медіана).`,
        trendSooner: (gap) => `на ${gap} раніше`,
        trendLater: (gap) => `на ${gap} пізніше`,
        trendSame: "приблизно так само",
        trendMinute: "Хвилина",
        deathMapTitle: "Де ви помираєте",
        deathMapNote: (matches, total, per) => `${total} ${plural(total, "смерть", "смерті", "смертей")} у ${matches} ${plural(matches, "матчі", "матчах", "матчах")} з мапою, ${String(per).replace(".", ",")} за матч.`,
        deathMapTurned: "Ігри за Сили Темряви повернуто на пів оберту: ваша база завжди ліворуч унизу.",
        deathMapSpot: (place, count, matches) => `${place}: ${count} ${plural(count, "смерть", "смерті", "смертей")} у ${matches} ${plural(matches, "матчі", "матчах", "матчах")}`,
        deathMapSpots: "Тут смерті повторюються:",
        deathMapLate: (pct) => `Після 10-ї хвилини на половині суперника: ${pct}% смертей`,
        opponentsTitle: "Ворожі герої",
        opponentsNote: (n, min) => `Ваш рахунок проти кожного ворожого героя в ${n} матчах з відомим складом (герої, зустрінуті ${min}+ рази).`,
        opponentsHard: "Проти них найважче",
        opponentsEasy: "Їх ви обігруєте найчастіше",
        opponentRecord: (w, l, wr) => `${w}–${l} · ${wr}%`,
        poolTitle: "Ваш пул героїв",
        poolNote: "Ваш відсоток перемог на кожному герої (від 4 ігор) проти того, як на ньому грають гравці вашого звання.",
        poolMore: "Грайте на них частіше",
        poolPark: "Їх краще поки відкласти",
        poolRecord: (w, n, wr, br) => `${w} з ${n} перемог · ${wr}%${br == null ? "" : ` (на вашому званні ${br}%)`}`,
        goalsTitle: "Ваші цілі",
        streaksTitle: "Серії",
        goalMakeTop: (title) => `Зробити фокусом: ${title}`,
        zoneGoals: "Цілі",
        zoneGoalsHint: "Над чим ви працюєте і як минули останні матчі",
        summaryLast: "Останній матч",
        summaryTip: "Головне виправити",
        summaryStrength: "Що вдалося",
        summaryOpen: "Відкрити розбір",
        summaryToday: "Сьогодні",
        summaryNoGames: "Сьогодні матчів ще не було",
        summaryFocus: "Ваш фокус",
        summaryFocusProgress: (met, total) => `вдалося в ${met} з ${total}`,
        summaryNoFocus: "Оберіть одну проблему, над якою працювати: тренер перевірить за нею кожен матч.",
        summaryPickFocus: "Обрати в «Прогресі»",
        streakFewDeaths: (target) => `${target} ${plural(target, "матч", "матчі", "матчів")} поспіль — не більше 5 смертей`,
        streakGoodScore: (target) => `${target} ${plural(target, "матч", "матчі", "матчів")} поспіль з оцінкою 60+`,
        streakProgress: (cur, target) => `${Math.min(cur, target)} з ${target}`,
        streakMet: (cur) => `виконано: ${cur} поспіль`,
        streakBest: (best) => `Найкраща серія за останні 30 матчів: ${best}`,
        tiltLosses: (n) => `${n} ${plural(n, "поразка", "поразки", "поразок")} поспіль. Може, перерва — або зіграйте щось просто для задоволення.`,
        tiltScore: (a, b, usual) => `Дві останні оцінки — ${a} і ${b}, а зазвичай у вас близько ${usual}. Може, зробити перерву?`,
        friendTitle: "Порівняння з другом",
        friendHint: "Friend ID друга, Steam ID або посилання на профіль (steamcommunity.com/profiles/…). Порівнюються відкриті матчі з OpenDota: останні 20 ігор кожного.",
        friendPlaceholder: "Friend ID, Steam ID або посилання на профіль",
        friendCompare: "Порівняти",
        friendSelf: "Це ваш власний акаунт.",
        friendFailed: "Не вдалося зберегти друга.",
        friendLoading: (name) => `Завантажую матчі ${name} з OpenDota…`,
        friendPrivate: (name) => `${name} приховує дані матчів.`,
        friendPrivateHint: "Їх можна відкрити в Dota 2: Налаштування → Спільнота → «Відкрити дані матчів». Потім натисніть «Оновити» (OpenDota потрібен хоча б один матч після цього).",
        friendOffline: "Для порівняння потрібен OpenDota (інтернет).",
        friendError: (code) => `OpenDota не відповів${code ? ` (${code})` : ""}. Спробуйте «Оновити» пізніше.`,
        friendRefresh: "Оновити",
        friendUpdating: "Оновлюю…",
        friendChange: "Інший друг",
        friendGroup: "Ігри",
        friendGroups: { all: "Усі ігри", core: "Кор", support: "Саппорт" },
        friendYou: "Ви",
        friendGames: (me, friend) => `ігор: у вас ${me}, у друга ${friend}`,
        friendFew: (n) => `Замало ігор, щоб сказати, хто попереду: потрібно ${n}+ у кожного.`,
        friendMetrics: { win_rate: "Відсоток перемог", kills: "Вбивства", deaths: "Смерті", assists: "Допомога", gpm: "Золото за хвилину", xpm: "Досвід за хвилину", lh_per_min: "Добивання за хвилину", damage_per_min: "Шкода по героях за хвилину" },
        friendCommon: "Герої, на яких грали обидва",
        friendHeroGames: (g1, w1, g2, w2) => `ви ${g1} · ${w1 ?? "—"}%   друг ${g2} · ${w2 ?? "—"}%`,
        friendTheirHeroes: (name) => `Найчастіше грає ${name}`,
        friendNote: "Середні за гру, відкриті дані OpenDota, лише рейтингові й звичайні режими. Кор чи саппорт — за добиваннями за хвилину.",
        rankHistoryTitle: "Ваше звання",
        rankUp: (from, to, since) => `З ${since} ви піднялися з ${from} до ${to}.`,
        rankDown: (from, to, since) => `З ${since} звання знизилося з ${from} до ${to}.`,
        rankNote: "Застосунок запам'ятовує ваше звання щоразу, коли оновлює історію, і позначає, коли воно змінюється.",
        heroBuildTitle: (hero) => `Ваш білд на ${hero}`,
        buildNote: (n, wins) => `Ваші предмети в ${n} розібраних матчах на герої (перемог: ${wins}): коли вони з'являються в перемогах і в поразках і як часто ви виграєте з ними й без них.`,
        buildItem: "Предмет",
        buildGames: "Ігор",
        buildWinrate: "Перемог із ним",
        buildWithout: "Без нього",
        buildWinTime: "У перемогах",
        buildLossTime: "У поразках",
        selfTitle: (hero) => `Найкращі й найгірші матчі на ${hero}`,
        selfNote: (n) => `Найкраща третина з ${n} останніх розібраних матчів на герої проти найгіршої третини, за оцінкою розбору.`,
        selfBest: "Найкращі",
        selfWorst: "Найгірші",
        selfGroup: (count, wr) => `${count} матчі · ${wr}% перемог`,
        selfMetrics: {
          lh_10: "Добивання до 10:00",
          gpm: "Золото/хв",
          deaths: "Смерті",
          lane_deaths: "Смерті на лінії",
          kill_participation: "Участь у вбивствах",
          first_item_t: "Перший великий предмет"
        },
        draftTitle: "Драфт",
        draftNote: (hero) => `Як часто ${hero} перемагає кожного ворожого героя (статистика публічних матчів OpenDota).`,
        draftNoData: "Статистики щодо цих героїв поки немає: вона завантажиться під час наступного оновлення історії.",
        draftEnemy: "Ворог",
        draftWinrate: "Ваш вінрейт",
        draftGames: "ігор",
        draftPool: "Ваші герої проти цього складу",
        draftPoolNote: "Середня перевага за вінрейтом над 50% проти цих п'яти героїв.",
        draftPicked: "ваш пік",
        draftBetter: (hero) => `Найкраще проти цього складу підходив ${hero}.`,
        draftCounters: "Відповіді на ворожих героїв",
        draftReasons: { evasion: "ухилення", illusions: "ілюзії", invisibility: "невидимість", healing: "лікування", targeted: "убивав контролем" },
        draftForSupports: "завдання саппорта",
        draftBought: "куплено",
        coachTitle: "Розбір тренера",
        coachCareerTitle: "Розбір тренера за останніми матчами",
        coachTag: "ШІ",
        coachPending: "Тренер пише розбір. Це займає до хвилини.",
        coachCareerPending: "Тренер дивиться ваші останні матчі. Це займає до хвилини.",
        coachWaiting: "ШІ чекає, поки OpenDota вивчить реплей (зазвичай кілька хвилин): так у нього більше даних.",
        coachNow: "Розібрати зараз",
        coachUpdating: "Оновлюється за новими даними…",
        coachRetry: "Повторити",
        coachRewrite: "Написати заново",
        coachNotEnough: (n) => `Тренерові потрібно щонайменше ${n} розібрані матчі.`,
        coachTurning: "Ключові моменти",
        coachMistakes: "Головні помилки",
        coachFix: "Наступного разу",
        coachStrengths: "Що вдалося",
        coachNextGame: "Цілі на наступну гру",
        coachPatterns: "Повторювані проблеми",
        coachTrain: "Як тренувати",
        coachPlan: "План на наступні ігри",
        coachFooter: (provider, model) => `Написано ШІ (${provider} · ${model}) за даними розбору. Числа, час, герої й предмети звірено з ними.`,
        coachErrors: {
          rate_limited: "Безкоштовний ліміт ШІ поки вичерпано. Спробуйте за кілька хвилин.",
          busy: "ШІ зараз перевантажений. Спробуйте за кілька хвилин.",
          invalid_key: "Ключ не підійшов. Перевірте його в налаштуваннях ШІ-тренера.",
          region: "Цей ШІ не працює з вашої країни. Оберіть інший (наприклад, OpenRouter) або ввімкніть VPN; ключ збережено.",
          timeout: "ШІ надто довго відповідав.",
          offline: "Немає зв'язку з ШІ: перевірте інтернет.",
          unverified: "У відповіді ШІ були факти, яких немає в даних, тому її не показано. Спробуйте ще раз.",
          bad_response: "ШІ відповів помилкою. Спробуйте пізніше.",
          no_key: "Ключ ще не вказано."
        },
        askTitle: "Запитати тренера",
        askHint: "Запитання про цей матч. Відповідь будується лише за даними матчу й проходить ту саму перевірку фактів.",
        askPlaceholder: "Наприклад: чому я програв лінію?",
        askButton: "Запитати",
        askThinking: "Тренер думає…",
        askSuggestions: ["Що вирішило цю гру?", "Що змінити на лінії?", "Чи вчасно я зібрав предмети?"],
        askCareerHint: "Запитання про ваші останні матчі: герої, суперники, звички. Відповідь будується лише за вашою статистикою й проходить ту саму перевірку фактів.",
        askCareerPlaceholder: "Наприклад: проти яких героїв мені найважче?",
        askCareerSuggestions: ["Проти яких героїв мені найважче?", "Яка помилка коштує мені найбільше ігор?", "На якому герої мені варто грати частіше?"],
        askErrors: {
          unverified: "Тренер не зміг відповісти за даними цього матчу. Спробуйте запитати інакше.",
          empty_question: "Спершу напишіть запитання.",
          no_review: "Розбір цього матчу ще не готовий.",
          not_enough: "Поки мало розібраних матчів: спершу відкрийте кілька розборів.",
          off: "Спершу ввімкніть ШІ-тренера в налаштуваннях.",
          pending: "Відповідь готується довше, ніж зазвичай. Запитайте ще раз за хвилину — поки вона готується, повторне запитання дочекається тієї самої відповіді.",
          bad_request: "Не вдалося надіслати запитання. Запитайте ще раз."
        },
        aiSettingsTitle: "ШІ-тренер",
        aiOnTitle: "ШІ-тренера ввімкнено",
        aiCheckNow: "Перевірити ключ",
        aiCheckOk: "Ключ працює.",
        aiOffTitle: "ШІ-тренера вимкнено",
        aiOffHint: "Після кожного матчу ШІ простими словами пояснює, що вдалося й що виправити, — як тренер, що подивився ваш реплей. Безкоштовно: потрібен лише ключ від Google (Gemini), Groq або OpenRouter.",
        aiTurnOn: "Увімкнути",
        aiSetupHint: "Ключ — це як пароль, з яким застосунок може звертатися до ШІ. Отримайте безкоштовний (хвилина, без картки) і вставте сюди. ШІ лише пояснює: усі числа, як і раніше, беруться з розбору. Дані матчу (без вашого Steam ID) ідуть на обраний сайт.",
        aiService: "Звідки ключ",
        aiKey: "Ключ",
        aiKeyPlaceholder: "Вставте ключ",
        aiModel: "Модель ШІ",
        aiAdvanced: "Для досвідчених",
        aiModelHint: "залиште порожнім — буде типова",
        aiGetKey: "Отримати безкоштовний ключ",
        aiSave: "Перевірити й зберегти",
        aiChecking: "Перевіряємо ключ…",
        aiSaved: "Ключ працює. Тренера ввімкнено.",
        aiSavedWarn: (reason) => `Ключ збережено, але перевірка не пройшла: ${reason}`,
        aiSettings: "Налаштування ШІ",
        aiCurrent: (provider, model, hint) => [provider, model, hint ? `ключ ${hint}` : ""].filter(Boolean).join(" · "),
        aiEnvKey: "Ключ уже задано у файлі налаштувань застосунку.",
        aiChangeKey: "Змінити ключ",
        aiDisable: "Відключити",
        aiCancel: "Скасувати"
      }
    };
    return TEXT;
  }

  const exported = { create };
  if (typeof module === "object" && module.exports) module.exports = exported;
  else window.WardlyMatchTexts = exported;
})();
